### ISSUE TITLE
Periodic segfault/malloc issues in macOS repl when using tag unions

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1073]
Sometimes when running repl tests, we see errors like this in tests that involve tag unions:

```
roc(41971,0x118087dc0) malloc: *** error for object 0x7fcad9d1d8a0: pointer being freed was not allocated
roc(41971,0x118087dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```

```
roc(42941,0x11cff6dc0) malloc: Incorrect checksum for freed object 0x7fb790f599a0: probably modified after being freed.
Corrupt value: 0x7ffee8411c88
roc(42941,0x11cff6dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```

This can manifest as a segfault:

```
---- repl_eval::num_add_checked stdout ----
thread 'repl_eval::num_add_checked' panicked at 'repl segfaulted during the test. Stderr was ""', cli/tests/helpers.rs:343:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We can also sometimes see these segfaults when running the repl manually, but not always - try running `List.first [ 1, 2, 3 ]` a few times on macOS to reproduce it.

It seems some pointer is pointing to the wrong memory, because in some rare cases it's even overwriting memory outside the normal program - in this case, overwriting some of the memory in the `ena` data structure:

```
thread 'main' panicked at 'index out of bounds: the len is 120 but the index is 3950083208', /Users/rtfeldman/code/roc/vendor/ena/src/snapshot_vec.rs:151:10
```

```
thread 'main' panicked at 'Unexpected FlatType FlexVar(None) in num_to_ast', cli/src/repl/eval.rs:846:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

One potential clue is that mono IR consistently prints this out when running these tests in isolation:

```
emitted runtime error VoidValue
```

**Comment by isaacvando** [comment]
Hard to say if this still relevant or not because it is intermittent, but I ran `List.first [ 1, 2, 3 ]` in the repl on my Mac about 30 times and didn't have any issues so I'm going to close the issue.
