### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1085]
Full error:
```
+test-rust *failed* | Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
+test-rust *failed* | error: test failed, to rerun pass '-p test_gen --lib'
```
This is a bug in glibc. The error only shows up sometimes because it is a race condition.
bug trackers:
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1863162
https://sourceware.org/bugzilla/show_bug.cgi?id=19329
This error was first reported in 2015, a patch is available but it will likely take a while before it is merged in.

For CI, a possible fix would be to:
1. capture errors for  `cargo test --release`with `2> err_log.txt`
2.  Check if this is the `Inconsistency detected by ld.so ...` error
3. Re-run `cargo test --release` if true, print the contents of `err_log.txt` with the appropriate exit code if false.

**Comment by JanCVanB** [comment]
I hit this now when following [the Roc installation guide for Linux](https://github.com/roc-lang/roc/blob/main/getting_started/linux_x86_64.md):
```
[jan@framey roc]$ sudo dnf check-update && sudo dnf install clang
Last metadata expiration check: 0:18:50 ago on Sun 29 Oct 2023 09:13:32 PM MDT.

crun.x86_64                1.11-1.fc38                 updates
[jan@framey roc]$ roc version
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
roc nightly pre-release, built from commit c509252 on Fr 27 Okt 2023 09:07:30 UTC
[jan@framey roc]$ roc ./examples/platform-switching/rocLovesC.roc 
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
🔨 Rebuilding platform...
Roc <3 C!
Inconsistency detected by ld.so: dl-runtime.c: 63: _dl_fixup: Assertion `ELFW(R_TYPE)(reloc->r_info) == ELF_MACHINE_JMP_SLOT' failed!
[jan@framey roc]$ 
```

**Comment by Anton-4** [comment]
Thanks for reporting this @JanCVanB! I did make a separate issue for this (#5943) because it does seem to be different from the first case.

**Comment by isaacvando** [comment]
Have you run into this bug recently @Anton-4?

**Comment by Anton-4** [comment]
No :+1:
