### ISSUE TITLE
Hash Links in docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1108]
If I write (for example) `The #Num.abs function` in a doc string, that should get converted to a link to the docs for the `Num.abs` function, because I put the `#` in there.

The rules for how this should work:

* If there's a `#` followed immediately by a letter in a doc string (but outside a code block), we parse that as a hash link.
* Hash links use the module's scope to resolve the identifiers and figure out what to link to. (For example, if the module has `foo` imported unqualified, then I can reference it with `#foo`, and if the module header has `Json.Decode` imported `as JD` then `#JD.str` should link to the docs for `Json.Decode.str`)
* If there's a naming error when resolving one of these (e.g. we encounter `#blah` but we can't find a `blah` in scope), we should report it as a naming error in the console. Like with all other Roc compilation, this shouldn't block progress (we should generate a broken link there and continue), but it should mean we exit with a nonzero status when the command finishes.
* If you actually really want a `#` there, and don't want it to become a link, we should allow this with `\#`. If you really want to write a `\#`, then you'd write `\\#` instead.

**Comment by skyqrose** [comment]
Links in docs exist now (though with `[]` instead of `#`). Here's a random example: https://github.com/roc-lang/roc/blob/b7c2cb084e15a56320e652ad3c77fdb8262bc1a4/crates/compiler/builtins/roc/Str.roc#L530
