### ISSUE TITLE
Syntax Highlighting in HTML docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1123]
We should have syntax highlighting in our generated documentation. Importantly, *this should not be done with JavaScript!* The HTML docs are designed to have extremely fast performance and minimal memory usage, and as such they run the bare minimum of JS possible. We should do that highlighting in the generated HTML itself at generation time, not at runtime!

**Comment by lukewilliamboswell** [comment]
This sounds similar to #5051. I will add to my list to look at this, but it we should be able to use the same roc_parse::highlight module in the same way.

**Comment by skyqrose** [comment]
Done in https://github.com/roc-lang/roc/pull/5097
