### ISSUE TITLE
CI context deadline exceeded

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1131]
This error show up from time to time:
```
output | --> exporting outputs
output | WARN: (exporting outputs) no active session for yocq5xvnvdgri5jdj82sry05v: context deadline exceeded
```
I did some searching and have yet to find a possible cause or fix.

**Comment by isaacvando** [comment]
Hey @Anton-4, do you know if this issue has come up any recently?

**Comment by Anton-4** [comment]
No, I think it form back when we used earthly for CI. Thanks for alerting me :)
