### ISSUE TITLE
Editor allows multiple consecutive spaces outside of indents

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1141]
Currently, it's possible to put multiple spaces after (for example) a record field:

<img width="166" alt="Screen Shot 2021-03-31 at 7 20 22 PM" src="https://user-images.githubusercontent.com/1094080/113223045-4ce74600-9256-11eb-9e54-697c61937434.png">

In general, I think it'll be nicest if we try to keep the code formatted the same way Roc's formatter would format it - which is to say, the only places multiple consecutive spaces would ever appear would be when indenting.

I think ideally the way this would work would be:
* If I press spacebar, and there's already a space before the caret, and I'm not currently indenting something...
* ...we should not add a space
* ...but we should give the user some indication of having registered the keystroke and intentionally not added anything, e.g. displaying a brief explanation in a status bar or something.
 
We can figure out exactly how that indication would work separately from this issue (cc @popara - definitely a design question that fits into bigger designs!) but I've often found it confusing when I press a button in an application that normally does something, the application doesn't appear to do anything, and also doesn't tell me why...I generally think "something is broken!" and then, after pressing it a few times "...or maybe it's working as intended, and I'm not allowed to do that here? But if so, why not?" - and I think we can do better than that!

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
