### ISSUE TITLE
Dict values can only grow, but not shrink

### ISSUE THREAD

**Issue by Chadtech** [roc-lang/roc#1150]
The `Dict` type is a list under the hood, that grows longer when entries collide.

Removing an entry however, doesnt make the `Dict` shrink.

So, as it is today, any long running Roc code with a `Dict` in it will see that `Dict` grow and grow in its memory size.

What should be the strategy for shrinking a `Dict`? I could imagine the code in `remove : Dict key value, key -> Dict key value` reads like "If the `key` is towards the end of the `Dict key value` cut off the entire tail end of the `Dict`.

**Comment by skyqrose** [comment]
Based on Richard's comment, closing as won't do.
