### ISSUE TITLE
Remove multiple `provides` in app modules

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1178]
Currently `provides` in app modules typically looks like this:

```coffeescript
provides [ main ] to base
```

However, in retrospect, allowing multiple `provides` was a mistake. We should change it to:

```coffeescript
provides main to base
```

...and make the corresponding change on the platform side as well.

**Comment by skyqrose** [comment]
A lot has changed in the app header since this was made, and also providing multiple functions works now.
