### ISSUE TITLE
Defs in repl no longer accepted

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1187]
It used to be the case that I could write `foo = 5` in the repl, and it would detect an incomplete def-expression and give me a `…` prompt so I could continue adding defs or else finish the expression.

Now instead when I put in a def, there's an immediate `MISSING FINAL EXPRESSION` error.

We could fix this bug, or we could go for the ambitious approach of changing the repl to allow top-level module defs instead - so if I type `foo = 5` it records that as a top-level decl, leaves it in scope for the rest of the repl session, and then proceeds to ask me for another expression (or another decl).

**Comment by Ivo-Balbaert** [comment]
At this moment a top level decl like foo = 5 is simply accepted in the repl:

» foo = 5

5 : Num *                  # foo

»

Does this address all concerns of this issue?

**Comment by Anton-4** [comment]
I think so, thanks for notifying us @Ivo-Balbaert :)
