### ISSUE TITLE
Setting `PresentMode` to `Immediate` causes freeze on close after something has been selected. (so far only seen on Nvidia GPU, Ubuntu 20.04)

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1206]
To reproduce:
1. change both occurrences of `PresentMode::MailBox` to `PresentMode::Immediate` in `editor/src/editor/main.rs `.
2. Start editor with `cargo run edit`
3. type `"test`
4. press `ctrl+shift+up`
5.  try to close the window

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
