### ISSUE TITLE
Investigate dynamically switching between `PresentMode::Immediate` when typing and `PresentMode::Mailbox` otherwise.

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1211]
Quote from Richard:

> Here's a thought:
>
> Immediate is wonderful for text input; if I switch back and forth between Immediate and MailBox, and type as fast as I can, there's a very noticeable difference in how snappy the text feels when it appears on the screen.
>
> Any other time, I doubt it's noticeable. Actually it is noticeable when I move my mouse, in the sense that the cursor stutters in Immediate mode (presumably because it's trying to repaint on every mousemove event) and not in MailBox mode.
>
> I wonder if it would be worth our switching between the two - like repaint with Immediate mode right after a keyboard event, so the pixels hit the screen as soon as possible, and for all other events, use MailBox?

`gpu_device.create_swap_chain` will need to be called to switch `PresentMode`, the main risk is that would introduce noticeable lag.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
