### ISSUE TITLE
"label only" type variable missing in alias crashes but does not error

### ISSUE THREAD

**Issue by Chadtech** [roc-lang/roc#1233]
Putting this in a Roc program crashes, when really it should error.
```
Namey : { name }
```
It should error with something like "the type variable name appears in the type but not in the alias" - and ideally a hint like "Did you mean Namey name instead?" instead, since its really syntax sugar for..
```
Namey : { name: name }
```

**Comment by Ivo-Balbaert** [comment]
At this time the following program:
```coffee
main =
    Namey : { name }
    Stdout.line "Hello, World!"
```

does not crash, but gives an error:
── UNBOUND TYPE VARIABLE ─────────────────────────────────────────── test1.roc ─

The definition of Namey has an unbound type variable:

9│      Namey : { name }
                  ^^^^

Tip: Type variables must be bound before the :. Perhaps you intended
to add a type parameter to this type?

────────────────────────────────────────────────────────────────────

1 error and 2 warnings found in 31 ms.

Does this address your concern? Could you look into this @Anton-4 ? Thanks
However:  Namey : { name: name }  gives the same error.

**Comment by Anton-4** [comment]
Yeah, the crash no longer occurs but the error message is not very helpful. I'll make a new issue for that.
