### ISSUE TITLE
Editor increasing memory consumption while idle

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1248]
The culprit is `create_buffer_init` called by `create_rect_buffers`.
The solution would be to execute this function only once and allocate space for the maximum amount of rectangles we would expect to need. An example of this workflow can be found in this [file](https://github.com/hecrj/iced/blob/master/wgpu/src/quad.rs) from the iced project.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
