### ISSUE TITLE
Eliminate `libc++` and `libunwind` dependencies

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1267]
Currently, compiling Roc programs relies on `libc++` and `libunwind` for `cxa_throw` and friends. This means anyone who wants to build a Roc program needs to have `libc++` and `libunwind` installed on their system.

That's undesirable for several reasons, including how it blocks the goal to have people be able to download the `roc` static executable and be able to run it without needing anything else installed!

Since both `libc++` and `libunwind` are MIT-licensed, we can bundle only the parts we need into `roc_std` and remove the step where we link in `libc++` and `libunwind`. While we're at it, we can also rename them to things like `roc_throw`, to prevent namespace conflicts in hosts in case we ever decide to make Roc-specific changes to how they work.

This issue will be resolved when we can remove [this step](https://github.com/rtfeldman/roc/blob/b775b39fe4ad9dea6aa07477728462010debb2f2/BUILDING_FROM_SOURCE.md#libunwind--libc-dev) from `BUILDING_FROM_SOURCE` and have everything still work!

**Comment by skyqrose** [comment]
Done in https://github.com/roc-lang/roc/pull/1605
