### ISSUE TITLE
Unresolved type variable when creating layout

### ISSUE THREAD

**Issue by tskj** [roc-lang/roc#1305]
## Example to repro:

```
app "hello-world"
    packages { base: "platform" }
    imports []
    provides [ main ] to base

main =
    when (accept "B" pReturn) [ "B" ] is
        Ok (Pair result _) -> result

pReturn =
    \ x ->
        \ input -> Ok (Pair x input)

# dummy-implementation that returns "A" always
accept =
    \ _token, _c ->
        pReturn "A"
```

Interestingly, the same implementation but with line 7 changed to:

```
    when (accept "B" 1) [ "B" ] is
```

where `1` is just a dummy value which can be anything since it's not used, does work.

I've tried typing stuff explicitly, but I'm not sure I've gotten all the types right.

## Error message:

![image](https://user-images.githubusercontent.com/25415972/118333798-a6f15180-b50c-11eb-8e7e-5ea288f66834.png)

**Comment by isaacvando** [comment]
This no longer repros for me.
