### ISSUE TITLE
Record syntax for `imports`, `provides` and friends

### ISSUE THREAD

**Issue by tskj** [roc-lang/roc#1310]
Ref this discussion https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/syntax.20for.20provides/near/238981071

`imports` and `provides` really should leverage existing syntax for records, because they have the same semantics. Today we have this syntax:

```
app "http-get"
    packages { base: "platform" }
    imports [ base.Task.{ Task, await }, base.Stdout, base.Stdin, base.Http ]
    provides [ main ] to base
```

However, it would make much more sense if these used the already established record syntax instead of a list-like syntax, exactly because the arguments are named and not positional. This would be one less thing for people to learn - we could leverage the existing intuition for records.

In the following example `imports` looks and behaves just like record destructuring, and `provides` looks and behaves just like constructing a record.

```
app "http-get"
    packages { base: "platform" }
    imports { base.Task.{ Task, await }, base.Stdout, base.Stdin, base.Http }
    provides { main } to base
```

For this to make sense and be consistent, we probably also should allow the none-shortcut syntax for constructing a record, also opening the door for folks to call their function something other than what the platform requires (in this case `main`).

```
provides { main: myMain } to base
```

**Comment by skyqrose** [comment]
The app header has evolved a few times since this issue was created. This is no longer relevant.
