### ISSUE TITLE
Seamless Slices for Strings and Lists

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1361]
See [this doc](https://docs.google.com/document/d/1sYA8lgUW836OJoH_kFJz1WPzwJrFLnWbTCCYNhMSI80/edit?usp=sharing) for motivation and explanation.

A change from the doc: instead of treating negative capacity as a negative offset, instead treat it as a bit-shifted pointer. (Shift it over 1 bit to obtain a valid pointer to the refcount.) This will always be possible, because pointers always have one spare bit even on 16-bit targets.

This change makes it easy to use seamless slices as an `Rc` equivalent in the host, when you have an existing heap allocation and want to pass it into Roc with a refcount, but you don't have a slot for the refcount right before the existing allocation. This would mean you wouldn't have to reallocate and copy everything over.

Additionally, we should move storage of "this memory is readonly, so don't increment the refcount" from being stored on the heap to being stored on the stack (specifically, a capacity of 0 with a non-null pointer should mean "this memory is readonly"). This would have a few benefits:
* Not having to chase a pointer to check whether refcounting is allowed (the biggest benefit; can potentially save a lot of cache invalidations and misses for long static strings)
* Less total memory usage and lower total binary size
* Might help address the valgrind issue which blocked further optimization of atomic refcounts in https://github.com/rtfeldman/roc/pull/3684

**Comment by rtfeldman** [comment]
Now that https://github.com/roc-lang/roc/issues/2871 is closed, I think this can be closed too!

@bhansconnect thoughts?

**Comment by bhansconnect** [comment]
Oh yeah. For sure 😃
