### ISSUE TITLE
Automatically coordinate www and trunk branches

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1383]
Whenever we merge a PR into the `www` branch, it deploys to Netlify. The reason for having this branch be separate from `trunk` is so that we aren't using Netlify build minutes on every single `trunk` build - plus, having all those status checks is unnecessary for almost all PRs.

That said, we should keep them in sync by making a GitHub Action which makes it so that whenever `www` gets commits, we merge `www` into `trunk` automatically. (But not the reverse! We should update `www` manually when we want to make a PR into it.)

**Comment by skyqrose** [comment]
The `trunk` branch doesn't exist anymore and the newest commit on the `www` branch is more than 2 years old, so I'm pretty sure this isn't relevant anymore.
