### ISSUE TITLE
Show Roc cheat sheet on editor startup

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1398]
When `ed_model.markup_root_id` points to a `Blank` node, a Roc cheat sheet should be displayed below the current line.
-  `ed_model.markup_root_id` contains the id to the root of the Abstract Syntax Tree of the current file.
- Get the root node with `ed_model.markup_node_pool.get(ed_model.markup_root_id)`.
- Check [roc-for-elm-programmers](https://github.com/rtfeldman/roc/blob/trunk/roc-for-elm-programmers.md) for inspiration on the cheat sheet.
- Take a look at the flow for `START_TIP` to see how to draw the cheat sheet string to the screen.
- The cheat sheet should not have any syntax highlighting at this stage.

There's nothing like fresh eyes to see what can be improved about our project and the experience for new contributors.
Any suggestions for improvements in comments, structure, documentation... are immensely appreciated.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
