### ISSUE TITLE
Str.fromFloat accepts `Float *` but the implementation assumes `F64`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1553]
It says it takes a `Float *`, but in practice the implementation assumes `F64`.

This means passing a `F32` to `Str.fromFloat` would not go well!

(Separately, it should be renamed to `Str.fromFrac` now that `Dec` exists.)

**Comment by Ivo-Balbaert** [comment]
Neither Str.fromFloat nor Str.fromFrac do exist at this moment. Does this mean the issue is deprecated and can be closed?

**Comment by Anton-4** [comment]
:+1: yes, we now have `Num.toStr`
