### ISSUE TITLE
"missing import" error reported as something else for packages

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1612]
If I do `requires {}{ main : Task.Task {} * }` and I forget to add the `Task` module to `imports`, I get this error:

```
The Task module does not expose a Task value
```

...rather than "the Task module is not imported" - which is the real problem in this case!

**Comment by Ivo-Balbaert** [comment]
The following program now seems to give a correct error message:

```coffee
app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br" }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf


main =
    foo = {a: 1, b: 2}
    foo.a + foo.b |>  Num.toStr |>
       Task.putLine
```

namely:
── MODULE NOT IMPORTED ───────────────────────────────────────────── test2.roc ─

The `Task` module is not imported:

14│         Task.putLine
            ^^^^^^^^^^^^

Did you mean to import it?

────────────────────────────────────────────────────────────────────
1 error and 1 warning found in 33 ms.

It seems this issue can be closed now? @Anton-4?
