### ISSUE TITLE
Editor: unstuck the user after he enters 0

### ISSUE THREAD

**Issue by popara** [roc-lang/roc#1639]
When writing a number, we are not allowing leading zeros, so if roc programmer types:

`0`

`1` 

it will get stuck on `0`. 

For nicer experience I suggest we eliminate zero and allow user to continue typing number. 

PS: I this is first issue that I want to get into the code with, so when sound thing comes in, I will feel more comfortable around the code base.

**Comment by JanCVanB** [comment]
@popara @Anton-4 @rtfeldman How do each of you feel about this a year later? Instant zero elimination or deferred?

**Comment by rtfeldman** [comment]
Seems worth trying to me! 👍

**Comment by Anton-4** [comment]
This is kind of a low priority issue, it wouldn't make sense implementing this before the big editor re-write. Let's come back to this later.

**Comment by JanCVanB** [comment]
@rtfeldman @Anton-4 Sounds good! I'll leave this issue as-is and close the stale implementation PR.

**Comment by popara** [comment]
Yes, 100% we should close this, and comeback to editor when I have some time to breathe 😅
