### ISSUE TITLE
Extra parens in docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1643]
Currently `List.reverse` is rendered as:

```elm
reverse : (List elem) -> (List elem)
```

It would look nicer without the parens!

```elm
reverse : List elem -> List elem
```

**Comment by yukiomoto** [comment]
@rtfeldman 
I don't see this problem in the docs anymore. So it might have been fixed maybe ?

**Comment by Anton-4** [comment]
Yes, looks like it's been fixed, thanks for mentioning it @yukiomoto!
