### ISSUE TITLE
Have sensible font-size options

### ISSUE THREAD

**Issue by popara** [roc-lang/roc#1772]
Make sure that only couple of options for font-size in the editor are allowed. 

My take at what the sizes should convey:

- minimal:  should be the size were letters are easily readable but anything less would be hard to read for 95% of users. 
- small 
- medium 
- big 
- maximum: optimized for presentations, code showcases etc, on laptop it should hold couple of lines of this big font.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
