### ISSUE TITLE
Panic with misnamed requires

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#1782]
If you rename the functions exposed to the host, for example main, and you forget to change the requires field, you just get a panic instead of a nice error message.

Apparently the panci is related to Tasks somehow, but there error message is still not great for other types.  Anyway, on [this branch](https://github.com/rtfeldman/roc/tree/issue-requires-mismatch), run `cargo examples/cli/Echo.roc` has this error:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/mono/src/ir.rs:8089:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`cargo check examples/cli/Echo.roc` does a better job, but prints out a confusing message. We likely want to point it to the requires line and point out that we couldn't find it. This is also the message when running on hello world were it doesn't return task. Here is the message:
```
── UNRECOGNIZED NAME ───────────────────────────────────────────────────────────

I cannot find a `setup` value

14│              getLine : Effect Str
                    ^^^^^

Did you mean one of these?

    Set
    Nat
    Dec
    Str

────────────────────────────────────────────────────────────────────────────────
```

**Comment by Ivo-Balbaert** [comment]
As far as I can tell at this moment, this provokes no panic anymore.
I encounter error messages such as:
```
── UNRECOGNIZED NAME ─ ...DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk/main.roc ─

Nothing is named `main1` in this scope.

28│  mainForHost = main1
                   ^^^^^

Did you mean one of these?

    main
    Nat
    Dict
    Int


── UNRECOGNIZED NAME ─ ...DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk/main.roc ─

The #UserApp module does not expose anything by the name 1.


── MISSING DEFINITION ────────────────────────────────────────────── test4.roc ─

main is listed as exposed, but it isn't defined in this module.

You can fix this by adding a definition for main, or by removing it
from exposes.

────────────────────────────────────────────────────────────────────
1 error and 1 warning found in 30 ms.
```

so perhaps this issue is solved - @Anton?
