### ISSUE TITLE
Add example project to nightly release tar

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#1930]
The editor creates an example project if no directory is passed.
When inside the git repository, `examples/hello-world` is copied to a new folder called `new-roc-project`.
When using the roc binary, this example is not available. For this reason it would be nice to have an example included.

Having an example app is also useful for those getting started with roc.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
