### ISSUE TITLE
Remove `--valgrind` CLI flag once Valgrind workaround no longer needed

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1997]
https://github.com/rtfeldman/roc/pull/1986 introduced the `--valgrind` flag as a workaround for https://github.com/rtfeldman/roc/issues/1963 - once we no longer need that workaround, we should remove the flag so as not to run afoul of [Hyrum's Law](https://www.hyrumslaw.com/). It's not intended to be a long-term feature! 😄

**Comment by skyqrose** [comment]
Removed in https://github.com/roc-lang/roc/pull/3754
