### ISSUE TITLE
Fix test `tld_with_comment_after` in `docs/tests/insert_syntax_highlighting.rs`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2134]
The likely problem here is that the parser goes through `CanonicalizeAndConstrain` in `file.rs` which might delete comments.
The `Parse` task should likely be set as the `goal_phase` in earlier functions but this requires some work.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
