### ISSUE TITLE
Comment between type annotation and declaration results in compiler seeing 2 declarations

### ISSUE THREAD

**Issue by erwinkn** [roc-lang/roc#2158]
Any comment added between a type annotation and the associated declaration results in the compiler thinking the two are separate declarations.

**Reproduction**
In any of the "Hello world" examples, write:
```coffee
main: Str
# comment
main = "I'm still the same declaration!"
```

**Expected behavior**
The program runs fine and prints `I'm still the same declaration!`

**Actual behavior**
I get the following error:
```
emitted runtime error NoImplementationNamed { def_symbol: `8.IdentId(0)` }
🔨 Rebuilding host... 
── DUPLICATE NAME ──────────────────────────────────────────────────────────────

The main name is first defined here:

6│  main: Str
    ^^^^

But then it's defined a second time here:

8│  main = "Hello!" 
    ^^^^

Since these variables have the same name, it's easy to use the wrong
one on accident. Give one of them a new name.

────────────────────────────────────────────────────────────────────────────────

Done!
Roc hit a panic: NoImplementationNamed { def_symbol: `8.IdentId(0)` }
```

**Comment by robbym** [comment]
I get the same runtime error if the definition is omitted altogether. I was surprised when it compiled. Usually that would give me a link-time error in C for example.

**Comment by isaacvando** [comment]
The parser now accepts this 
```roc
module []

foo : Str
# foo
foo = "hello"
```
