### ISSUE TITLE
website to convert Roc into syntax-highlighted Roc

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2170]
For easy sharing/discussion of Roc code.
A lot of things can be re-used from the docs folder.

**Comment by lukewilliamboswell** [comment]
One way to do this is to copy-paste the roc into GH code editor, or a gist. Then "view source" and copy that out. 

It will be using the GH css, but it works well.

**Comment by Anton-4** [comment]
Yeah actually, github gists can do everything we need in this case.
