### ISSUE TITLE
Make sure compiler/builtin/docs contains all implemented builtins.

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2199]
Some implemented builtins are not listed there, this can make things difficult for roc programmers.
- [ ] Write a CI test (see Earthfile) to check if all implemented builtins are listed in compiler/builtin/docs.
- [ ] Add implemented builtins that are not yet in compiler/builtin/docs.
- [ ] Add a docs comment (## UNIMPLEMENTED) in compiler/builtin/docs for those that are not yet implemented.
- [ ] Write a CI test that checks if every unimplemented builtin mentioned in compiler/builtin/docs has a `## UNIMPLEMENTED` comment above it.

**Comment by ayazhafiz** [comment]
Since all the docs now live in the roc sources for the builtins, is this issue still relevant?
