### ISSUE TITLE
`List.get [1, 2, 3] -1 == Ok -9223372036854775808`

### ISSUE THREAD

**Issue by kili-ilo** [roc-lang/roc#2203]
This seems like a bug. Is it?

```
[nix-shell:~/code/advent-of-code-2021]$ ./roc/target/release/roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :exit/:q.

» List.get [1, 2, 3] -1

Ok -9223372036854775808 : Result (Num *) [ OutOfBounds ]*

» 
```

**Comment by Ivo-Balbaert** [comment]
Perhaps not so important: List.get when given a negative index gives a correct TYPE MISMATCH error when compiling a program, in the repl it immediately panics:

names = ["John", "Andy", "Kumar", "Eva"]
List.get names -2
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Erroneous', crates/compiler/mono/src/ir.rs:8803:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Anton-4** [comment]
Thanks for reporting this @Ivo-Balbaert :)
Can you make a new issue for this and link this one as possibly related?
