### ISSUE TITLE
Support reading opaque types from a roc file.

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2221]
- [ ] In `code_markup/src/markup/top_level_def.rs` add the function `opaque_tld_mark_node`, it's implementation will be similar to `tld_mark_node` but with `val_name_mn` renamed to `type_name_mn` and a `HighlightStyle::Type`. As well as a different `MarkNode` for the special equals `:=`.

I'd recommend holding off on the issues below until opaque type defs have landed in the language itself (#2214).
- [ ] A variant `OpaqueType(OpaqueTypeDef)` should be added to The `Def` enum in `ast/src/lang/core/def/def.rs`.
- [ ] `Def2` should get a `OpaqueDef`
- [ ] add conversion from `Def` to `Def2` to `def_to_def2.rs`
- [ ] use the new `opaque_tld_mark_node` function in `def2_to_markup` (`code_markup/src/markup/convert/from_def2.rs`).
- [ ] add a test for an opaque type definition in `insert_syntax_highlighting.rs` (`docs/tests`).

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
