### ISSUE TITLE
Duplicate `Int` definition in builtins docs

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#2224]
[This](https://github.com/rtfeldman/roc/blob/6056d29df075908afaf9add776f7301ce012a330/compiler/builtins/docs/Num.roc#L308) and [this](https://github.com/rtfeldman/roc/blob/6056d29df075908afaf9add776f7301ce012a330/compiler/builtins/docs/Num.roc#L408) seem like duplicates, but they have different docstrings. How should we merge these?

**Comment by ayazhafiz** [comment]
Now that `Num.roc` is checked by the compiler to produce builtins, those duplicates don't exist! Closing as resolved.
