### ISSUE TITLE
Improper indentation after if block causes panic

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#2255]
Regarding (6), the issue is that lines 18-24 are indented one more character than expected. If you delete the first space on each of those rows, the program should compile.

Here is an minimal example:

```
app "hello-world"
    packages { pf: "platform" }
    imports []
    provides [ main ] to pf

a =
  if True then Red else Yellow

 main =
   ""
```

```
thread 'main' panicked at 'attempt to subtract with overflow', reporting/src/report.rs:505:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

using the "hello-world" platform.

_Originally posted by @ayazhafiz in https://github.com/rtfeldman/roc/issues/2227#issuecomment-998989488_

**Comment by Ivo-Balbaert** [comment]
The above minimal example now runs for the equivalent platform: packages { pf: "c-platform/main.roc" }

ivo@megaverse:~/roc_code$ roc test2.roc
🔨 Rebuilding platform...

── UNUSED DEFINITION ─────────────────────────────────────────────── test2.roc ─

a is not used anywhere in your code.

6│  a =
    ^

If you didn't intend on using a then remove it so future readers of
your code don't wonder why it is there.

────────────────────────────────────────────────────────────────────────────────

0 errors and 1 warning found in 281 ms.

Running program…

So I think this issue can be closed now.

**Comment by Anton-4** [comment]
Thanks @Ivo-Balbaert!
