### ISSUE TITLE
Why are tabs illegal?

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#2288]
I'm personally ambivalent on tabs vs. spaces for indentation, but I'm surprised that Roc takes such a strong stance against tabs. It seems that tabs are illegal anywhere except string literals and application names:
- When used for indentation, the type checking step of the compiler throws an unformatted `index out of bounds: the len is 11 but the index is 11` panic.
- When used anywhere else (such as between function arguments), the type checking step of the compiler throws a well-formatted `Tab characters are not allowed.` error.

Is this an intentional choice (to enforce consistency between developers? to enable the editor to use the tab key for features?) or is tab support on the roadmap?

**Comment by skyqrose** [comment]
It's 3 years later, and the tabs vs spaces debate may never be resolved (here's a recent thread on [zulip](https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/Whitespace.2E)), but we don't need to keep this old issue open. Closing.
