### ISSUE TITLE
Unreachable code reached in reporting

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2364]
ff19056cff3ac2a2edbff9e8aa15754e0dc2d035 reproduces this if you check it out and run `cargo run -- check examples/cli/Files.roc`

```
$ cargo run -- check examples/cli/Files.roc 
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/roc check examples/cli/Files.roc`
Mismatch in compiler/unify/src/unify.rs Line 1184 Column 13
Trying to unify two flat types that are incompatible: Apply(`Str.Str`, []) ~ EmptyRecord

thread 'main' panicked at 'internal error: entered unreachable code: closure tags are internal only', reporting/src/report.rs:278:42
```

(Also `cargo run` without the `--check` also reproduces it; the `unreachable!` happens in reporting.)

Here's the diff:

```diff
             Ok v ->
                 {} <- await (Stdout.line "Thank you for flying Roc!")
-                Task.succeed v
+                Task.succeed ""
```

The issue is that in after this change, we're doing `Task.succeed` with a `Str`, whereas before it was a `{}` (because `v` has the type `{}` here). `roc check` should report this as a type mismatch between `Str` and `{}`.

**Comment by ayazhafiz** [comment]
This is no longer an issue on `main`, because closures are no longer tag names - they are now a totally separate type from tag unions.
