### ISSUE TITLE
draft editor plugin API in roc

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2368]
- How is AST data accessible to plugins?
- How does plugin UI work (UI components, vector level, pixel-level)?
- Given a selected expression, how do we show all plugins available that can visualize this expression or have an interactive widget to alter the expression (color picker). What does this API look like?
- use type driven UX? https://pchiusano.github.io/2013-09-10/type-systems-and-ux-example.html

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
