### ISSUE TITLE
in-depth comparison of structural editing vs tree-sitter approach

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2381]
A major disadvantage of structural editing is that you may not know how to edit something that would be very easy to achieve in a regular editor. This will likely hurt the first impression of the editor.

A tree-sitter can also give us the AST but not for every state of the text buffer.

Further pros and cons should be investigated and compared.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
