### ISSUE TITLE
Start on roadmap to prepare editor to connect with API of some of the most popular accessibility software

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2532]
These include the following:
- [ ] Jaws
- [ ] ZoomText
- [ ] NV Access (open source)
- [ ] Native Screen Readers (Windows, Linux. MacOS, etc.)

### Other Options
Other options can include embedding something similar to Java's Accessibility Bridge, or perhaps only talking to native API's which will in turn proxy to the screen reader.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
