### ISSUE TITLE
Possible Performance Enhancements for TEA Architected Elements

### ISSUE THREAD

**Issue by jquesada2016** [roc-lang/roc#2539]
I recently came up with a technique out of a desire for wanting to create an elm-style app without the VDOM. It is a twist on the aforementioned architecture.

### Before we Begin

I would like to clarify ahead of time, a couple concepts that we will need in order to understand this pattern.

We will be mixing in Functional Reactive Programming (FRP) with TEA. (Frappe tea? We should ask marketing about that one...). FRP allows us to efficiently create subscribers, or **observers** to **source** data. When the source data changes, the observer can react to that change. In `rust`, this can be implemented _very_ efficiently with `async Streams`.

### An Example

Let's walk through a simple counter example by creating a counter that increments/decrements when the user clicks the respective button.

Let's begin by creating our model.

```rust
struct Model {
    count: Source<isize>,
}
```

Here, `Source` is a simple proxy to an `Rc` container. A source can set the inner value, but not subscribe to it's changes.

Let's go ahead and implement the update logic.

```rust
enum Msg {
    Increment,
    Decrement,
}


// Note that `update` does not return anything
fn update(model: &Model, msg: Msg) {
    match msg {
        Msg::Increment => model.*counter.set_with(|counter: &mut isize| *counter += 1),
        Msg::Decrement => model.*counter.set_with(|counter: &mut isize| *counter -= 1),
    }
}
```

We can begin to see how these parts correspond to TEA. We take an immutable reference to the model, which consists of a model full of `Source`. We can go ahead and set the value upon receiving a message. An important note and distinction is that `update` does not need to return anything. It could, but it doesn't need to for updating the model. This is due to the async nature of `Observer`. As soon as you set the value, depending on the async runtime, the UI could react immediately (for blocking clients), or after `update` completes (for non-blocking clients).

Let's complete the implementation by creating a view function.

```rust
fn view(model: &ModelView) -> View<Model, Msg> {
    vec![
        h1().dyn_text(model.counter.clone(), |c: usize| c.to_string()),
        button().on("click", |_| Msg::Increment).text("+"),
        button().on("click", |_| Msg::Decrement).text("-"),
    ]
}
```

Now, where did `ModelView` come from? Well, we need to create it. It's purpose is just to mirror the structure of the original Model, replacing `Source` with `Observer` which we can use to react to changes. Let's go ahead and create it.

```rust
struct ModelView {
    counter: Observer<isize>
}
```

So what's going on with that `dyn_text` function? In this case, all it is meant to do is receive any item which implements `Stream`. Whenever the stream yields a value, the `|c: usize| c.to_string()` is called, which is what will be rendered to the DOM.

And that's it! That's all there's to it! The synchronization between `Model` and `ModelView` can be made with a macro, which can make this automatic. I meant this code to be more pseudocode than actual code, but I do have fully working examples for another framework I'm developing. These concepts can be applied outside the confides of front-ends.

### Beyond the Front-End

For the Roc language, this method can be used for certain situations where having a Model-View-Update style makes sense, perform much faster, with many of the same benefits of the original architecture.

Let's take fore example the editor, which we would like to load plugins when the imports change.

```rust
struct ImportsModel {
    imports: Source<Vec<ImportStmt>>,
    plugins: Source<Vec<Plugin>>,
}

enum Msg {
    ChangedImport(ImportChangeKind),
    Load(Plugin),
    Unload(Plugin),
}

enum ImportChangeKind {
    Added(ImportStmt),
    Removed(ImportStmt),
}

struct Plugin {/* .. */}

struct ImportStmt {/* .. */}

fn update_imports(model: &ImportsModel, msg: Msg) {
    match msg {
        Msg::ChangedImport(kind) => match kind {
            ImportChangeKind::Added(import) => {
                let plugin = Plugin {/* extract plugin from import */};

                model
                    .imports
                    .set_with(|imports: &mut Vec<ImportStmt>| imports.push(import));

                update_imports(model, Msg::Load(plugin));
            }
            ImportChangeKind::Removed(import) => {
                let plugin = Plugin {/* extract plugin from import */};

                model.imports.set_with(|imports: &mut Vec<ImportStmt>| {
                    // find and remove the import statement
                });

                update_imports(model, Msg::Unload(plugin));
            }
        },
        Msg::Load(plugin) => { /* load plugin */ }
        Msg::Unload(plugin) => { /* remove plugin */ }
    }
}

fn main_loop() {
    let model = ImportsModel {
        imports: Source::new(vec![]),
        plugins: Source::new(vec![]),
    };

    // Do other main loop stuff

    // pass the imports, or plugins to anything else that needs it

    // Observers can be cheaply cloned, sources cannot.
    let imports_observer = model.imports.observer();
    let plugins = model.plugins.observer();

    // Do more stuff
}

```

As an `Observer` is just a weak reference to the `Source`, they are extremely light weight, can be checked that the source is still alive, and can provide the owner with an immutable reference, avoiding the need for expensive clones. They can therefore be listened to in the following manner, or used with stream combinators.

```rust
/* .. */
plugin_observers.for_each(|plugins: &Vec<Plugin>| {
    // do stuff with the plugin
});
/* .. */
```

These features provide a performance characteristic of O(1) for small, multithreaded workloads, and O(n) for large or single threaded situations. Here, n is the number of observers. This brings up another important note; sources and observers can easily be made to work across threads.

#### Important Node:

In the above examples, I've been using `Vec<_>`, which is not the most efficient data structure if you want to get notified of only the items that have been changed, I do have a solution for this, although it's outside the scope of demonstrating the overall technique.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
