### ISSUE TITLE
Updating identifiers in the editor goes wrong for identical identifiers

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2548]
The `update_key` function in `compiler/module/src/symbol.rs` updates identifiers based on their `str` value.
If you already have a function `f` and you want to write the function `foo` the first function name `f` will be updated to be `foo` instead of the second `f` you typed while wanting to type `foo`.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
