### ISSUE TITLE
Specialization bugs in recursive union types

### ISSUE THREAD

**Issue by brian-carroll** [roc-lang/roc#2551]
In a couple of places, we are not distinguishing correctly between different instances of `RecursivePointer`.

This [test](https://github.com/rtfeldman/roc/blob/5fec87dc2ac43f324202cea4fb59f5a8d081ce0f/compiler/test_gen/src/gen_compare.rs#L503) fails for gen_llvm and gen_wasm for two different reasons. 

```elm
Rose a : [ Rose a (List (Rose a)) ]

a1 : Rose I64
a1 = Rose 999 []
a2 : Rose I64
a2 = Rose 0 [a1]

b1 : Rose I64
b1 = Rose 999 []
b2 : Rose I64
b2 = Rose 0 [b1]

ab = a2 == b2

c1 : Rose Str
c1 = Rose "hello" []
c2 : Rose Str
c2 = Rose "" [c1]

d1 : Rose Str
d1 = Rose "hello" []
d2 : Rose Str
d2 = Rose "" [d1]

cd = c2 == d2

ab && cd
```

## LLVM backend: equality procedure generation

The test fails with the LLVM backend because `compiler/gen_llvm/src/llvm/compare.rs` doesn't create distinct equality procedures for different `RecursivePointer`s. 
When we use `gen_wasm`, the equality procedures are generated somewhere else that doesn't have the same issue (`compiler/mono/src/code_gen_help/equality.rs`)

## Dev backends: equality procedure *calls*

For the dev backends, the IR for the equality procedures is generated in `compiler/mono/src/code_gen_help/equality.rs`.
It correctly generates IR for two separate procedures, but the IR for the _calls_ to those procedures is not specific enough. In both cases we get the following:

```rs
    CallType::ByName {
        ret_layout: Builtin(Bool),
        arg_layouts: [Builtin(List(RecursivePointer)), Builtin(List(RecursivePointer))],
        ..
    },
```

But the `ProcLayout` uses an expanded version of the `RecursivePointer`, so we have problems matching the call to the right procedure
```rs
ProcLayout {
    arguments: [
        Builtin(List(Union(NonNullableUnwrapped([
            Builtin(Int(I64)),
            Builtin(List(RecursivePointer)),
        ])))),
        Builtin(List(Union(NonNullableUnwrapped([
            Builtin(Int(I64)),
            Builtin(List(RecursivePointer)),
        ])))),
    ],
    result: Builtin(Bool),
};
```

**Comment by ayazhafiz** [comment]
This now compiles. A test should be added.
