### ISSUE TITLE
Monomorphization reaching `unreachable!` branch

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2568]
In 181fcb97f702b36e839256daae3104ee2a89c135 running `cargo run examples/gui/Hello.roc` triggers an `unreachable!`

```
'internal error: entered unreachable code: so far', compiler/mono/src/ir.rs:2410:21
```

Of note, this only started happening after introducing a large recursive type that's not named (it's defined recursively using `as`, which in this case is important).

**Comment by ayazhafiz** [comment]
This has been resolved partly with #3549
