### ISSUE TITLE
Formatter should automatically enforce newlines at end of files

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2580]
POSIX compliance requires that all text files [end in a newline](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline). Since `.roc` files are text files, they should end in newlines!

Currently the formatter expects a `.roc` file with these contents not to end in a newline:

```elm
interface Foo exposes [] imports []
```

Instead, it should format the file (and all `.roc` files) to end in exactly one newline.

**Comment by Ivo-Balbaert** [comment]
This issue seems to have been closed, but made open again by adding/removing the hactoberfest label. Probably it can be closed definitively @Anton-4 ?

**Comment by Anton-4** [comment]
Thanks @Ivo-Balbaert, I've confirmed that this is fixed.
