### ISSUE TITLE
Doc comments with code snippets don't re-format the same way

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2585]
To reproduce, edit `examples/hello-world/Hello.roc` to include this doc comment:

```
app "hello-world"
    packages { pf: "platform" }
    imports []
    provides [ main ] to pf

## Greets the user
##
##     Blah
main = "Hello, World!\n"
```

Then run `cargo run format examples/hello-world/Hello.roc`

**Expected:** It formats the file successfully

**Actual:** It panics with `Formatting bug; formatting is not stable. Reformatting the formatted file changed it again.`

Specifically what happens is that re-formatting the already-formatted code changes the indentation of `Blah`, which is interpreted (correctly) as a code snippet.

What should happen instead is that the first time this gets formatted, the indentation for `Blah` is set, and then running the formatter on it a second time should not change anything. (Running the formatter a second time on code that has already been formatted should never change anything, which is why we detect this case and explicitly panic if it happens!)

**Comment by cjduncana** [comment]
The code's latest version doesn't have this problem. I added that comment to `examples/helloWorld.roc` and ran `cargo run format examples/helloWorld.roc` twice. The first time, it removed the file's extra line at the end, and the second time, it exited successfully.

**Comment by Ivo-Balbaert** [comment]
Running roc format now confirms the findings of @cjduncana. Is this enough to close this issue, @Anton-4?
