### ISSUE TITLE
Anonymous record update syntax

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2659]
Similar to how you can write `.foo` today (which desugars to `\record -> record.foo`), writing `&foo` should desugar to `\record, val -> { record & foo: val }`

**Comment by GabrielDertoni** [comment]
I would like to start working on this, can it be assigned to me? But I might need some guidance at some point.

**Comment by ayazhafiz** [comment]
Sure! Assigned to @GabrielDertoni . Feel free to message on the contributing channel on the Roc Zulip (https://roc.zulipchat.com/#narrow/stream/316715-contributing) if you'd like to chat through anything.

**Comment by smores56** [comment]
Oh, what timing. I already started working on this yesterday after asking in the Zulip channel ([thread here](https://roc.zulipchat.com/#narrow/stream/231634-beginners)), but didn't assign it to myself. @GabrielDertoni how committed are you to this issue? I've already started implementation, more or less halfway done.

**Comment by smores56** [comment]
We've discussed on Zulip about collaboration, which will involve us both pushing code to different branches and comparing notes.

**Comment by lishaduck** [comment]
Closed in #7002?

**Comment by lukewilliamboswell** [comment]
Thank you @lishaduck
