### ISSUE TITLE
False interpretter lots of specialization subs

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#2671]
Building the false interpreter creates hundreds of thousands of subs in total with the largest module creating approximately 75,000 subs by itself. If in [run_tasks](https://github.com/rtfeldman/roc/blob/37ab632ccd78b582952de21d55c471935e2a31ee/compiler/load/src/file.rs#L3719), you print out the [MakeSpecializations.specializations_we_must_make](https://github.com/rtfeldman/roc/blob/37ab632ccd78b582952de21d55c471935e2a31ee/compiler/load/src/file.rs#L3808), you will see the gigantic list of subs. Generating this large of a number of subs seems like it could definitely be a bug, or a least something to optimize.

**Comment by ayazhafiz** [comment]
I'm going to close this for now since we've done a lot of perf work since March.
