### ISSUE TITLE
Add tests for everything in `compiler/parse/tests/snapshots/pass/` to `highlight/tests/peg_grammar.rs`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#2689]
See also `/compiler/parse/tests/test_parse.rs` to see how those tests are being run on the currently used compiler parser.

**Comment by skyqrose** [comment]
`parse/snapshots/` no longer exists: https://github.com/roc-lang/roc/tree/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/compiler/parse/tests
`highlight/tests/` no longer exists: https://github.com/roc-lang/roc/tree/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/highlight
Nothing to do.
