### ISSUE TITLE
Re-enable Valgrind on some tests after Zig 0.9

### ISSUE THREAD

**Issue by brian-carroll** [roc-lang/roc#2794]
PR #2538 failed Valgrind on some tests, for reasons that will go away once we migrate to Zig 0.9.
Unfortunately Zig 0.9 is currently blocked on that same PR!
To break the dependency cycle, Valgrind has been disabled on those tests for now. 
This issue is to re-enable it later.

**Comment by skyqrose** [comment]
The configuration for valgrind has gotten a bit more complex in the last 2 years, but I'm pretty sure this is resolved.
Test 1: https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/cli/tests/cli_tests.rs#L874
Test 2: https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/cli/tests/cli_tests.rs#L212 (commented out)
