### ISSUE TITLE
CLI produces 0 exit codes even if there are warnings

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2808]
It should produce a nonzero exit code if there are any warnings!

**Comment by HajagosNorbert** [comment]
Wanted to do this, but the roc executable already produces exit code 1 when hitting an error (during compilation of a roc program) and exits with 0 on warnings, as it should.
If this shouldn't be closed yet, could you specify the issue @rtfeldman?

**Comment by rtfeldman** [comment]
Ah, I think it should still exit 1 if there are warnings!

**Comment by skyqrose** [comment]
It exits with a nonzero code when there are warnings now.
