### ISSUE TITLE
Compiler crash if func annotation has different # of parameters than func

### ISSUE THREAD

**Issue by jared-cone** [roc-lang/roc#2862]
On `d23d5f249` modifying `echo.roc` from the examples:

```
app "echo"
    packages { pf: "cli-platform" }
    imports [ pf.Task, pf.Stdout ]
    provides [ main ] to pf
    
test : I32, I32 -> I32
test = \i -> 0 # <--- forgot 2nd param

main =
    str = Num.toStr (test 0 0)
    Stdout.line str
```

```
thread '<unnamed>' panicked at 'more arguments (according to the layout) than argument symbols for `#UserApp.test`', compiler/mono/src/ir.rs:2810:25
```

Similar if too many parameters:

```
app "echo"
    packages { pf: "cli-platform" }
    imports [ pf.Task, pf.Stdout ]
    provides [ main ] to pf
    
test : I32 -> I32
test = \i, j -> 0

main =
    str = Num.toStr (test 0)
    Stdout.line str
```

```
thread '<unnamed>' panicked at 'more argument symbols than arguments (according to the layout) for `#UserApp.test`', compiler/mono/src/ir.rs:2816:35
```

**Comment by Ivo-Balbaert** [comment]
The first code snippet now gives the proper error message:

── TYPE MISMATCH ──────────────────────────────────────────────────── test.roc ─

Something is off with the body of the test definition:

6│  test : I32, I32 -> I32
7│  test = \i -> 0 # <--- forgot 2nd param
           ^^^^^^^

The body is an anonymous function of type:

    (I32 -> I32)

But the type annotation on test says it should be:

    (I32, I32 -> I32)

Tip: It looks like it takes too few arguments. I was expecting 1 more.

────────────────────────────────────────────────────────────────────

The 2nd code snippet also gives a good error message:
── TYPE MISMATCH ──────────────────────────────────────────────────── test.roc ─

Something is off with the body of the test definition:

6│  test : I32 -> I32
7│  test = \i, j -> 0
           ^^^^^^^^^^

The body is an anonymous function of type:

    (I32, * -> I32)

But the type annotation on test says it should be:

    (I32 -> I32)

Tip: It looks like it takes too many arguments. I'm seeing 1 extra.

So I think this issue can be closed. @Anton-4 ?
