### ISSUE TITLE
Canonicalization panics when importing nonexistant platform alias

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2891]
If my platform has a module called `Foo` which does _not_ expose a type alias called `Blah`, and I try to import `Foo.{ Blah }`, canonicalization panics:

```
'apparently, `pf.Foo.Blah` is not actually a type alias', compiler/can/src/module.rs:222:13
```

**Comment by Ivo-Balbaert** [comment]
Tested this as follows:

app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br" }
    imports [
        pf.Stdout, pf.Stdout.Blah, pf.Task.{ Task },
    ]
    provides [main] to pf

main = ...

This now doesn't panic anymore, and gives a nice error message:

── FILE NOT FOUND ──────────────────────────────────────────────── UNKNOWN.roc ─

I am looking for this file, but it's not there:

    /home/ivo/.cache/roc/packages/github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk/Stdout/Blah.roc

Is the file supposed to be there? Maybe there is a typo in the file
name?

So probably this issue can be closed. @Anton-4 ?

**Comment by lukewilliamboswell** [comment]
Concur this is resolved. 

```
app "test"
     packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br"
    }
    imports [
        pf.Stdout.Blah,
    ]
    provides [main] to pf

main = Stdout.line "test"
```

```
% roc run Experiments/Test.roc
── FILE NOT FOUND ──────────────────────────────────────────────── UNKNOWN.roc ─

I am looking for this file, but it's not there:

    /Users/luke/.cache/roc/packages/github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk/Stdout/Blah.roc

Is the file supposed to be there? Maybe there is a typo in the file
name?%                         
```
