### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2908]
I noticed in `examples/breakout/`, [roctris](https://github.com/cjcone/roctris), and [roc-ecs](https://github.com/bhansconnect/roc-ecs)'s fireworks demo, the longer I run the program the more memory usage continually increases. For all of those, I would expect memory usage to be relatively stable shortly after startup.

I'm not sure if this is because of the platforms or because of Roc code gen, but noting it here for further investigation!

**Comment by ostev** [comment]
I, too, have noticed memory issues with long running Roc programs while working on the [`roc-retro`](https://github.com/ostev/roc-retro) platform. It seems that either `Effect.loop` is leaking the `state` of each step or `List.repeat` is leaking memory. I've been working on isolating this in a seperate repo and will post more information once I've found something a little more concrete.

**Comment by skyqrose** [comment]
Presumably fixed by https://github.com/roc-lang/roc/pull/4830 .
