### ISSUE TITLE
Allow record field names to be integers

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2934]
This is part of the [SIMD proposal](https://docs.google.com/document/d/1R3ESkzSyOAA8DnasxF1WHDeoe9LgFE1uvmIr8s-aNro/edit).

Record field names that are (decimal) integer literals should be allowed, e.g. `{ 0: foo, 1: bar }`.

Although `{ x, y }` desugars to `{ x: x, y: y }`, the record `{ 0, 1 }` should not desugar to ` { 0: 0, 1: 1 }`. That's because there is basically no reason to ever write this, so it's almost certain to be an error - and getting a compiler error on the standalone `0` if you mistakenly write `{ x: 0, y, 0 }` instead of `{ x: 0, y: 0 }` is likely to be more helpful than the type mismatch(es) you'd get if the desugaring silently succeeded.

This also means that record accessors should support it as well, e.g. `foo.0` and `(foo bar baz).1` should both be treated as valid and normal record accesses.

Similarly, standalone `.0` and `.1`  values should be record accessor functions, the same way that `.x` and `.y` are. (This is distinct from `0.0` and `0.1`, which are number literals.)

> Of note, since code generation sorts these alphabetically, this might result in some surprising orderings for very long tuples - e.g. the string `"12"` sorts earlier than the string `"9"` because the 1 gets compared to the 9 and then the 2 never gets compared to anything. However, this should not cause problems in practice; records (including tuples) get reordered based on alignment anyway, so there's never any guarantee that the ordering you specify is exactly what you'll get in code gen - just that it'll be consistent. So no changes to code gen should be necessary for this.

**Comment by ayazhafiz** [comment]
@rtfeldman this isn't relevant anymore with tuples, is it?
