### ISSUE TITLE
Desugar tuples to records

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2935]
This is part of the [SIMD proposal](https://docs.google.com/document/d/1R3ESkzSyOAA8DnasxF1WHDeoe9LgFE1uvmIr8s-aNro/edit), and comes after https://github.com/rtfeldman/roc/issues/2932 and https://github.com/rtfeldman/roc/issues/2934

Tuples should desugar to numbered record fields; e.g. `(a, b)` should desugar to `{ 0: a, 1: b }`.

This should presumably be done at the type-checking stage so that we can record that something originated as a tuple, allowing us to pretty-print errors using tuple syntax instead of record syntax even after the desugaring has happened.

**Comment by lukewilliamboswell** [comment]
Closing as I think this is completed.
