### ISSUE TITLE
Generate builtin docs from compiler/builtins/roc instead of compiler/builtins/docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2937]
- [ ] Generate builtin docs from `compiler/builtins/roc` instead of `compiler/builtins/docs`
- [ ] Migrate doc comments from `compiler/builtins/docs` to `compiler/builtins/roc`
- [ ] Delete `compiler/builtins/docs`

Once these are done, we'll have a single source of truth for builtins, and it will be possible to add both new builtin functionality as well as documentation for it in the same file!

**Comment by skyqrose** [comment]
`crates/copmiler/builtins/docs/` doesn't exist anymore. https://github.com/roc-lang/roc/tree/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/compiler/builtins
