### ISSUE TITLE
`when` branches always check indentation relative to `when`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2945]
Currently, neither of these parse successfully:

```coffee
thing = when tag is
    Foo -> "foo"
    Bar -> "bar"
```

```coffee
x = when tag is
        Foo -> "foo"
        Bar -> "bar"
```

However, both should!

The indentation check for branches should be relative to the first branch, not `when`. That requirement is unnecessarily restrictive; clearly, as long as the patterns have the same indentation, it's clear what is meant!

For similar reasons, this should work too:

```coffee
\x -> when x is
    Foo -> "foo"
    Bar -> "bar"
```

And of course, combinations of these:

```coffee
thing = foo bar \x -> when x is
    Foo -> "foo"
    Bar -> "bar"
```

**Comment by tannerntannern** [comment]
I use this style of `when` indentation all the time without issue.  We might be able to close this.  Would a regression test be warranted?

**Comment by Ivo-Balbaert** [comment]
I tested all of the above combinations and all were parsed fine.

So I think this issue can be closed. @Anton-4?

**Comment by lukewilliamboswell** [comment]
```
interface A
    exposes [ ]
    imports [ ]

tag = Foo

thing = when tag is
    Foo -> "foo"
    Bar -> "bar"

x = when tag is
        Foo -> "foo"
        Bar -> "bar"

expect thing == "foo"
expect x == "foo"
```

```
% roc test Experiments/A.roc

0 failed and 2 passed in 608 ms.

```
