### ISSUE TITLE
Unnecessary parentheses in generated docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2992]
Currently, in type signatures in generated docs, we have some unnecessary parentheses - [for example](https://www.roc-lang.org/builtins/Num#tan):

<img width="569" alt="Screen Shot 2022-05-02 at 10 29 17 PM" src="https://user-images.githubusercontent.com/1094080/166396374-ea410b66-ecf3-4f79-a46c-b2da17b20913.png">

This should be `tan : Float a -> Float a` without the parens

**Comment by sandprickle** [comment]
This appears to be fixed!
Here's what `roc docs` just generated for `Num.tan`:
<img width="304" alt="Screenshot 2023-05-04 at 3 24 43 PM" src="https://user-images.githubusercontent.com/891102/236218172-99eb88d8-649a-44e5-b777-9332b3fc2436.png">
