### ISSUE TITLE
Allow underscores in field names and variable names

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3026]
Currently, you can't have underscores in record field names or in variable names. This feature changes that!

So today, `{ _foo: 1, bar_: 2, my_thing: 3 }` are all disallowed, as would be `{ _foo, bar_, my_thing }` and `_foo =`, `bar_ =`, and `my_thing =` - but the idea would be to support all of these.

This will be valuable for automatic deserialization, e.g. from JSON that has underscores in object field names (which is common). I don't know of a compelling reason to support underscores in tag names, type names, or record names, so it should remain disallowed in those places.

Of note, a standalone underscore `_` is still a special case, and works the same way it currently does.

**Comment by Anton-4** [comment]
Note: we now [do not support underscores](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Allow.20underscores.20in.20field.20names.20and.20variable.20names.20.233026/near/410432492).
