### ISSUE TITLE
Compiler hangs when interface imports itself

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#3057]
For example, create `a.roc` with

```
interface A
    exposes [ ]
    imports [ A ]
```

The compiler will hang, presumably waiting for `A` to canonicalize (but of course, it's waiting for itself). This should be a pretty straightforward fix - after parsing the header, check if we import ourselves; if so, that's an error.

**Comment by rnice01** [comment]
@ayazhafiz https://github.com/roc-lang/roc/pull/4125 this fixes this problem as well right?

**Comment by Ivo-Balbaert** [comment]
The following interface now checks correctly:  file A.roc

interface A
    exposes [ ]
    imports [ A ]

```
$ roc check A.roc
── IMPORT CYCLE ──────────────────────────────────────────────────────── A.roc ─

I can't compile A because it depends on itself through the following
chain of module imports:

    ┌─────┐
    │     A
    │     ↓
    │     A
    └─────┘

Cyclic dependencies are not allowed in Roc! Can you restructure a
module in this import chain so that it doesn't have to depend on
itself?
```

So I think this issue can be closed, @Anton-4 ?
