### ISSUE TITLE
`roc run` should generate a binary with the app's name, not `roc_app_binary`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3130]
Right now when you do `roc Foo.roc` or `roc run Foo.roc` we generate a file named `roc_app_binary` and then run that.

Instead, we should generate a file with the name specified in the `app` module (e.g. for `app "blah"` we should generate an executable named `blah`), like we do with `roc build`.

**Comment by Ivo-Balbaert** [comment]
This was already solved a long time ago, but I did check it now again.

Can be closed.  @Anton-4 ?
