### ISSUE TITLE
Show preceding comments in `expect` failures

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3141]
It's common to want to describe a test, e.g. to explain what it's checking. Some test frameworks have an explicit "description" string for this, but the idea for `expect` is to do this by letting you optionally put a comment right above the `expect`, and then including that comment in the output when it fails - by expanding the source code lines to include any comment lines immediately preceding the `expect` itself (with no newlines before them).

For example, if I write this:

```
# this must always be true at this point because
# negative numbers cause explosions later
expect foo >= 0
```

...and there's a failure, the failure should look like this:

```
── EXPECTATION FAILED ─────────────────────────────────── /code/proj/Main.roc ─

This evaluated to False:

5│      # this must always be true at this point because
6│      # negative numbers cause explosions later
7│      expect foo >= 0
               ^^^^^^^^

The named values involved were:

    foo : I64
    foo = -42
```

**Comment by HajagosNorbert** [comment]
@rtfeldman I think this is done and can be marked as complete
