### ISSUE TITLE
Trying to execute an `interface` gives unhelpful error

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3240]
`cargo run examples/benchmarks/AStar.roc` currently results in:

> 'TODO turn fn_var into a RuntimeError UnresolvedTypeVar(201)', compiler/mono/src/ir.rs:1004:35

`AStar.roc` is an `interface` file, so instead we should give an error like "you can only run `app` modules, and this is an `interface` module."

**Comment by Ivo-Balbaert** [comment]
This is solved:

itself?ivo@megaverse:~/roc_code$ roc A.roc
── NO PLATFORM ─────────────────────────────────────────────────── UNKNOWN.roc ─

The input file is an `interface` module, but only `app` modules can be
run.

Tip: You can use `roc check` or `roc test` to verify an interface
module like this one.

@Anton-4 ?

**Comment by lukewilliamboswell** [comment]
Thank you @Ivo-Balbaert 

```
$ cargo run -- run crates/compiler/load_internal/tests/fixtures/build/app_with_deps/AStar.roc
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target/debug/roc run crates/compiler/load_internal/tests/fixtures/build/app_with_deps/AStar.roc`
── NO PLATFORM ─────────────────────────────────────────────────── UNKNOWN.roc ─

The input file is an `interface` module, but only `app` modules can be
run.

Tip: You can use `roc check` or `roc test` to verify an interface
```
