### ISSUE TITLE
Str.concatUtf8 : List U8, Str -> List U8

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3251]
```elm
Str.concatUtf8 : List U8, Str -> List U8
```

Concats the contents of the string directly into the given list of bytes.

See https://github.com/rtfeldman/roc/pull/3223/files#r899682722 for motivation

**Comment by shua** [comment]
Could I pick this up?

**Comment by lukewilliamboswell** [comment]
Sure, if you have any questions best to jump on Zulip. 😀

**Comment by shua** [comment]
This was implemented as `List.concatUtf8: List U8, Str -> Str`

**Comment by rtfeldman** [comment]
Awesome, thank you so much @shua! 😃
