### ISSUE TITLE
Some function signatures in the docs are missing necessary parentheses

### ISSUE THREAD

**Issue by Qqwy** [roc-lang/roc#3254]
For instance `List.walkUntil`:

```
walkUntil :     (List elem), state, state, elem -> [Continue state, Stop state] -> state
```

![image](https://user-images.githubusercontent.com/5345745/174313304-529d2c16-480a-4958-8611-719b768bcbd3.png)

This should of course be

```
walkUntil :     (List elem), state, (state, elem -> [Continue state, Stop state]) -> state
```

This might be related to #2992 but is sort of the opposite problem.

**Comment by sandprickle** [comment]
This appears to be fixed!
Documentation for `List.walkUntil` generated by `roc docs` built from main:
<img width="342" alt="Screenshot 2023-05-04 at 3 28 06 PM" src="https://user-images.githubusercontent.com/891102/236219170-b87d27d7-9376-4fc1-8781-9739600b128d.png">
