### ISSUE TITLE
Add curl command to nightly release page to download for macOS to prevent "...Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#3272]
We can't do this before going public because you need to log in to access the URL which is probably not easy to do with curl.

**Comment by skyqrose** [comment]
Done here: https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/www/content/install/macos_x86_64.md#L11

And there's also a note on the releases page under "common issues / macos"
