### ISSUE TITLE
New styles for generated docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3274]
@joeybright came up with some beautiful designs for the generated docs, which are responsive and include dark mode!

These can be implemented via changes to the [styles.css](https://github.com/rtfeldman/roc/blob/0c65aac757ab6973c703fb66473d69c07f7960ab/docs/src/static/styles.css) and [index.html](https://github.com/rtfeldman/roc/blob/0c65aac757ab6973c703fb66473d69c07f7960ab/docs/src/static/index.html) files used by the `roc docs` generator command.

![joey-bright-roc_designs](https://user-images.githubusercontent.com/1094080/174482512-d35540cf-4db5-4dee-8520-804b241cf420.png)

**Comment by cjduncana** [comment]
I love the design! Is there an idea for a homepage? Right now, if you visit https://www.roc-lang.org/builtins, it has no generated page. I noticed that the project's `README.md` points to https://www.roc-lang.org/builtins/Str instead.

**Comment by cjduncana** [comment]
Do we have the original files that generated the image in the OP? We can extract the distances among the elements from those files.
