### ISSUE TITLE
`List.range` is implemented as ceiling-exclusive, but docs say it's ceiling-inclusive

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3282]
From [the docs](https://github.com/rtfeldman/roc/blob/a957ba879f15ec3b0593bb8bec3179ec458084b0/compiler/builtins/roc/List.roc#L442):
```
## Returns a list of all the integers between one and another,
## including both of the given numbers.
##
## >>> List.range 2 8
range : Int a, Int a -> List (Int a)
```

However, I see this in the REPL:
```
» List.range 1 5

[1, 2, 3, 4] : List (Int *)

» 
```

Which should change, the implementation or the docs?

**Comment by extemporalgenome** [comment]
Is this addressed now?

**Comment by bhansconnect** [comment]
This uses the old version of List.range, so I think it can be closed.
