### ISSUE TITLE
MVP CLI Platform example

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3288]
- [x] `Task` with 3 type parameters
- [ ] `Stdout`, `Stderr`, `Stdin`
- [ ] `Env`
- [ ] `File` and `Path`
- [ ] `Http`
- [ ] A way to obtain a `List (List U8)` of the command-line arguments (not `List (List Str)` because CLI args may not be valid UTF-8, and there needs to be an opportunity for the application to gracefully recover from that possibility)

**Comment by JanCVanB** [comment]
I think you've done everything but the last task on that checklist! 😃 Great work.

**Comment by skyqrose** [comment]
Looks like this issue was never completed when basic-cli hit MVP.
