### ISSUE TITLE
Move `roc-bindgen` binary into `roc glue` subcommand

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3293]
For now, hardcode support for Rust bindings only.

In the future, this command will be given a `.roc` file which knows how to generate bindings for the target language, so it won't be coupled to Rust or to anything else. For now though, moving it into the `roc` binary will mean that users of the nightly `roc` binaries have access to this without having to build from source.

**Comment by ayazhafiz** [comment]
This is done!
