### ISSUE TITLE
`roc docs` panics instead of reporting a nice error message for missing auto-link symbol

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3294]
To reproduce, try to auto-link something that doesn't exist, e.g. `[doesNotExist]`. The panic is:

> 'Tried to generate an automatic link in docs for symbol doesNotExist, but that symbol was not in scope in this module.', docs/src/lib.rs:751:17

**Comment by skyqrose** [comment]
Replaced by https://github.com/roc-lang/roc/issues/3471 , which has a better solution: Report the error, and then continue to generate the docs anyway.
