### ISSUE TITLE
Firefox crashes on the Web REPL

### ISSUE THREAD

**Issue by brian-carroll** [roc-lang/roc#3364]
https://www.roc-lang.org/repl

On Firefox the `wasm-bindgen` init code tries to use the wasm module before it is actually loaded.
It displays `TypeError: wasm is undefined` for every expression.
This is a surprise!

This is a pure JS issue, there's not really any Wasm knowledge involved.
`wasm-bindgen` generates the `roc_repl_wasm.js` file and we have no control over it.
If someone wants to reproduce locally, check out repl_wasm/README.md

**Comment by Anton-4** [comment]
I could not reproduce this issue anymore on firefox 116.0 on Android 13. Please re-open if this still occurs.
