### ISSUE TITLE
roc check and roc build hang on module whose name does not follow its file name

### ISSUE THREAD

**Issue by Qqwy** [roc-lang/roc#3440]
Minimal example:

- Change `examples/hello-world/main.roc` to:
```elm
app "helloWorld"
    packages { pf: "platform/main.roc" }
    imports [Cheese]
    provides [main] to pf

main = "Hello, World!\n"
```

- Create the file `examples/hello-world/Cheese.roc` with the following contents:

```elm
interface NotCheese
  exposes []
  imports []
```

Now, running `cargo run -- check examples/hello-world/main.roc` or `cargo run -- build examples/hello-world/main.roc` will hang forever (while using 100% of the CPU).

**Comment by JanCVanB** [comment]
This just happened to me, and it looks similar to #4050.
