### ISSUE TITLE
Reporting crash for nested "lowercase tag name"

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3442]
To reproduce, enter this into the repl:

```
» Foo : [X, Y [z]]
thread 'main' panicked at 'assertion failed: c.is_lowercase()', crates/reporting/src/error/parse.rs:2449:21
```

This is syntactically invalid because `z` is lowercase and therefore type variable, but it's being used in a tag union without a tag name in front of it.

Usually we report a nice parse error for this - e.g. if you remove the `X` tag, it says:

```
── WEIRD TAG NAME ──────────────────────────────────────────────────────────────

I am partway through parsing a tag union type, but I got stuck here:

4│      Foo : [Y [z]]
                  ^

I was expecting to see a tag name.

Hint: Tag names start with an uppercase letter, like Err or Green.
```

However, in this very particular circumstance, we crash. Instead, we should report something nicer like the `WEIRD TAG NAME` error!

**Comment by Ivo-Balbaert** [comment]
This now gives a correct error message in the repl:

── WEIRD TAG NAME ──────────────────────────────────────────────────────────────

I am partway through parsing a tag union type, but I got stuck here:

4│      Foo : [X, Y [z]]
                  ^

I was expecting to see a tag name.

Hint: Tag names start with an uppercase letter, like Err or Green.


Probably can be closed. @Anton-4 ?
