### ISSUE TITLE
Parser doesn't accept empty tag union type with comment inside

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3445]
To reproduce:

```elixir
Never : [
    # This can never be instantiated
]
```

This should parse to the same thing as `Never : []` (except with the comment inside), but instead it's a parse error.

**Comment by Ivo-Balbaert** [comment]
I think this is solved. Both forms with parser issues now only give an UNUSED DEFINITION warning.

Can be closed @Anton-4 ?
