### ISSUE TITLE
Bad error message for package-qualified imports with no registered shorthand

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3489]
If I do e.g. `imports [foo.Blah]` but there is no `foo` shorthand defined in my root module's `packages` section, I should get a nice error. Currently I get a panic!

**Comment by Ivo-Balbaert** [comment]
Currently there isn't even a panic, the executing program hangs indefinitely it seems.

**Comment by JRI98** [comment]
No longer panics or hangs.

Current output for reference:
```
The package shorthand 'foo' that you are using in the 'imports' section of the header of module 'main.roc' doesn't exist.
Check that package shorthand is correct or reference the package in an 'app' or 'package' header.
```

**Comment by Ivo-Balbaert** [comment]
Probably can be closed.
