### ISSUE TITLE
Panic with unhelpful message when platform has a bad import

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3544]
To reproduce, in 6c62f72489de68f92493eeda9584c3879dedbd84 run:

```
cargo run -- check examples/interactive/cli-platform/main.roc
```

It produces the following unhelpful panic:

> 'The `Http.Response` is not a type alias or ability known in Effect', crates/compiler/can/src/module.rs:345:13

The fix is 58d153293636f75e8f51ac190a326485f2fa4e43 (the problem is that the import should be `HttpTypes`, not `Http`; the other missing imports aren't necessary to introduce the problem)

**Comment by skyqrose** [comment]
Pretty sure this is obsolete now. `Effect.roc`, which is the file linked in the fix, is much simpler now (either [this file](https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/examples/cli/effects-platform/Effect.roc#L4) or [this file](https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/cli/tests/test-projects/test-platform-effects-zig/Effect.roc#L4)), and doesn't have the bad import anymore. Even if the panic still exists in the compiler 2 years later, the reproduction is gone, so I'm closing this issue.
