### ISSUE TITLE
Effects with Tagged Unions don't generate caller functions.

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#3549]
Looking at https://github.com/bhansconnect/roc-async/tree/trunk/04-nested-future-continuations with the changes mentioned in #3548 to get type checking to pass leads to a Roc app that is missing the `roc__mainForHost_1_Continuation_*` and `roc__mainForHost_1_MoreCont_*` functions.

Both of theses types for main compile, but neither manages to generate the expected functions:
```
mainForHost : Effect [More Future ((I32 -> Effect Continuation) as MoreCont), Done I32] as Continuation
```
```
mainForHost : Effect ([More Future ((I32 -> Fx) as MoreCont), Done I32] as Continuation) as Fx
```

Theoretically the `Effect` wrapping is failing to generate functions for the nested types.

**Comment by ayazhafiz** [comment]
@bhansconnect is this still an issue?

**Comment by bhansconnect** [comment]
Given the plan is to remove `Effect` and just use tags directly for interfacing with the platform, I think this can be closed. Soon it will hopefully be fully obsolete.
