### ISSUE TITLE
Compiler panic on invalid syntax

### ISSUE THREAD

**Issue by MartinSStewart** [roc-lang/roc#3584]
The following code (with a syntax error on the last line)
```elm
app "helloZig"
    packages { pf: "main.roc" }
    imports []
    provides [main] to pf

main =
    a.joinWith "" []
```
causes the compiler to panic with this message
```
RUST_BACKTRACE=1 ./roc examples/hello-world/zig-platform/helloZig.roc
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/mono/src/ir.rs:9147:35
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: roc_mono::ir::match_on_lambda_set
   4: roc_mono::ir::with_hole
   5: roc_mono::ir::from_can
   6: roc_mono::ir::specialize_variable_help
   7: roc_mono::ir::specialize_external_help
   8: roc_mono::ir::specialize_all
   9: roc_load_internal::file::run_task
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Ivo-Balbaert** [comment]
The only way I can make sense of this code snippet is to assume that a is a type alias for Str.
Then this code:

main =
    a : Str
    a.joinWith "" []

gives following error:


── TYPE MISMATCH ────────────────────────────────────────────────── test16.roc ─

This expression is used in an unexpected way:

10│      a.joinWith "" []
         ^^^^^^^^^^

This a value is a:

    Str

But you are trying to use it as:

    { joinWith : * }b

which seems a legitimate error and is in any case no crash.
What do you think of this issue @Anton-4?

**Comment by MartinSStewart** [comment]
This issue is a year old so I'm guessing it's been fixed by someone already. Probably safe to close?

**Comment by lukewilliamboswell** [comment]
I am also unable to replicate this panic.
