### ISSUE TITLE
Reword "host" to "platform" in all app-developer-facing text

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3630]
I just learned about the Roc executable flag `--precompiled-host`, and it's great! However, it's confusingly named to an app developer. Roc app developer know about Roc platforms, but "host" is either meaningless, synonymous for platform, synonymous for platform language, or synonymous for server/device. Therefore, can we please protect app developers against any host confusion by only referring to platforms?

Where else does "host" appear?

- [ ] `--precompiled-host`

**Comment by vedant-z** [comment]
@JanCVanB Hey I want to work on this issue.

Can you please guide me specifically in which files I need to change "host" to "platform" ?

**Comment by JanCVanB** [comment]
I haven't done a file search, and I don't know how many phrases/variables containing "host" (other than `--precompiled-host`) could be improved with a rename. However, I recommend starting by editing any occurrences of `precompiled-host` (there may be other casings, such as `precompiledHost`, I don't know) and then expanding your search to analyze occurrences of `host`/`Host`.

**Comment by JanCVanB** [comment]
@bhansconnect do you have any tips for what other variables/names should be changed?

**Comment by JanCVanB** [comment]
I've started working on this renaming work myself, and I've realized that it's trickier that initially expected. Due to the dual meanings of both "host" (sometimes a language, sometimes a device) and "platform" (sometimes a Roc codebase, sometimes a CPU architecture), I've started a discussion in Zulip for feedback on various phrases & contexts.

**Comment by JanCVanB** [comment]
@vedant-z Well, that PR is definitely bigger than what I initially expected for this Issue! 😆
