### ISSUE TITLE
write tests for interactive examples

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#3633]
Current examples are tested [here](https://github.com/rtfeldman/roc/blob/trunk/crates/cli/tests/cli_run.rs), perhaps the test flow for interactive examples is different enough that they should be put in a separate file.
I recommend starting with a PR for the [countdown example](https://github.com/rtfeldman/roc/blob/trunk/examples/interactive/countdown.roc), get that merged in, and do a separate PR for the echo example.

The tricky thing with the echo example is that the process does not terminate automatically, you could keep inputting text and it would keep responding. This also means you'd have to wait some time after sending the input to check if the output is correct.

**Comment by skyqrose** [comment]
The examples have been restructured. The example tests are now in https://github.com/roc-lang/roc/tree/6a3db1e59ad087125c2ff630dfeadb2ffe0b78d8/crates/cli/tests/cli_tests.rs and the interactive examples are in `test-projects/effectful`
