### ISSUE TITLE
Letter repeat key presses dont work for some letters in some sequences in the editor

### ISSUE THREAD

**Issue by Chadtech** [roc-lang/roc#368]
You know how if you press and hold the `g` key youll get `gggggggggg` (in some editors)?

That works, but if I do several back to back, immediately switching from one letter to the next, _some_ letters dont work.

Here is a screen shot. All letter presses were pressed and held, not simply pecked.
<img width="456" alt="Screen Shot 2020-05-30 at 15 59 28" src="https://user-images.githubusercontent.com/2939686/83338110-e472b580-a28e-11ea-8c96-9c0cebbd7712.png">

So, If I pressed and held `c`, `f`, and `g` for example, immediately back to back, I only got "ccccccccccfg".

I  tried these examples on both my external keyboard and the keyboard built into my mac to test out whether it was my hardware. Different keyboard hardware did not lead to a different result.

**Comment by JanCVanB** [comment]
I can't reproduce this in the Roc editor (on Linux), but perhaps I'm doing it wrong. @Chadtech @rtfeldman and others, please feel free to reopen this issue for any reason!
