### ISSUE TITLE
X86 dev backend: Add overflow check and call to `roc_panic` for NumAdd, NumSub, NumMul

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#3795]
Subtask of https://github.com/roc-lang/roc/issues/3513

**Comment by shua** [comment]
it seems this is already implemented?
NumAdd: https://github.com/roc-lang/roc/blob/main/crates/compiler/gen_dev/src/generic64/mod.rs#L1353
NumSub: https://github.com/roc-lang/roc/blob/main/crates/compiler/gen_dev/src/generic64/mod.rs#L1831
NumMul: https://github.com/roc-lang/roc/blob/main/crates/compiler/gen_dev/src/generic64/mod.rs#L1512

Or is there something different?
