### ISSUE TITLE
X86 dev backend: NumAddChecked

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#3799]
Subtask of https://github.com/roc-lang/roc/issues/3513

**Comment by shua** [comment]
Looks like this is implemented for all num types as a call to bitcode: https://github.com/roc-lang/roc/blob/0e550a7f68f53d8699d484a426cd4963e0110539/crates/compiler/gen_dev/src/generic64/mod.rs#L1460-L1482
