### ISSUE TITLE
X86 dev backend: NumAddSaturated

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#3800]
Subtask of https://github.com/roc-lang/roc/issues/3513

**Comment by shua** [comment]
looks like this is done too?
https://github.com/roc-lang/roc/blob/e40b3cd6a92687843e04797419a8901aa918cdbd/crates/compiler/gen_dev/src/generic64/mod.rs#L1428

**Comment by shua** [comment]
missing `u128` and `i128` cases, so this could be opened again (sorry I missed that)
