### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by benjamin-thomas** [roc-lang/roc#3854]
Hello, I've played for an hour or two trying to get basic syntax highlighting working with vscode (since I'd like to play around with Roc as it progresses..., the experimental editor is too unstable for me)

I used the fsharp extension syntax file as a starting point, rather than the Elm extension, as it follows [this guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) to the letter so it seemed like a better fit.

After a bit of tweaking, this is what I've got:

![image](https://user-images.githubusercontent.com/1557738/185745007-817ccc65-20d3-4e76-bf87-704d9e65e3dc.png)

Commenting/uncommenting via the usual keyboard shortcut works too.

Now, I got something out quick and dirty which is not perfect but will do for my needs, for now.

Would you be interested in hosting this code and publishing the extension via the `roc-lang` org?

**Comment by rtfeldman** [comment]
Wow, super cool - thanks for taking the time to make this! I would gladly use this in vscode over my current practice of using CoffeeScript syntax highlighting. 😄

As for hosting and publishing, I'd suggest publishing it under your account - I think long term the org's focus should be on the Roc editor, and tooling for other editors should be a community thing.

I wouldn't want to send mixed messages by having the org appear to be responsible for both!

**Comment by benjamin-thomas** [comment]
Alrighty :)

So I've published the extension if you want to give it a go. It looks like vscode now hints that there's an extension for ".roc" files.

I got string interpolation too, crazy regexes + double escaping going on in those syntax files :p

![image](https://user-images.githubusercontent.com/1557738/185761687-850e4650-4db4-4968-bbe8-b31db027918f.png)

Keep up the good work!

**Comment by JanCVanB** [comment]
Link for the lazy :) https://github.com/benjamin-thomas/vscode-roc-lang-extension
