### ISSUE TITLE
Reintroduce layout caching

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#3882]
We should re-introduce layout caching on root variable keys.

- The cache gets invalidated every time subs rolls back in mono
- Add tracing to see how large of a cache is built
- Add tracing to see how many cache hits/misses we get, and the hit rate relative to cache size
- Add tracing to see how many lambda sets are hit in the cache
- Add tracing to see how large of a cache is rolled back

**Comment by ayazhafiz** [comment]
Right now, we should attempt cache invalidation in the same way subs cache is invalidated - that is, when invalidating, roll back to the previous cache we used. So we snapshot and rollback 1-1 with subs.

**Comment by ayazhafiz** [comment]
@folkertdev do you have any suggestions here, based on your previous excursions into caching layout? I don't know how long ago that was.

**Comment by folkertdev** [comment]
the previous attempt was long ago and very naive. We now need something fast (check if an FnvHashMap is maybe a good option here, otherwise a `VecMap`) where we can take and revert to snapshots (when variables are invalidated). Snapshots are easy with the `VecMap` approach: it's just a truncate (at least, if invalidation is based on rank, do I understand that correctly?)

**Comment by ayazhafiz** [comment]
FNV makes sense. It’s possible we may want to use an even simpler hash optimizer for integers, since that’s what our variables are.

Re invalidation - rank is not quite right. During mono rank is irrelevant. Instead I think we will want to use something like subs’ snapshots for the layout cache as well. We need to invalidate the cache whenever subs content is rolled back (or to be precise, when a variable’s content changes, which in practice is easiest approximated by subs rollback right now). 

we’ll want to optimize that though. If specializing a variable doesn’t change some other variable V’s content, we don’t want to invalidate V when we invalidate the specialized variable’s layout.
