### ISSUE TITLE
Stop surgical linker from breaking caching

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#3883]
Currently the surgical linker will break Rust caching. The issue is that the rust app compiles against a dylib that is generated by the surgical linker. Since we regenerate the the dylib on every run, the rust app final linking step will run every time even if nothing truly changed. As such, without the `precompiled-host` flag, we will waste a lot of timing doing unnecessary work.

We do need to regenerate the dylib on occassion when the platform api changes, but otherwise, it should remain static. Not sure the best way to fix this, but some sort of check to avoid generating the same dylib again may be necessary.

Note: this is just my current understanding of the issue, more investigation may lead to a different root cause

**Comment by folkertdev** [comment]
we could just parse the current dylib and check the `.dynsym` section to verify everything that should be there, is there

**Comment by folkertdev** [comment]
I'm observing

```
[crates/linker/src/lib.rs:303] std::time::Instant::now().duration_since(before) = 89.558612ms
[crates/linker/src/lib.rs:343] std::time::Instant::now().duration_since(before) = 89.783672ms
[crates/linker/src/lib.rs:518] std::time::Instant::now().duration_since(before) = 104.987961ms
[crates/linker/src/lib.rs:559] std::time::Instant::now().duration_since(before) = 105.165254ms
[crates/linker/src/lib.rs:561] text_sections.len() = 5
[crates/linker/src/lib.rs:680] md.surgeries.iter().map(|x| x.1.len()).sum::<usize>() = 0
[crates/linker/src/lib.rs:682] std::time::Instant::now().duration_since(before) = 604.348898ms
[crates/linker/src/lib.rs:709] std::time::Instant::now().duration_since(before) = 619.539276ms
[crates/linker/src/lib.rs:799] std::time::Instant::now().duration_since(before) = 707.186267ms
Finished rebuilding and preprocessing the host in 1270 ms
```

most time seems to be spent in this loop 

```
        while decoder.can_decode() {
            decoder.decode_out(&mut inst);
```

so it's not really a caching issue: the surgical linker is just slow when the platform is large
