### ISSUE TITLE
Undefined bahviour in `RocResult::into_payload`

### ISSUE THREAD

**Issue by isaacthefallenapple** [roc-lang/roc#3897]
I just started skimming this repo and found [this line](https://github.com/roc-lang/roc/blob/a8b83cfe372fd4fd3c713a0141f4ee371444e169/crates/roc_std/src/lib.rs#L156) in `roc_std` (comment mine):
```rust
let mut value = MaybeUninit::uninit();
let ref_mut_value = unsafe { &mut *value.as_mut_ptr() }; // UB!
```

From the [`MaybeUninit::as_mut_ptr` docs](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html#method.as_mut_ptr):
> Reading from this pointer or **turning it into a reference is undefined behavior** unless the MaybeUninit<T> is initialized.

I believe to do this safely, `self.payload` has to be copied directly:
```rust
fn into_payload(self) -> RocResultPayload<T, E> {
    let mut value = MaybeUninit::uninit();

    // copy the value into our MaybeUninit memory
    unsafe {
        core::ptr::copy_nonoverlapping(&self.payload, value.as_mut_ptr(), 1);

        // don't run the destructor on self; the `payload` briefly has two owners
        // but only `value` is allowed to drop it (after initialization)
        core::mem::forget(self);
    }

    unsafe { value.assume_init() }
}
```

This is my first issue on this (very exciting) project so I wanted to get some feedback before submitting a PR.

**Comment by Anton-4** [comment]
@folkertdev

**Comment by folkertdev** [comment]
yes that looks good. maybe move the `forget` outside of the unsafe?

**Comment by isaacthefallenapple** [comment]
@folkertdev I'll defer to you but I kept it in the unsafe block to indicate that it only becomes safe again once `self` is forgotten and can't drop `payload` anymore. Otherwise one might think it's okay to arbitrarily keep working with `self` between the `copy` and the `forget` even though it's not.
