### ISSUE TITLE
Move all `rocLovesFoo.roc` examples into parent dir

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3912]
These example apps are used so frequently (usually to test whether a platform language compiler like the Rust or Zig compiler is properly installed on one's system) that it's worth shortening their paths.

For example, `examples/platform-switching/rust-platform/rocLovesRust.roc` should be moved to `examples/platform-switching/rocLovesRust.roc`, as well as the example apps for Zig, C, etc.

**Comment by JanCVanB** [comment]
References to these example apps (such as those in `getring-started/*.md`) will also need to be updated.

**Comment by sandprickle** [comment]
PR #3943 should resolve this. Let me know if I missed anything!
