### ISSUE TITLE
Expect on user app/interface references expects in the stdlib

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#3921]
For example, if I add the expect

```
expect
    a = "f"
    b = "g"
    a == b
```

to a user-level app or interface, I get the following output with `roc test`

```
── EXPECT FAILED ─────────────────────────────── examples/hello-world/main.roc ─

This expectation failed:

6│>  expect
7│>      a = "f"
8│>      b = "g"
9│>      a == b

When it failed, these variables had these values:

a : Str
a = "f"

b : Str
b = "g"

1 failed and 3 passed in 400 ms.
```

The relevant bit is the last line. The other 3 expects come not from the user-level module, but from expects in the standard library! We shouldn't be running or displaying those for userspace roc test runs.

**Comment by TAGraves** [comment]
I think this is a duplicate of https://github.com/roc-lang/roc/issues/3722

**Comment by ayazhafiz** [comment]
Thanks Tommy
