### ISSUE TITLE
Compiler bug when formatting

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3924]
[This app](https://github.com/JanCVanB/project-euler-in-roc/blob/985097770e3770474fe42a546ac0f70f543b7fcf/3.roc) passes testing & type checking. It currently segfaults because the algorithm is naive, but reducing the top number from `600851475143` to something like `100` fixes that.

However, when I run `roc format 3.roc` on it, I get this output:
```
[jan@framey project-euler-in-roc]$ roc format 3.roc
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Formatting bug; formatting didn't reparse as the same tree

I wrote the incorrect result to this file for debugging purposes:
3.roc-format-failed

I wrote the tree before and after formatting to these files for debugging purposes:
3.roc-format-failed-ast-before
3.roc-format-failed-ast-after

', crates/cli/src/format.rs:110:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey project-euler-in-roc]$ 
```

I've attached the debugging files with the `.txt` suffix for GitHub's sake:
[3.roc-format-failed.txt](https://github.com/roc-lang/roc/files/9440784/3.roc-format-failed.txt)
[3.roc-format-failed-ast-before.txt](https://github.com/roc-lang/roc/files/9440783/3.roc-format-failed-ast-before.txt)
[3.roc-format-failed-ast-after.txt](https://github.com/roc-lang/roc/files/9440781/3.roc-format-failed-ast-after.txt)

**Comment by JanCVanB** [comment]
NEVERMIND THE ABOVE EXAMPLE, I just found a much simpler reproduction:

```
app "this_breaks_the_formatter"
    packages { pf: "../roc/examples/hello-world/platform/main.roc" }
    imports []
    provides [main] to pf

main = ""

expect
    x = 1
    y = 2
    x == y

expect 1 == 2
```

```
app "this_does_not_break_the_formatter"
    packages { pf: "../roc/examples/hello-world/platform/main.roc" }
    imports []
    provides [main] to pf

main = ""

expect
    x = 1
    y = 2

    x == y

expect 1 == 2
```

```
app "this_is_also_fine"
    packages { pf: "../roc/examples/hello-world/platform/main.roc" }
    imports []
    provides [main] to pf

main = ""

expect
    x = 1
    y = 2
    x == y
```

The failure seems to happen with any app that has a multi-line `expect` without a pre-return line break, followed by another `expect` anywhere later in the module.

**Comment by JRI98** [comment]
No longer reproduces
