### ISSUE TITLE
Some builtins unavailable in platforms

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4001]
Trying to use the `Str.Utf8Problem` type alias in an application works, but using it in a platform yields a compiler panic with `Alias Str.Utf8Problem not registered in delayed aliases`. (Separately, it shouldn't need to be qualified with `Str.`; the rule is that every builtin module should be imported automatically, and all their exposed types should be imported unqualified automatically. Maybe we could write a test to verify this for all builtin modules?)

Also, the `Decode` module is not imported by default, but importing it explicitly in platform code causes the compiler to hang. (Importing it in application modules works fine.)

**Comment by ayazhafiz** [comment]
This is now fixed!
