### ISSUE TITLE
Potential zero-sized value bugs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#403]
I haven't attempted to reproduce any problems, but I'm confident there are bugs around the situation where both of the following are true:

* A record has multiple fields that are *not* zero-sized
* It also has at least one field that *is* zero-sized preceding a field that is *not* zero-sized

I think this because we store record accesses by index in `mono::Expr` (using `AccessAtIndex`), and that means I suspect at least one of the following bugs are present:

* If I try to access a field following a zero-sized one, I'm not sure what happens - is the correct index still calculated, adjusting for the fact that there's no field preceding this field at runtime even though it was there at compile time?
* If I try to access a zero-sized value, I'm also not sure what happens. Does that access compile to a no-op? (That's what it ought to do, but does it?)

There are probably other, similar bugs around these scenarios that I'm not thinking of right now.

**Comment by rtfeldman** [comment]
@folkertdev do you know if we currently handle these scenarios correctly?

**Comment by folkertdev** [comment]
we sort fields by alignment, so I don't think this is actually a problem at all.
