### ISSUE TITLE
glue hangs if interface name does not match filename

### ISSUE THREAD

**Issue by BrianHicks** [roc-lang/roc#4050]
On 57681be5420586fff80ca6c6f850a9bfc7e6a4c2, given the following files `roc glue Package-Config.roc glue.rs` will just hang forever.

`Package-Config.roc`:

```elixir
platform "roc-lang/rbt"
    requires {} { init : SomeInterface.RecursiveThing }
    exposes [SomeInterface]
    packages {}
    imports [SomeInterface]
    provides [initForHost]

initForHost : SomeInterface.RecursiveThing
initForHost = init
```

`SomeInterface.roc`:

```elixir
interface Rbt
    exposes [RecursiveThing]
    imports []

RecursiveThing : [RecursiveThing Str]
```

(`RecursiveThing` is not a great name for this extremely non-recursive type, but I was trying for a different SSCCE when I found this!)

**Comment by BrianHicks** [comment]
ahhhh, looks like `interface Rbt` in the filename `SomeInterface.roc` might be the problem here! But still it hangs forever if the name is wrong.

**Comment by JanCVanB** [comment]
This just happened to me, and it looks similar to #3440.
