### ISSUE TITLE
Improve "I tried to read this file, but ran into a" error

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4052]
The error "I tried to read this file, but ran into a" on [this line](https://github.com/roc-lang/roc/blob/166be98ac8b6c2446753423ea827220a42276954/crates/compiler/load_internal/src/file.rs#L5601), occurs when you pass a directory to the roc command (`roc ./examples/hello-world/`) instead of a file. It will also happen if you use a directory instead of a file at `packages { pf: "some_folder"`.

If we can reasonably include the path (like `./examples/hello-world/` and `some_folder` from above) in the error message it would be a lot easier to figure out what's going wrong.
This path might be the argument `filename: &Path` in the function `to_file_problem_report(` but I'm not sure.

**Comment by rezzaghi** [comment]
Maybe it can be done in the same way as this [line](https://github.com/roc-lang/roc/blob/e9f162c9165ff9d9102565d35c97b10232170671/crates/compiler/load_internal/src/file.rs#L5591])?

something like:

"I tried to read this file: 
[path] 
But ran into a..."

**Comment by Anton-4** [comment]
Excellent find @rezzaghi!
Feel free to give this issue a try if you'd like :)
We want the process of new contributors getting started to be as smooth as possible, so you can always contact me in case of questions or difficulties.
