### ISSUE TITLE
Hello.roc (TUTORIAL.md) not running on MacOS Silicon 

### ISSUE THREAD

**Issue by studiorubenz** [roc-lang/roc#4055]
Following the TUTORIAL.md (using roc_nightly-macos_apple_silicon-2022-09-14-6613e9d.tar.gz) I can't make the first program "hello" run. When I type `roc Hello.roc` I get this:

```
── TYPE MISMATCH ────────────────── examples/interactive/cli-platform/main.roc ─

Something is off with the type annotation of the main required symbol:

2│      requires {} { main : List Str -> Task {} [] * }
                             ^^^^^^^^^^^^^^^^^^^^^^^^

This #UserApp.main value is a:

    InternalTask.Task {} * [Write [Stdout]*]* ?

But the type annotation on main says it should be:

    (List Str -> Task.Task {} [] a ?)

Tip: Type comparisons between an opaque type are only ever equal if
both types are the same opaque type. Did you mean to create an opaque
type by wrapping it? If I have an opaque type Age := U32 I can create
an instance of this opaque type by doing @Age 23.


── TOO FEW ARGS ─────────────────── examples/interactive/cli-platform/main.roc ─

The main function expects 1 argument, but it got only 1:

9│  mainForHost = \args -> InternalTask.toEffect (main args)
                                                  ^^^^

Roc does not allow functions to be partially applied. Use a closure to
make partial application explicit.

────────────────────────────────────────────────────────────────────────────────

2 errors and 0 warnings found in 10 ms.

You can run the program anyway with roc run Hello.roc
```

Thank you for pointing an absolute roc-beginner in the right direction!

**Comment by Anton-4** [comment]
@ayazhafiz I think this was caused by changes to examples/interactive/cli-platform/main.roc in ec628ed5c634cd592fe0797267f51085206e5c89. Can you update cli snippets in TUTORIAL.md?

**Comment by studiorubenz** [comment]
Thanks a lot, @Anton-4, this would totally make sense as the 'interface' of main has obviously changed.
(If I can figure it out myself, I will create a PR.)

**Comment by studiorubenz** [comment]
@ayazhafiz & @Anton-4, I tried but I cannot figure out myself. Sorry!
So I'd really appreciate if this could get fixed (so I can continue learning roc ;-) , thanks!

**Comment by Anton-4** [comment]
Can you plan this in @ayazhafiz?

**Comment by rtfeldman** [comment]
https://github.com/roc-lang/roc/pull/4104 should have updated this, and it's now merged in!

@studiorubenz can you try out [the current `TUTORIAL.md`](https://github.com/roc-lang/roc/blob/main/TUTORIAL.md) and see if that works for you? (You might need to update your local clone of this repo too, since the `examples/cli-platform` directory contents have changed in a relevant way for this update!)

**Comment by studiorubenz** [comment]
After updating roc to the latest build it worked – awesome!
Thank you so much, @rtfeldman, @Anton-4 and @ayazhafiz!
