### ISSUE TITLE
Reporting crashes for parse error on incomplete backpassing expression

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4086]
To reproduce:

```haskell
x =
    y <- Result.try (Ok 1)

"Hello, World!\n"
```

This panics with:

`'not yet implemented: unhandled parse error: IndentEnd(@100)', crates/reporting/src/error/parse.rs:532:14`

**Comment by Ivo-Balbaert** [comment]
This now gives a normal error (with basic cli 0.4.0):

── INDENT ENDS AFTER EXPRESSION ─────────────────────────────────── test17.roc ─

I am partway through parsing an expression, but I got stuck here:

 1│  app "test"
 2│      packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br" }
 3│      imports [
 4│          pf.Stdout, pf.Task.{ Task },
 5│      ]
 6│      provides [main] to pf
 7│
 8│  # main : Task {} U32
 9│  main =
10│      x =
11│          y <- Result.try (Ok 1)
                                   ^

Looks like the indentation ends prematurely here. Did you mean to have
another expression after this line?

**Comment by lukewilliamboswell** [comment]
```
app "test"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br",
    }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf

main = 
    x =
        y <- Result.try (Ok 1)

    Stdout.line "Hello, World!\n"

```

```
% roc dev test.roc
── INDENT ENDS AFTER EXPRESSION ───────────────────────────────────── test.roc ─

I am partway through parsing an expression, but I got stuck here:

 1│  app "test"
 2│      packages {
 3│          pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br",
 4│      }
 5│      imports [
 6│          pf.Stdout,
 7│      ]
 8│      provides [main] to pf
 9│
10│  main = 
11│      x =
12│          y <- Result.try (Ok 1)
                                   ^

Looks like the indentation ends prematurely here. Did you mean to have
another expression after this line?% 
```
