### ISSUE TITLE
`expect` doesn't print output during execution of app

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4093]
Top level expects work, but expects in functions and thunks don't work.

To repo, change `examples/hello-world/main.roc` to:
```coffee
app "helloWorld"
    packages { pf: "platform/main.roc" }
    imports []
    provides [main] to pf

main = 
    # This should fail.
    expect 3 == 4
    
    "Hello, World!\n"
```

Then `roc dev examples/hello-world/main.roc`.

The output is:
```
🔨 Rebuilding platform...
Hello, World!
```

The expect is not run and does not print a message, but it should print out that 3 == 4 does not hold true and the expect has failed.

**Comment by Ivo-Balbaert** [comment]
At this moment, both roc and roc dev when run with this code give:

── EXPECT FAILED ────────────────────────────────────────────────── test17.roc ─

This expectation failed:

12│      expect 3 == 4
                ^^^^^^

So I think this issue can be closed, @Anton-4 ?

**Comment by lukewilliamboswell** [comment]
```
% roc dev test.roc 
── EXPECT FAILED ──────────────────────────────────────────────────── test.roc ─

This expectation failed:

12│      expect 3 == 4
                ^^^^^^

Success!
```
```
app "test"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br",
    }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf

main = 
    # This should fail.
    expect 3 == 4
    
    Stdout.line "Success!"

```
