### ISSUE TITLE
building GUI example results in "XdgRuntimeDirNotSet" error

### ISSUE THREAD

**Issue by nick-gravgaard** [roc-lang/roc#4132]
I've just installed the latest Ubuntu on a VirtualBox host, and used shared folders to copy across the latest nightly build archive of roc and my recently cloned roc repo.

Building the repo's `examples/gui/Hello.roc` using the roc binary from the archive file results in an error.

```
nick@nick-VirtualBox:~/Downloads/roc_nightly-linux_x86_64-2022-09-28-11ef947$ ./roc ~/repos/roc/examples/gui/Hello.roc
🔨 Rebuilding platform...
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
```

This does however create a `hello-gui` file which successfully opens a window when run. When I close that window I get a `Segmentation fault (core dumped)` message in the console.

**Comment by rtfeldman** [comment]
Hm, what happens if you run `roc edit` from the command line? Same error?

**Comment by nickgravgaard** [comment]
Nope, `roc edit` works and does not output an error message to the console when I close the window.

**Comment by nickgravgaard** [comment]
The `ZDG_RUNTIME_DIR` env var is set to `/run/user/1000` in my shell before I run roc. Is there any reason why this env var would not be visible when the GUI example is built before being run? (as opposed to running the built binary directly which does successfully open a window)

**Comment by skyqrose** [comment]
The gui example was broken and was removed from the repo in https://github.com/roc-lang/roc/pull/6917. It's now in https://github.com/roc-lang/examples/pull/190 , in a better state (but still not merged). I'm not sure if this problem still exists, but if it does, it would belong as an issue in the other repo now.
