### ISSUE TITLE
Indented lambda bodies

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4139]
As [discussed on Zulip](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/lambdas.20in.20pipelines), we want to make it possible to write lambdas like this without needing parentheses:

```elm
"a string"
|> Str.toUtf8
|> List.map \byte -> byte + 1
|> List.reverse
```

Today, this gets parsed as:

```elm
"a string"
|> Str.toUtf8
|> List.map (\byte -> byte + 1 |> List.reverse)
```

However, if we change the parser so that lambda bodies work more like `when` branches - as in, the body of the lambda must have a *higher* indentation level than the indentation level of the line containing the `\` that begins the lambda (just like how `when` branches must have higher indentation than the line containing the `when` keyword), and once there is an outdent, then the lambda's body ends - then this would Just Work the way it looks like it would:

```elm
"a string"
|> Str.toUtf8
|> List.map \byte -> byte + 1
|> List.reverse
```

After this change, normally formatted lambdas would be unaffected. However, lambdas formatted like this would become parsing errors:

```elm
fn = \nums ->
    List.map nums \num ->
    num + 1
```

Ideally we could give a helpful error message in situations like this!

**Comment by joshuawarner32** [comment]
I think a slightly nicer process/rule might be:
* For every line, keep track of the indent level of that line in the `State`
* During parsing, each parse function (i.e. each node in the ast) checks the current indent of the line it starts on
* Require all child nodes to have _strictly greater_ column than that starting indent
  * For nodes on the same line, this is trivially true
  * For nodes on the next line, this seems more natural to me (coming from a more python background, than a haskell background)

Concretely, I think this rule would follow the intent in this issue (making sure the lambda doesn't gobble the following `|>` in your first example) - but it also means your last example parses fine and does the obvious thing.

So this would be fine:
```
fn = \nums ->
    List.map nums \num ->
    num + 1
```

**Comment by joshuawarner32** [comment]
Err wait, sorry - that'd need to be formatted like this:
```
fn = \nums ->
    List.map nums \num ->
        num + 1
```

**Comment by joshuawarner32** [comment]
So... I think I'm mostly agreeing with what you originally said - except the quibble that I think it's not the column of the `\` that should matter, but rather the indent level of the line the `\` is on that should matter.

That makes things much nicer for folks coming from languages like python, expecting to be able to indent the bodies of functions/lambdas by a fixed amount relative to the parent scope - but also accepts the haskell syntax for indentation (mostly) fine.

**Comment by joshuawarner32** [comment]
Note that the main disadvantage of the indentation rules I'm proposing here, is that (unlike under the haskell indentation rules), you can't have multiple continuations of of a single line - i.e. you can't do something like this:
```
fn = \x -> when x is 0 -> 0
                     1 -> 1
        + 1
```
There the `+ 1` is supposed to be attached like `(when ...) + 1`.

However, I'd argue that's much clearer when written explicitly:
```
fn = \x -> 
    (
        when x is
            0 -> 0
            1 -> 1
    ) + 1
```

Or, even better, breaking out a temporary variable:
```
fn = \x -> 
    a = when x is
        0 -> 0
        1 -> 1
    a + 1
```
... so this doesn't seem like a great loss to me.

**Comment by rtfeldman** [comment]
Yeah, I totally agree! It wouldn't even occur to me to try to write the `+ 1` like the original. That would be really confusing, I think - I would have guessed it would be equivalent to the last branch being `1 -> 1 + 1`, which wouldn't have been the intent.

Overall this seems like a great approach to me! 💯
