### ISSUE TITLE
"also known as" in docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4141]
We should have a concept of "also known as" in the docs, so that when you search for (for example) `foldl` or `reduce`, your search results include `walk`, and the same for `List.filterMap` and `List.keepOks`, `flatMap`/`andThen`/`bind` and `Task.await`/`Result.try`, etc. Also when you search for `println` or `puts` in the CLI platform, you get `Stdout.line` in your search results.

**Comment by Anton-4** [comment]
I wanted to make sure everything is working as intended. Entering `foldl` and `reduce` in the search box on https://www.roc-lang.org/builtins/List does not show `walk`. Can you link the PR where this was completed @rtfeldman?
