### ISSUE TITLE
Conservative inference of tag functions

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4150]
The following program checks and compiles:

```
g : Str -> [H Str, J Str]
g = if Bool.true then H else J

g ""
```

however if I remove the type annotation

```
g = if Bool.true then H else J

g ""
```

It does not. I think we should try to infer the function-based definition when possible. Doing so is tricky in the presence of generalization but we can make it happen.

This is not an esoteric example; it comes up when you're parsing. For example, in solving https://adventofcode.com/2021/day/2, I want to define a parser

```
Command : [Forward U64, Down U64, Up U64]

parseCmd =
    oneOf [
        map (string "forward") (\_ -> Forward),
        map (string "down") (\_ -> Down),
        map (string "up") (\_ -> Up),
    ]

parseLine =
    const (\cmd -> \_spaces -> \num -> \_newline -> cmd num)
    |> apply parseCmd
    |> apply spaces
    |> apply digits
    |> apply newline
```

However, with the above bug, this does not check. Moreover it not enough to add a type annotation to `parseCmd`; you must add a type annotation to the lambdas `\_ -> Forward`, or re-write them as `\_ -> (\n -> Forward n)`.

**Comment by rtfeldman** [comment]
In general, I consider anything of the form "this checks and compiles unless I remove a type annotation" a bug, so by default I'm in favor of inferring the (potentially) function-based definition! 😄

**Comment by ayazhafiz** [comment]
yeah it definitely is a bug
