### ISSUE TITLE
repl tips at start-up: assignment

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4160]
On repl start-up we should show some important tips for the follwing problem situations:

Typing `total = 4` followed by enter in the repl will simply start a new line which may leave new users confused with what is expected of them. We should say something like "Everything in the repl needs to be an expression, it needs to return something.". We should probably show a minimal example like:
```
foo = 1

foo
```

**Comment by Areadrill** [comment]
Hi. I'd love to be assigned to this.

**Comment by Anton-4** [comment]
That was quick, it's all yours!
Feel free to reach out if you need any help :)

**Comment by Areadrill** [comment]
Could take a gander at my draft and tell me if that is more or less what you expected? Just as a start
