### ISSUE TITLE
repl tips at start-up: how to newline

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4161]
On repl start-up, below `Enter an expression, or :help, or :q to quit` we should mention how to create a new line.
So something like:
You can use `Ctrl+V`+`Ctrl+J` to make a newline. The repl will also insert a newline if you press enter when the current expression can not be evaluated, e.g. when you type `foo =<ENTER>`.

**Comment by jmakhack** [comment]
Hey @Anton-4, I would love to work on this. Can I get assigned this issue if it is still available?

**Comment by Anton-4** [comment]
@jmakhack you've been assigned :)
Feel free to reach out for help!

**Comment by Anton-4** [comment]
Good question, we probably want to add this new tip before [this line](https://github.com/roc-lang/roc/blob/f1c34513845965c34accf5c9e2400c6997db4ed4/crates/repl_cli/src/lib.rs#L61).

**Comment by jmakhack** [comment]
@Anton-4, I've opened PR #4226 a few days ago. Can I get a reviewer to look over my changes?

**Comment by Anton-4** [comment]
Yes I missed that, thanks for notifying me @jmakhack!
