### ISSUE TITLE
Expand `examples/cli-platform` Stdout/Stdin/Stderr functions to use Results

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4165]
Currently, we do a lot of unwrapping in these functions and they can just panic.

This is not what we want. For example, you currently can't read from `Stdin` until `EOF`. If you use `Stdin.line`, it will either return a line or panic rust. This is just one case where we should return a result instead. I think most functions linked to those modules should return results instead.

**Comment by ayazhafiz** [comment]
Should this necessarily return errors? What method of recovery does a Roc program have if e.g. `Stdout.line` fails?

**Comment by bhansconnect** [comment]
Yeah, maybe it doesn't apply to all of them. At a minimum, `Stdin.line` needs to return and option so that we can tell when we have consumed the last line and no more will follow.

**Comment by skyqrose** [comment]
These examples were removed in https://github.com/roc-lang/roc/pull/6034
