### ISSUE TITLE
Give builtins a proper homepage and link to them in docs/on website.

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4166]
[roc-lang.org/builtins](http://roc-lang.org/builtins) currently is a 404. You need to go to a module like [roc-lang.org/builtins/List](http://roc-lang.org/builtins/List) instead. It is also not linked to in many places. This should be linked in more places to help with discoverability of documentation.

**Comment by skyqrose** [comment]
This exists now at https://www.roc-lang.org/builtins , and it's linked to from https://www.roc-lang.org/docs , which is linked to from the nav bar of the home page.
