### ISSUE TITLE
Unable to run roc on MacOS 11

### ISSUE THREAD

**Issue by sporto** [roc-lang/roc#4185]
I cannot upgrade my Mac to OS 12 unfortunatelly.
When I try to run the Mac Intel binary I get

```
dyld: Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Users/Sebastian/Downloads/roc_nightly-macos_x86_64-2022-10-01-2b91154/./roc (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/Sebastian/Downloads/roc_nightly-macos_x86_64-2022-10-01-2b91154/./roc
```

Maybe we could have a build to MacOS 11
Thanks

**Comment by Anton-4** [comment]
I'm working on this in PR  #4178

**Comment by Anton-4** [comment]
Can you give this a try @sporto?
[roc_nightly-macos_11_x86_64-2022-10-10-ec6b93c.tar.gz](https://github.com/roc-lang/roc/files/9745951/roc_nightly-macos_11_x86_64-2022-10-10-ec6b93c.tar.gz)

**Comment by sporto** [comment]
@Anton-4 this one works well

**Comment by Anton-4** [comment]
Awesome :) I'll set it up with the other nightly releases.
