### ISSUE TITLE
Support types bound to multiple abilities

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4189]
In the pursuit of supporting hash-based `Dict`s/`Set`s, we'll need a way to say that a type has multiple abilities (specifically for these hash-based containers, they need both `Hash` and `Eq`). That is, we'd like to say something like

```
Dict k v := ... | k has Eq, Hash
```

I could see some other syntaxes here, like

```
Dict k v := ... | k has Eq, k has Hash
```

@rtfeldman what are you thoughts? I know you've also wanted to explore the `k supports Eq` syntax as well; it's separate but we should do that sooner rather than later as well.

**Comment by extemporalgenome** [comment]
Would something like `Dict k v := ... | k has Eq | k has Hash` (with `k has Eq, Hash` as a shorthand) be reasonable? I'm thinking of multiline-friendliness, possibly with an author's choice ordering of clauses.

**Comment by ayazhafiz** [comment]
@extemporalgenome there is now a discussion on Zulip: https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Binding.20type.20variables.20to.20multiple.20abilities
