### ISSUE TITLE
Implement the Hash and Hasher ability

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4195]
- [x] #4201
- [x] 2. Compiler Side
  - [x] #4200
    - The rules here are like what they are for encode/decode. Functions cannot be hashed. Optional records also cannot be hashed.
  - [x] #4202
    - All number types should be immediates
    - List (T) decays to repeated applications of `hash<T>`, it's just a List.walk basically
    - Records: hash each field
    - Tags: hash the discriminant, then each value in the corresponding payload
- [ ] 2. Builtins Side
  - [x] Implement a default type that uses `Hasher`, for use in the stdlib Hash/Dict
  - [x] #4206
  - [ ] Implement a Hash-based Dict that binds the key to `Hash`
  - [ ] Implement hash-based Set (this likely can just be defined as `Set k := Dict k {}`

**Comment by ayazhafiz** [comment]
@bhansconnect want to split this up such that you take the stuff on the Builtins Side, and I take the compiler-side work/

**Comment by bhansconnect** [comment]
Yeah, that sounds great!
