### ISSUE TITLE
add `Dict.replace` or `Dict.update` builtin

### ISSUE THREAD

**Issue by ghigt** [roc-lang/roc#4239]
Be able to update/replace an element of a `Dict`.

Following discussion on [zulip](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/builtins/near/302742164), @rtfeldman suggested the definition like in [Elm](https://package.elm-lang.org/packages/elm/core/latest/Dict#update):
```elm
Dict.update :
    Dict k v,
    k,
    ([Present v, Missing] -> [Present v, Missing])
    -> Dict k v
```

**Comment by rtfeldman** [comment]
I like `Dict.update` for this, both because there's precedent for it (Elm uses that name for this operation) and because `List.replace` in Roc is a different operation altogether!
