### ISSUE TITLE
roc test crash when using |>

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4244]
This may be the intended behaviour. It gives an EXPECT PANICKED and a crash report that is difficult to interpret. Maybe this just needs a nicer error printed out? 

```elixir
# Passes
expect "SomeString" == Str.concat "Some" "String"
expect "SomeString" == ("Some" |> Str.concat "String")

# Crashes with "Hit an erroneous type when creating a layout for `5.IdentId(7)`"
expect "SomeString" == "Some" |> Str.concat "String"
```

**Comment by ayazhafiz** [comment]
Yeah, we need a better error here. This parses as

```
expect ("SomeString" == "Some" |> Str.concat) "String"
```

which leads to a type error that then doesn't get printed out well.

**Comment by lukewilliamboswell** [comment]
This issue has been resolved.
