### ISSUE TITLE
Segfault in examples/gui/breakout platform

### ISSUE THREAD

**Issue by marcospri** [roc-lang/roc#4285]
A small change to [hello.roc](https://github.com/roc-lang/roc/blob/main/examples/gui/breakout/hello.roc) to include a list of values in the model

```diff
app "breakout"
     packages { pf: "platform/main.roc" }
-    imports [pf.Game.{ Bounds, Elem, Event }]
+    imports [pf.Game.{ Bounds, Elem, Event, Rgba }]
     provides [program] { Model } to pf
 
-Model : { text : Str }
+Model : { text : Str, colors: List (Rgba) }
 
 init : Bounds -> Model
-init = \_ -> { text: "Hello, World!" }
+init = \_ -> { text: "Hello, World!", colors: List.repeat {r:1, g: 1, b: 1, a: 1 } 1}
 
 update : Model, Event -> Model
 update = \model, _ -> model
```

Results in a segfault:

```
cargo run -- build examples/gui/breakout/hello.roc
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/roc build examples/gui/breakout/hello.roc`
🔨 Rebuilding platform...
0 errors and 0 warnings found in 8843 ms while successfully building:

    examples/gui/breakout/breakout

examples/gui/breakout/breakout
thread 'main' panicked at 'assertion failed: (*next).value.is_some()', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sync/mpsc/mpsc_queue.rs:95:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2]    4154625 segmentation fault (core dumped)  
```

Tested with in commit e32cd14 in ubuntu x86_64.

An empty list in `init` doesn't cause the problem. I suspect some sort of problem around the layout here https://github.com/roc-lang/roc/blob/main/examples/gui/breakout/platform/src/roc.rs#L398 but this is way over my head so that might be nonsense.

In case it's useful here valgrinds's output on the resulting binary: [breakout.valgrind.txt](https://github.com/roc-lang/roc/files/9746330/breakout.valgrind.txt)

**Comment by ghigt** [comment]
I can't reproduce your segfault.
I'm on MacOS arm64 (M1) with the latest build (commit https://github.com/roc-lang/roc/commit/e32cd140a80d5589563753073408bc25ea529bb5), what is yours?

**Comment by marcospri** [comment]
Thanks @ghigt, just tested in the same commit with the same (segfault) result. I'm in ubuntu x86_64.

Added this info to the first comment.
