### ISSUE TITLE
`roc format` doesn't add spaces around `?` in optional record field

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4327]
You can see the bad formatting that it allows here: https://github.com/roc-lang/roc/blob/856f0516199bbc30bd204f216705d47c3e557385/crates/compiler/builtins/roc/Dict.roc#L240

Essentially, this: `{ seed ?U64 }` should be `{ seed ? U64 }`

I have not worked on the formatter, but I would assume this should be a pretty simple fix.

**Comment by rnice01** [comment]
I'd like to work on this if possible.

**Comment by bhansconnect** [comment]
Sounds great. Feel free to ask questions on [the contributing thread on zulip](https://roc.zulipchat.com/#narrow/stream/316715-contributing) in a new topic or via questions here.
