### ISSUE TITLE
Write up `my-first-roc-project.md`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4344]
This might be a valuable focused addition to our current resources.
I'd put some minimal platform information here, guidance on choosing a platform, explaining glue, link to other resources...

**Comment by skyqrose** [comment]
There's the tutorial now (I think it's newer than this issue) which would be the place for some of this, if it's not already there. There's always improvements to make to documentation, but I don't think this old issue is a useful way to track that work anymore, so I'm closing this issue. If there are still ideas here that are important to be in an issue (and aren't already covered in another issue, check the [website tag](https://github.com/roc-lang/roc/issues?q=is%3Aopen+is%3Aissue+label%3Awebsite)), then it should probably be a new issue.
