### ISSUE TITLE
"cargo test" doesn't work in surgical-linker-enabled platforms

### ISSUE THREAD

**Issue by BrianHicks** [roc-lang/roc#4373]
In https://github.com/roc-lang/rbt/pull/82, I have a problem: I have to enable the surgical linker to get CI to pass, but enabling the surgical linker means I need to have an `app` to link against. Before I run `roc build`, I don't have `libapp.so`, and on macOS that file isn't generated at all. Practically speaking, that means I have no good way to run `cargo test` in rbt on macOS! Yikes!

I know this issue is a little vague, sorry! I'm not sure how to make it more specific right now. 😬

**Comment by bhansconnect** [comment]
This should now have a workaround through #4380. You can now run `roc gen-stub-lib some-example-app.roc`. That will give you a `libapp.so` for linking.
