### ISSUE TITLE
`crash` keyword

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4384]
Based on discussions on Zulip, we should introduce a new `crash` keyword with the following semantics:

- `crash "uh oh"` is a valid expression which has the type `*`
- `crash` is a language keyword, not a function; you can't do (for example) `List.map myList crash` - you always have to apply it to a string right away, like `crash myCrashMessage`. (You can of course wrap it in a lambda, like `List.map myList \str -> crash str`)
- When `crash` gets run, it calls `roc_panic` passing the given string, and also a discriminant of 0 (indicating a panic due to the user running the `crash` function explicitly, as opposed to say a builtin panic due to arithmetic overflow).
- It's not necessary for version 1, but in the future we should give warnings for unreachable code due to `crash`. For example, `|> Result.withDefault (crash "uh oh!")` should warn that `Result.withDefault` will never get run; in fact, nothing in this entire pipeline will get run, because `crash "uh oh!"` will happen instead.

**Comment by skyqrose** [comment]
This exists now!
