### ISSUE TITLE
Is it late to reconsider the syntax of lambdas? 

### ISSUE THREAD

**Issue by danielo515** [roc-lang/roc#4404]
Hello, this project looks super impressive, it ticks almost all checks in my list of super nice things to have, except for easiness of typing 😁.
In a functional language, where you are going to  e writing functions all the time I think the ergonomics are very important.
Currently it requires at least 4 special characters, which are not commonly available in keyboard layouts other than US.
I know there is some history behind the syntax, but I don't think it's worth it for a reference.
In comparison, other space sensitive functional languages like F have a much more succinct syntax.

Regards

**Comment by Anton-4** [comment]
Hi @danielo515,
We still regularly discuss modifying syntax so it's not too late :)
Come join us on https://roc.zulipchat.com/, we usually discuss things like that there.
It would be great If you can post an example on zulip of some roc code with the lambda syntax modified to your liking.

**Comment by skyqrose** [comment]
I'm closing this old issue, but it's still not too late to consider syntax changes like this. We had a proposal for something this big just last week! If you want to revive this topic, or any other proposals, the best place is on zulip, though opening a new GitHub issue is also always welcome.
