### ISSUE TITLE
`getting_started/windows.md` obsolete

### ISSUE THREAD

**Issue by C-BJ** [roc-lang/roc#4418]
The issue that prevents the installation of Roc on windows seems to have been closed.

**Comment by Anton-4** [comment]
@folkertdev could you update `getting_started/windows.md` with remaining issues for windows?

**Comment by folkertdev** [comment]
you mean remaining limitations when using roc on a windows machine? I think the advise should still be to not use windows right now, the surgical linker works for hello world, but the more complex platforms (e.g. `cli`) still have linker issues (and possibly other problems) today
