### ISSUE TITLE
Don't make shadowing a runtime error

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4425]
When shadowing happens (including [rebinding in the same scope](http://blog.plataformatec.com.br/2016/01/comparing-elixir-and-erlang-variables/)) we should still report it as a warning but instead of generating a runtime error, we should override the current value in `Scope` and continue. This will enable more potentially useful workflows, and also make things a lot better for the repl. (The argument for making it be a warning and not an error is that although shadowing can actually break behavior like `expect`'s printing of current variables, it won't ever crash your program) 

We would need to make sure that cases like mutual recursion are still handled reasonably in some way. It's not immediately clear what this should compile to...

```elm
x = \{} -> y {}
y = \{} -> x {}
y = \{} -> {a: x {}}
```

...but we need to figure out what we want it to do!

**Comment by rtfeldman** [comment]
Currently shadowing triggers a mono panic on https://github.com/roc-lang/roc/blob/ae1a9e4dd6077b7db0b412ac20e5b5ec12c93c6a/crates/compiler/mono/src/ir.rs#L2580

**Comment by skyqrose** [comment]
There's a much more recent plan for shadowing (the `var` keyword). This is obsolete now.
