### ISSUE TITLE
Warning for out-of-order defs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4430]
Today, I can write this Roc code and the compiler will not complain:

```elm
x = y + 1

y = 3
```

The compiler will silently reorder these to have `y` appear before `x` because the implementation of `x` depends on `y`.

The compiler should still do this reordering, but it should give a warning telling the user to reorder them in the source code.

The reason for this is that Roc is an eagerly evaluated language, and this ordering can become observable (with potentially surprising results) under certain circumstances. For example, consider this code:

```elm
\arg1, arg2 ->
    x =
        if y + arg1 > 5 then
            expect arg1 == 2

            y * 3
        else
            0

    y = 
        if arg2 > 7 then
            expect arg2 == 9

            arg1 * arg2 * 100
        else
            0
```

Here, the `x` still depends on `y`, so the reordering will happen. However, now if both of these `expect`s fail, they actually print their output in a different order than how they appear in the source code! That would definitely be surprising (and would look like a bug in Roc), and would be a common beginner question the first time they saw something like that happen. Someone might stare at it for awhile trying to understand why their code was behaving that way if they didn't know in advance that Roc reorders defs.

Even more seriously, what if instead of `expect` it's a crash? Suppose the `arg1 * arg2 * 100` expression overflows and crashes. Someone might reasonably look at that code and assume (as would be the case in the vast majority of strictly-evaluated languages) that `x` did not contain a crash, because the program had successfully run past the `x = …` declaration and "made it" to the `y = …` declaration where the crash happened. This assumption would be wrong, of course; the code in `x` has not even run yet! Misleading evidence like this could lead to incorrect conclusions which derail and prolong debugging sessions.

Still, Roc's compiler is capable of reordering defs, and the order of defs should not affect whether a Roc program crashes (although it could impact *where* it crashes and the particular crash message), this should be a warning and not an error.

**Note:** None of this applies to defs of functions. Those can always go in any order, since the definition itself doesn't trigger any evaluation.

**Comment by skyqrose** [comment]
Superceded by https://github.com/roc-lang/roc/issues/5078, which is about erroring instead of warning.
