### ISSUE TITLE
test_mono tests fail on apple silicon mac

### ISSUE THREAD

**Issue by joshuawarner32** [roc-lang/roc#4435]
Recently I've noticed that when I'm running tests locally on my M1 mac, with a bunch of what look like re-numbering diffs. e.g.

```
---- specialize_closures stdout ----
diff --git a/crates/compiler/test_mono/generated/specialize_closures.txt b/crates/compiler/test_mono/generated/specialize_closures.txt
index 4dacbd022..844180ae1 100644
--- a/crates/compiler/test_mono/generated/specialize_closures.txt
+++ b/crates/compiler/test_mono/generated/specialize_closures.txt
@@ -1,14 +1,14 @@
 procedure Bool.2 ():
-    let Bool.12 : Int1 = true;
-    ret Bool.12;
+    let Bool.24 : Int1 = true;
+    ret Bool.24;

 procedure Num.19 (#Attr.2, #Attr.3):
-    let Num.258 : I64 = lowlevel NumAdd #Attr.2 #Attr.3;
-    ret Num.258;
+    let Num.257 : I64 = lowlevel NumAdd #Attr.2 #Attr.3;
+    ret Num.257;

 procedure Num.21 (#Attr.2, #Attr.3):
-    let Num.257 : I64 = lowlevel NumMul #Attr.2 #Attr.3;
-    ret Num.257;
+    let Num.256 : I64 = lowlevel NumMul #Attr.2 #Attr.3;
+    ret Num.256;
```

Here's the test report for test_mono:

```
test result: FAILED. 44 passed; 58 failed; 7 ignored; 0 measured; 0 filtered out; finished in 3.83s
```

Is this a known issue?

**Comment by Anton-4** [comment]
Is this with `cargo test` instead of `cargo test --release`?

**Comment by joshuawarner32** [comment]
Indeed, I was using `cargo test`. On my machine `cargo test --release` passes!

I find it very surprising that test results would depend on whether you're running in debug or release mode. That might make it hard to debug the tests! (just saying...)

If this is the expected status quo, what do you think about either (1) disabling these tests when in debug (non --release) mode, (2) creating a separate set of snapshots for debug mode, or (3) change something in these tests to make them always product the --release output, regardless of mode?

**Comment by ayazhafiz** [comment]
This has bene an issue for a while, we've talked about it on-and-off on Zulip. I think we should disable them in debug mode, or add a feature so that they consistently generate the same things in debug and release.

FWIW they pass on release only because with release we don't actually run them.

**Comment by joshuawarner32** [comment]
Hmm, what's the cause of the test failures in debug mode? Is that because of architecture differences (x86 vs arm)? Or OS differences (mac vs linux)? When I `git add` the changes that running `cargo test` generates, it starts passing again - which says to me that they are consistent on the same machine/config.

**Comment by ayazhafiz** [comment]
The problem has to do with the symbol names we generate in debug vs release
mode. In debug mode we carry much more information about what the
human-readable name of these symbols were, and generate more of them, than
we do in release mode. So if we want to reconcile the differences, we
should probably do so with conditional compilation behind a feature flag.

**Comment by joshuawarner32** [comment]
Hmm, I think the debug/release disparity is different from the failures I'm seeing in debug mode. When I modify the test code to run in release mode, I'm seeing diffs like this, which matches your description:

```
-procedure Bool.2 ():
-    let Bool.24 : Int1 = true;
-    ret Bool.24;
+procedure 5.2 ():
+    let 5.24 : Int1 = true;
+    ret 5.24;
```

That doesn't explain the re-numbering diffs when running tests in debug mode (see the original issue post for the diff).

**Comment by joshuawarner32** [comment]
Actually I'm seeing exactly the same diffs/failures (as in the original issue post) when running `test_mono` on my x86_64 linux machine. Do these tests pass in CI?

**Comment by ayazhafiz** [comment]
CI runs them only in release mode, which in fact does not check diffs at
all. So, the actual diffs, in either debug or release, are not checked in
CI.
