### ISSUE TITLE
REPL crash when naming something to existing named function

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4436]
To reproduce:

» foo = \_ -> 1
… bar = foo
… bar

This currently (as of 02a76bb8bd0235f64854c74a945cb7bad674ccfd) panics with:

> 'function symbol not in set', crates/compiler/mono/src/layout.rs:1390:9

The same bug is still reproducible after https://github.com/roc-lang/roc/pull/4419 using persisted defs:

<img width="1076" alt="Screen Shot 2022-10-30 at 4 02 42 AM" src="https://user-images.githubusercontent.com/1094080/198868724-f85dee26-4c2a-4d28-ba99-ef94756fda74.png">

**Comment by Ivo-Balbaert** [comment]
In my system (Ubuntu 22), this now gives the following error:

» foo = _ -> 1
… … bar = foo
… … bar

── UNKNOWN OPERATOR ────────────────────────────────────────────────────────────

This looks like an operator, but it's not one I recognize!

1│  app "app" provides [replOutput] to "./platform"
2│
3│  increment = \x -> x + 1
4│
5│  addXY = \x, y -> x + y
6│
7│  replOutput =
8│      foo = _ -> 1
                ^^

Looks like you are trying to define a function.

In roc, functions are always written as a lambda, like

    increment = \n -> n + 1

Using the correct parameter syntax, I get:

» foo = \_ -> 1
… … bar = foo
… … bar

── MISSING FINAL EXPRESSION ────────────────────────────────────────────────────
