### ISSUE TITLE
start on similar roc code searcher editor plugin

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4439]
Eventually, I want this to be a plugin that shows me code snippets of valid roc that are similar to the code that I am writing.
This is useful when you don't know the exact API of something but don't want to go digging into the documentation for your specific need. This is a slightly different spin on autocomplete that I'd like to try out.
A good starting point would be a roc cli program (using the cli platform) that can be given a string of incomplete roc code (max 5 lines) and an arbitrary number of roc files. The output would be the 3 most similar snippets (max 10 lines each). No fancy parsing of roc code should be done at this stage, simple string similarity will be good enough to get started.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
