### ISSUE TITLE
Parsing tuples

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4465]
After a bunch of iteration on Zulip, we've got a design for tuples!

Here are the parsing changes involved:

1. You can now write `(x, y)`, `(x, y, z)`, etc. as an `Expr`. There can be as many commas as you like, but for it to be a tuple, there must always be at least one comma. There is no`()`.
2. You can also write them in the same way for `Pattern`s.
3. You can write them the same way in type annotations, but - just like with records and tag unions - you can also have an "ext var" type variable right after the closing paren. So for example, `(Str, Str)`, `(Str, Str)*`, `(Str, Str)a`, and `(Str, Str)(Str, Str)` should all be valid syntactically.
4. You can access tuples' fields the same way you can record fields, except instead of like `expr.foo`, `expr.bar`, it's `expr.0`, `expr.1` etc. So a dot followed by an integer instead of a letter. This is "tuple access."
5. You can write `.1`, `.2,` etc. and it's a "tuple accessor" function similar to how `.x` and `.y` are "record field accessor" functions. So `0.1` is a number, but `.1` is a function. (This should be easy to give a nice error message around if people mistakenly try to write `.1` as a number, so any confusion should be very short-lived.)

**Comment by joshuawarner32** [comment]
Makes sense!

QQ: For (3), what does `(Str, Str)(Str, Str)` mean? I assume that would be equivalent to`(Str, Str, Str, Str)`, except in a context where you're refining the type of something like `(Str, Str)a`, where `a = (Str, Str)`; is that right?

**Comment by rtfeldman** [comment]
Yeah exactly! 👍

**Comment by joshuawarner32** [comment]
Here's an interesting ambiguity / inconsistency:
* `(Str, Str)a` represents a tuple that has at least two fields and maybe other fields (as specified by a)
* Similarly, we have `(Str, Str)` that has exactly two fields
* A corresponding value would be `("a", "b")` - all good so far.
* 1-element tuple _values_ don't exist, and neither do 0-element ones
* However, should _types_ for those exist, like `(Str)a` - a tuple with at least one string field, and maybe others?
* Or `()a`, representing a tuple has some unknown fields

`(Str)a` seems _probably_ useful, but it already breaks symmetry with single-element tuples (which don't exist). But what about `()a`? It feels weird not to allow that as a degenerate case, but it also feels weird to have that, from a symmetry perspective.

**Comment by joshuawarner32** [comment]
Whoops forgot to mark this one done
