### ISSUE TITLE
Mobile-friendly tutorial layout

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4522]
Currently /tutorial does not have a mobile-friendly layout. We should give it one!

**Comment by lukewilliamboswell** [comment]
![Screenshot_20221129_091744](https://user-images.githubusercontent.com/2679227/204392711-ab63144f-8f2c-4298-afff-19aa9eb9920d.jpg)
Minor comment, it wasnt clear to me that the contents label was a button that I needed to click to open.
