### ISSUE TITLE
examples/env.roc causes `roc dev` to hang, but other `roc` subcommands all work fine

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4600]
This is very strange! To reproduce, run:

```
cargo run -- dev examples/cli/env.roc
```

This hangs. However, `run` works fine, and running `build` instead of `dev` successfully produces a binary executable which also works as expected. Also, `roc check` successfully reports no errors and no warnings. `roc test` successfully reports no expectations found.

It appears to be only `dev` that has this problem!

**Comment by bhansconnect** [comment]
I think this is the same issue as #4622.

**Comment by ayazhafiz** [comment]
#4643 fixes this, closing in favor of tracking in 4622.
