### ISSUE TITLE
Support `expect` and `dbg` in `roc run`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4615]

**Comment by sporto** [comment]
While experimenting I'm using `roc run` a lot, because `roc dev` requires me to remove unused code. I don't really want to remove unused code while I'm exploring ideas. I can't use `dbg` in this case.

**Comment by skyqrose** [comment]
There have been lots of discussions recently about what the cli options should do and when to include expect and dbg. I don't remember the latest state, or where those are, but I know that there's more up to date work being planned elsewhere, so I'm closing this issue.
