### ISSUE TITLE
Tutorial missing Opaque Types

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4634]
The tutorial doesn't have an explanation of Opaque Types. There is a good description in the [Roc for Elm Programmers](https://github.com/roc-lang/roc/blob/main/roc-for-elm-programmers.md#opaque-types).

**Comment by lukewilliamboswell** [comment]
I've drafted content in this [draft gist](https://gist.github.com/lukewilliamboswell/0ce64b27d1f46461e2d094c04b7dcc37). Intention is to PR if/when build process is ready in CI.

**Comment by Anton-4** [comment]
The build process was already good in #4771, deployment will happen nightly. Let me know if you do happen to encounter any problems.
