### ISSUE TITLE
Mac OS 11 : Cannot find pf import from Github

### ISSUE THREAD

**Issue by sporto** [roc-lang/roc#4655]
I tried this form the tutorial:

```
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf
```

Works fine in LInux. 

But in Mac OS 11 I get
```
── FILE NOT FOUND ──────────────────────────────────────────────── UNKNOWN.roc ─

I am looking for this file, but it's not there:

    https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br

Is the file supposed to be there? Maybe there is a typo in the file
name?⏎
```

I downloaded the latest nighlty release I found for Mac OS 11

Thanks

**Comment by Anton-4** [comment]
Hi @sporto, we encountered a test failure for macos x86_64 that we have not yet been able to resolve. So macos x86_64 releases have been lagging behind. I should have a 2018 mac mini in my possession soon to resolve this.

As a workaround; you can clone the [basic-cli repo](https://github.com/roc-lang/basic-cli) locally and use a path instead of a URL at `pf:`.

**Comment by Anton-4** [comment]
We can do builds on the github macos 86_64 server but I prefer not to do a build if there are [test failures](https://github.com/roc-lang/roc/actions/runs/3600354340/jobs/6064922634).

**Comment by oliverhr** [comment]
@Anton-4 workaround worked.

For the newbies like me, this is how we can use source code as package:
```
app "cli-tutorial"
    packages { pf: "basic-cli/src/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line "Hello, World!"
```

**Comment by lowderdev** [comment]
`basic-cli` didn't seem to work for me, I think because I annotated my functions maybe? Got errors about not being able to find `Program` and `ExitCode` which indeed don't seem to appear in `basic-cli`.

But providing a path to the `examples/cli/cli-program/main.roc` in the nightly release examples worked:

```roc
app "day1"
    packages { pf: "../roc_nightly-macos_11_x86_64-2022-11-23-0ac6fe7/examples/cli/cli-platform/main.roc" }
    imports [
        pf.File,
        pf.Path,
        pf.Program.{ ExitCode, Program },
        pf.Stderr,
        pf.Stdout,
        pf.Task.{ Task },
    ]
    provides [main] to pf

main : Program
main = Program.noArgs mainTask

mainTask : Task ExitCode [] [Read [File], Write [Stderr, Stdout]]
mainTask =
```

**Comment by Anton-4** [comment]
A new macos x86_64 release is available [here](https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_11_x86_64-2022-12-07-224dffec0.tar.gz). I have not been able to test it on macos 12 but I do expect it to work.

For the `packages { pf:` you'll now have to use this URL: "https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br". I'll update the tutorial to use this URL on Friday.

If someone can confirm the new release works on macos 12, we can close this issue :)

**Comment by lukewilliamboswell** [comment]
Works for me. I'm on macOS 12.6 with M2 silicon
```sh
Lukes-MacBook-Air:euler luke$ ./roc p0.roc 
Downloading https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br
    into /Users/luke/.cache/roc/packages

Hello World!
```

**Comment by Anton-4** [comment]
Oh sorry, I meant macos 12 on a x86_64 device. I've edited my earlier message to clarify.

**Comment by oliverhr** [comment]
Hi @Anton-4 same error tested on macOS Monterey
```
$ roc version
roc nightly pre-release, built from commit 0ac6fe7 on Wed Nov 23 10:05:18 UTC 2022

$ uname
Darwin

$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217

$ cat main.roc
app "cli-tutorial"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line "Hello, World!"

$ roc dev
── FILE NOT FOUND ──────────────────────────────────────────────── UNKNOWN.roc ─

I am looking for this file, but it's not there:

    https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br

Is the file supposed to be there? Maybe there is a typo in the file
name?%
```

**Comment by sporto** [comment]
I just go the latest build for MacOS 11
It was working for a while, but odly I started seeing:

```
I was expecting this file to exist:

    /Users/Sebastian/.cache/roc/packages/github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk/macos-x86_64.o

However, it was not there!
```

I tried deleting the `.cache/roc` dir. After that it downloads the package again and shows the same error.

**Comment by sporto** [comment]
I just downloaded the latest MacOS 11 build. This seems to be working fine.

**Comment by Anton-4** [comment]
@oliverhr you're still using the old roc release. Can you try the [new one](https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_11_x86_64-2022-12-07-224dffec0.tar.gz)?

I should have grouped my "things to change" better :)

**Comment by oliverhr** [comment]
I did not test with the version you pointed `https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_11_x86_64-2022-12-07-224dffec0.tar.gz` sinces I'm running a v12 of macOS.

But I just tested with [roc_nightly-macos_x86_64-2022-12-09-7d8b9b232](https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_x86_64-2022-12-09-7d8b9b232.tar.gz) and worked as expected

```
# OS info
Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217

# roc version
roc nightly pre-release, built from commit 7d8b9b232 on Fri Dec  9 13:37:55 UTC 2022
```

**Comment by Anton-4** [comment]
Awesome :)
