### ISSUE TITLE
`roc check` hangs when trying to reference nonexistant package qualifier

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4675]
To reproduce, modify `examples/helloWorld.roc` to import from a package qualifier that doesn't exist (in this case, `foo`):

```
    imports [pf.Stdout, foo.Bar]
```

This causes `roc check examples/helloWorld.roc` to hang! Instead, it should report an error of an unrecognized

**Comment by JRI98** [comment]
No longer reproduces
