### ISSUE TITLE
Compiler issue | Advent of Code 2022

### ISSUE THREAD

**Issue by pkarthick** [roc-lang/roc#4676]
[part2.roc.txt](https://github.com/roc-lang/roc/files/10148577/part2.roc.txt)

I have attached a roc source file (appended with .txt extension) attempting to solve Day 3 Part 2 of Advent of Code 2022.

While running this file, got the below error:
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'ambient functions don't unify', /Users/m1ci/actions-runner2/_work/roc/roc/crates/compiler/unify/src/unify.rs:247:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This was run on Mac OS 13. I saw a note that this OS version was not supported. So, mentioning it here.

**Comment by ayazhafiz** [comment]
I've confirmed that #4688 should resolve this!
