### ISSUE TITLE
dbg shows incorrect output

### ISSUE THREAD

**Issue by shritesh** [roc-lang/roc#4677]
Update: turns out `dbg` is broken. See: https://github.com/roc-lang/roc/issues/4677#issuecomment-1336486960

macOS: 13.0.1 (22A400)
CPU: Apple M1 Max
Roc release: roc_nightly-macos_12_apple_silicon-2022-12-04-9becbed

I was solving AoC day 4 and got incorrect results that didn't make sense. I have reduced it to the incorrect result from Str.toU32.

```roc
app "advent-01"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

example =
    """
    2-4,6-8
    2-3,4-5
    5-7,7-9
    2-8,3-7
    6-6,4-6
    2-6,4-8
    """

main =
    dbg
        parse example

    Stdout.write ""

parse = \inputStr ->
    line <- Str.replaceEach inputStr "," "-" |> unwrap |> Str.split "\n" |> List.map
    Str.split line "-" |> List.mapTry Str.toU32

unwrap = \result ->
    when result is
        Ok x -> x
        Err _ -> crash "invalid input"
```

Inside the `parse` function, If I remove the last `|> List.mapTry Str.toU32`, everything works as expected:
```
[04_miscompliation.roc 18:9] [["2", "4", "6", "8"], ["2", "3", "4", "5"], ["5", "7", "7", "9"], ["2", "8", "3", "7"], ["6", "6", "4", "6"], ["2", "6", "4", "8"]]
```

Putting that back in, I get this garbage:
```
[04_miscompliation.roc 18:9] [Ok [4, 8, 2863311530, 2863311530], Ok [4, 0, 4, 0], Ok [4, 0, 4, 0], Ok [4, 0, 4, 0], Ok [4, 0, 4, 0], Ok [4, 0, 4, 0]]
```

**Comment by shritesh** [comment]
Even simpler repro:
```main =
    dbg
        parse "2-4-6-8"

    Stdout.write ""

parse = \inputStr ->
    Str.split inputStr "-" |> List.mapTry Str.toU32
```

**Comment by bhansconnect** [comment]
Is this an issue with `Str.toU32` or an issue with `dbg`. I have noticed a number of times that `dbg` has given me garbage print outs, but if I were to use the value or convert it to a string and print it with `Stdout.line`, the result is correct.

**Comment by shritesh** [comment]
yup that was it!

**Comment by bhansconnect** [comment]
Yeah, i think debug may somehow be reading the wrong memory or parsing the bytes wrong. Though if it was just parsing the bytes wrong, i think it should get the same results over many runs. So i bet it is reading wrong memory in some cases. Seems to happen with structs. I think lists of integers that aren't in structs work consistently.

**Comment by Ivo-Balbaert** [comment]
When trying to follow the tutorial (https://www.roc-lang.org/tutorial#removing-elements-from-a-list) and using dbg, I also get wrong output:

```coffee
app "lists"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.1/97mY3sUwo433-pcnEQUlMhn-sWiIf_J9bPhcAFZoqY4.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
  b5 = List.dropAt [ "R", "O", "C" ] 1  # should be ["R", "C"]
  dbg b5   # [lists_dbg_errors.roc 8:7] ["H", "C"]
  b5B = List.dropAt ["Sam", "Lee", "Ari"] 1 # should be ["Sam", "Ari"]
  dbg b5B  # [lists_dbg_errors.roc 10:7] ["H�G", "Ari"]
  b6 = List.keepIf [ 1, 2, 3, 4, 5 ] Num.isEven # should be [ 2, 4 ]
  dbg b6   # [lists_dbg_errors.roc 12:7] [139795183950408, 4]
  b7 = List.dropIf [ 1, 2, 3, 4, 5 ] Num.isEven # should be [ 1, 3, 5 ]
  dbg b7   # [lists_dbg_errors.roc 14:7] [139795183950408, 3, 5]
  Stdout.line "end"
```

**dbg always reports the first list value incorrectly, and the value reported changes on every run of the program
the same problem occurs with other List functions, like range or walk**

**Comment by Ivo-Balbaert** [comment]
All my problems with dbg are solved with a recent build (on WSL-Ubuntu 22). The above program correctly gives:

$ roc lists_dbg_errors.roc
[lists_dbg_errors.roc 8:7] ["R", "C"]
[lists_dbg_errors.roc 10:7] ["Sam", "Ari"]
[lists_dbg_errors.roc 12:7] [2, 4]
[lists_dbg_errors.roc 14:7] [1, 3, 5]
end

Also the original code reported by @shritesh works with output:
$ roc advent01.roc
[advent01.roc 18:9] [Ok [2, 4, 6, 8], Ok [2, 3, 4, 5], Ok [5, 7, 7, 9], Ok [2, 8, 3, 7], Ok [6, 6, 4, 6], Ok [2, 6, 4, 8]]

Perhaps this issue can be closed? @shritesh @bhansconnect

**Comment by Anton-4** [comment]
Sounds good, thanks for checking @Ivo-Balbaert!
