### ISSUE TITLE
Renable broken wasm `gen_dict` tests

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4679]
I had to disable 2 of the `gen_dict` tests on wasm.

`gen_dict::dict_empty_remove` is failing on the llvm wasm backend. (really confused as to why, it worked when I compiled a wasm app with the same code)

`gen_dict::small_str_keys` is failing on the dev wasm backend. It produces `[trap] out of bounds memory access`. Given this passes on the llvm wasm backend, I would assume it is a dev wasm backend issue and not a dictionary code issue.

As an extra note, a number of the dictionary tests only run with the llvm backend. I am pretty sure that more of them could be enable on the wasm backend if wanted.

**Comment by brian-carroll** [comment]
> As an extra note, a number of the dictionary tests only run with the llvm backend. I am pretty sure that more of them could be enable on the wasm backend if wanted.

Yes, the main work on the Wasm backend was completed before we implemented Dict in Roc code. So they wouldn't have passed at the time, but now they should.

**Comment by brian-carroll** [comment]
Ok it looks like a refcounting bug. I'll dig a bit further.
Valgrind isn't useful for Wasm, but Chrome devtools are very useful, and we have a test webpage in the repo at
`crates/compiler/test_gen/src/helpers/debug-wasm-test.html`

<img width="1728" alt="Screenshot 2023-01-23 at 23 16 49" src="https://user-images.githubusercontent.com/4647158/214173826-8533bc15-27c2-4079-a9e1-c857343992d1.png">
