### ISSUE TITLE
Fix the `TestAstar` cli test when run on wasm

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4680]
This issue might be fixed one #4679 is fixed. If not, we have to investigate and fix the the `TestAstar` benchmark for wasm. It currently compiles and runs, but it generates incorrect results.

The test case can be re-enabled my removing the block here: https://github.com/roc-lang/roc/blob/506deb0054ba12f51074e7d3592cb417d405f3f8/crates/cli/tests/cli_run.rs#L702

It is run with: `cargo test --features="wasm32-cli-run" -p roc_cli test_benchmarks::astar`

**Comment by brian-carroll** [comment]
This command now works, presumably due to #4683
