### ISSUE TITLE
Investigate List.concat builtins bug

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4697]
https://roc.zulipchat.com/#narrow/stream/358903-Advent-of-Code/topic/Day.205/near/314116723

**Comment by TAGraves** [comment]
Here's the smallest example I could figure out:
```
originalList = [["A", "B"], ["C"]]
f = List.get originalList 0 |> Result.withDefault []
s = List.get originalList 1 |> Result.withDefault []
{others} = List.split f 0
new = List.concat s others
List.set originalList 1 new
```

This evaluates to
```
[["A", "B"], ["C", "A", "A"]] : List (List Str)
```

instead of
```
[["A", "B"], ["C", "A", "B"]] : List (List Str)
```

Notably, if you just stop at `List.concat s others`, it evaluates to the correct `["C", "A", "B"]`, so I don't think this is just a List.concat bug.

**Comment by ayazhafiz** [comment]
`{others} = List.split f 0` appears to be important. If you instead write that line as `others = f` the runtime value is correct.

**Comment by ayazhafiz** [comment]
@folkertdev not sure if you've already figured this out, but this definitely seems to be a refcounting issue with the struct due to `List.split`. We have the following slice of IR

```
let `#UserApp.10` : {List U8, List U8} = CallByName `List.split` `#UserApp.f` `#UserApp.11`;
let `#UserApp.others` : List U8 = StructAtIndex 1 `#UserApp.10`;
inc `#UserApp.others`;
dec `#UserApp.10`;
let `#UserApp.new` : List U8 = CallByName `List.concat` `#UserApp.s` `#UserApp.others`;
```

If I turn off the recursive def for `UserApp.10` the program runs as expected. Not sure what's going on here, since the instructions themselves seem fine.. and `others` should be unique after this. Maybe it's a problem with `others` being seen as unique after this?

**Comment by ayazhafiz** [comment]
🙃 https://github.com/roc-lang/roc/blob/c8a335cd0be4358606337b8612347b973502924d/crates/compiler/builtins/bitcode/src/list.zig#L773 should use `copyBackwards` instead of `copy`.
