### ISSUE TITLE
List.range can introduce overflows/underflows

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4726]
## CRASHES
```elm
f : Nat -> Nat
f = \c ->
    List.range {start : At c, end : At 0}
    |> List.map \_ -> 1
    |> List.sum

expect f 2 == 3
```

## PASSES
```elm
f : Nat -> Nat
f = \_ ->
    List.range {start : At 2, end : At 0}
    |> List.map \_ -> 1
    |> List.sum

expect f 2 == 3
```

**Comment by lukewilliamboswell** [comment]
Also, below. It appears to be something type related.

```elixir
f : Nat -> List Nat # CRASHES WITH THIS TYPE DEFINITION, PASSES WITHOUT
f = \c -> List.range {start : At c, end : At 0}

expect f 2 == [2, 1, 0]
```

**Comment by ayazhafiz** [comment]
This is a bug in the range implementation. 

https://github.com/roc-lang/roc/blob/662eb5895eab36af4550a2c00d2bf089f0ef9340/crates/compiler/builtins/roc/List.roc#L693-L702

This code will decrement until `i` passed to `isComplete` is below `0` in this case, but of course that cannot happen and leads to overflow.

**Comment by folkertdev** [comment]
fixed by https://github.com/roc-lang/roc/pull/5076
