### ISSUE TITLE
remove mentions of `Num.maxNat`

### ISSUE THREAD

**Issue by shritesh** [roc-lang/roc#4746]
The docs mention `Num.maxNat` but it doesn't exist. 
https://github.com/roc-lang/roc/blob/662eb5895eab36af4550a2c00d2bf089f0ef9340/crates/compiler/builtins/roc/Num.roc#L1229

**Comment by timotree3** [comment]
Partially addressed in #6209, although there are still [occurrences](https://github.com/search?q=repo%3Aroc-lang%2Froc+maxnat&type=code) in Str.roc and List.roc

**Comment by gmlewis** [comment]
@lukewilliamboswell - could you please close this issue if it is no longer needed?
