### ISSUE TITLE
`dbg` terminates the program after many prints

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4753]
On both my linux machine and my M1 mac, this is reproducible. On the M1, the code below prints 253 times before exiting. On my linux machine, it prints 1020 times.

Essentially after a significant number of `dbg` prints due to looping, the program just exits. Interestingly, it exits successfully.

Simple repro:
```
app "helloWorld"
    packages { pf: "cli/cli-platform/main.roc" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    List.range {start: At 1, end: Length 5000}
        |> List.map \data ->
            dbg data
            Num.toStr data
        |> Str.joinWith ", "
        |> Stdout.line 
```

**Comment by bhansconnect** [comment]
Extra note: `--release` and `--optimize` do not seem to change the number of prints before exiting.

**Comment by ayazhafiz** [comment]
For me, the child dies due to SIGSEGV on M1 after 253 prints.

**Comment by bhansconnect** [comment]
Interesting. Does that mean you can use lldb and get a real error/line of code failure from this? On my machine, it just succeeds.

**Comment by ayazhafiz** [comment]
No because lldb hates fork/execve on M1 ):

to clarify, the forked child (aka the actual roc app) SIGSEGV's. But the parent process (the compiler, which interprets the dbgs) exits with 0 after SIGCHLD

**Comment by folkertdev** [comment]
@ayazhafiz I just saw this in the valgrind readme

> Important!  Do not move the valgrind installation into a place
> different from that specified by --prefix at build time.  This will
> cause things to break in subtle ways, mostly when Valgrind handles
> fork/exec calls.

maybe this is relevant for the problems you're seeing? (long shot but lldb may have similar issues and maybe gets moved?)
