### ISSUE TITLE
Defining a function to access record field crashed repl  (going through the tutorial)

### ISSUE THREAD

**Issue by hastiin-manuelito** [roc-lang/roc#4791]
I did not try to test anything more than this. The repl said it is likely a bug so I just submitted it.

The offending code:
`return = .foo`

The `RUST_BACKTRACE=1` output:
`An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'no lambda set found for (`16.IdentId(1)`, []): LambdaSet {
    set: [
        ( 16.2, []),
    ],
    representation: Interned(
        0,
        PhantomData,
    ),
}', crates/compiler/mono/src/layout.rs:1411:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: roc_mono::layout::LambdaSet::find_lambda_name
   3: roc_mono::ir::find_lambda_name
   4: roc_mono::ir::specialize_symbol
   5: roc_mono::ir::with_hole
   6: roc_mono::ir::from_can
   7: roc_mono::ir::from_can_let
   8: roc_mono::ir::from_can
   9: roc_mono::ir::specialize_variable
  10: roc_mono::ir::specialize_external_help
  11: roc_mono::ir::specialize_all
  12: roc_load_internal::file::run_task
  13: roc_load_internal::file::load_single_threaded
  14: roc_load_internal::file::load
  15: roc_load::load_and_monomorphize_from_str
  16: roc_repl_cli::repl_state::ReplState::eval_and_format
  17: roc_repl_cli::repl_state::ReplState::step
  18: roc_repl_cli::main
  19: roc::main`

**Comment by ayazhafiz** [comment]
Fixed by #4819
