### ISSUE TITLE
`repl_expect` unable to find location of error

### ISSUE THREAD

**Issue by Josh-cannot-code** [roc-lang/roc#4799]
When a repl expectation fails, the test runner is unable to find the source file of the failed assertion. This is likely due to the path being relative instead of absolute. Hard-coding an absolute path fixes the problem.

https://github.com/roc-lang/roc/blob/4022b44ff92883a7eeab304706b1f1487b39636e/crates/repl_expect/src/run.rs#L260-L267

**Error:** ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/user/roc/crates/repl_expect/src/run.rs:264:52```

## Steps to reproduce
1. Edit one of the expect assertions in `crates/compiler/builtins/roc/List.roc` so it should fail
2. Run `cargo run --locked --release -- test crates/compiler/builtins/roc/Str.roc`

## To see the correct error
Do the steps to reproduce then replace line 262 of `crates/repl_expect/src/run.rs` with 
```rust
let path = format!("crates/compiler/builtins/roc{}", &data.path.display());
```
 This should print the correct error message when step 2 is run again.

**Comment by folkertdev** [comment]
hmm, I cannot reproduce this error any more 

```
── EXPECT FAILED ──────────────────────── crates/compiler/builtins/roc/Str.roc ─

This expectation failed:

803│  expect Bool.false
      ^^^^^^^^^^^^^^^^^



1 failed and 21 passed in 379 ms.
```

so it seems to have fixed itself? (please re-open if I'm missing something)
