### ISSUE TITLE
[Virtual DOM] Investigate lambda set generalization when ambient function is not generalized

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4806]
https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/casual.20conversation/near/317764158
```   
is main broken? I'm hitting this
     Running `target/debug/roc check examples/virtual-dom-wip/example-client.roc`
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `12479`,
 right: `12479`: lambda set cloned but its ambient function wasn't?', crates/compiler/solve/src/solve.rs:4178:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ayazhafiz** [comment]
Hm, seems to work on main now.

0cf9ba647c9d26c1296ce705ac7609fc775b59ef is the last time this was busted. So I suspect https://github.com/roc-lang/roc/pull/4805 moved something around here.

@brian-carroll if you have a chance could you please try to minimize the virtual DOM program from 0cf9ba647c9d26c1296ce705ac7609fc775b59ef to reproduce this bug? It's only present in debug builds. I think if we can find a minimal example it will also cover the other lambda set bug you saw in the PR.

**Comment by ayazhafiz** [comment]
https://github.com/roc-lang/roc/pull/4805#discussion_r1057275424 also needs a minimal example. It manifests itself as an empty lambda set in mono but I suspect the underlying causes are the same.

**Comment by brian-carroll** [comment]
@ayazhafiz yep, I should be able to take a look in the next few days.

**Comment by brian-carroll** [comment]
This is as far as I was able to take it! Anything I change seems to get rid of the assertion.

```coffee
interface Html.Internal
    exposes [
        Html,
        initServerApp,
        initClientApp,
    ]
    imports []

Action state : [Action state]

Html state : [
    Element (state -> Action state) (Html state),
]

RenderedHtml : [
    RenderedNone,
]

translateStatic : Html state -> Html *

initServerApp : {} -> Html []
initServerApp = \{} ->
    translateStatic (Element [] [])

initClientApp : {} -> { thing : RenderedHtml }
initClientApp = \{} ->
    indexNodes { thing: RenderedNone } (Element [] [])

indexNodes : { thing : RenderedHtml }, Html state -> { thing : RenderedHtml }
indexNodes = \{ thing }, unrendered ->
    List.walk [] { thing } indexNodes

```

**Comment by brian-carroll** [comment]
Here's the branch I used, in case it's useful for some reason https://github.com/roc-lang/roc/tree/virtual-dom-bug-repro

**Comment by ayazhafiz** [comment]
Relevant branch: virtual-dom-annotations

Pop ca364a19967210cfcf3f46c203c18fb293e57fdf for the relevant bit
