### ISSUE TITLE
Unfinished sentence on roc-lang.org

### ISSUE THREAD

**Issue by brian-carroll** [roc-lang/roc#4809]
<img width="918" alt="Screenshot 2022-12-26 at 15 15 26" src="https://user-images.githubusercontent.com/4647158/209562783-ee6f4a56-a670-48cd-ba24-33328e064554.png">

This sentence is unfinished:

> You can read more about the differences between Roc and languages that support memory-unsafe

https://www.roc-lang.org/

**Comment by lukewilliamboswell** [comment]
This has been fixed at some point. 🎉 

<img width="710" alt="Screenshot 2023-08-09 at 21 35 34" src="https://github.com/roc-lang/roc/assets/2679227/dc965a0d-d194-47f2-958f-805fff7041e9">
