### ISSUE TITLE
Parser is broken on Linux

### ISSUE THREAD

**Issue by shritesh** [roc-lang/roc#4821]
[My project](https://github.com/shritesh/raytrace.roc/tree/ead45fc0f0f2536062f313c78bb626bc1d0e32fe) parses and runs without any problems in the latest nightly on a M1 Max running MacOS 13.1. But on Linux  x64, same nightly version, I get two different parse errors across multiple invocations.

```
shritesh@pc (main) [1] % roc check                                                                   ~/src/raytrace.roc
── NOT END OF FILE ─────────────────────────────────────────────────── RNG.roc ─

I expected to reach the end of the file, but got stuck here:

23│      newRng, u32Value <- u32 rng
               ^%                                                                                                       
shritesh@pc (main) [1] % roc check                                                                   ~/src/raytrace.roc
── MISSING FINAL EXPRESSION ──────────────────────────────────────── World.roc ─

I am partway through parsing a definition's final expression, but I
got stuck here:

 9│      final =
10│          state, sphere <- List.walk world { closestSoFar: max, recAndMat: Err NoHit }
                  ^

This definition is missing a final expression. A nested definition
must be followed by either another definition, or an expression

    x = 4
    y = 2

    x + y%                                                                                                              
```

**Comment by folkertdev** [comment]
specifically multi-param backpassing seems to be broken within a def (on linux, but the OS should not matter)

```
main = 
    arg1, arg2 <- f {}
    "Roc <3 Zig!\n"
```

we have tests for it within an expression, but because of tuples we cannot force the backpassing to be parsed in that way. @joshuawarner32  can you reproduce this? It would be really odd if it were something linux-specific. I don't think the parser considers the OS at all.

**Comment by shritesh** [comment]
I updated to the latest nightly on MacOS and it exhibits the same error as Linux now. The previous roc nightly that worked fine on MacOS was `roc nightly pre-release, built from commit 174b37e on Wed Dec 21 09:22:31 UTC 2022`

**Comment by joshuawarner32** [comment]
I've definitely been changing things in this area, very possible I broke this! Looking now.
