### ISSUE TITLE
Unexpected output in browser REPL when displaying records

### ISSUE THREAD

**Issue by giacomocavalieri** [roc-lang/roc#4835]
## Steps to reproduce
- open the [web REPL](https://www.roc-lang.org/repl)
- type the record `{a: "", b: 0}` and press Enter
## Output
```
» {a: "", b: 0}
{ a: "", b: -9223372036854775808 } : { a : Str, b : Num * }
```
I guess it may be a bug in the display of the record since accessing its fields works as one would expect:
```
» {a: "", b: 0}.a
"" : Str

» {a: "", b: 0}.b
0 : Num *
```

**Comment by folkertdev** [comment]
this works now 

```
» {a: "", b: 0}

{ a: "", b: 0 } : { a : Str, b : Num * }
```
