### ISSUE TITLE
Equal sign as key = value separator in records

### ISSUE THREAD

**Issue by kuchta** [roc-lang/roc#4840]
I've come across this in FAQ:

> : instead of = for record field definitions (e.g. { foo: bar } where Elm syntax would be { foo = bar }): I like = being reserved for definitions, and : is the most popular alternative.

And since I understand you want to make different signs mean different things, in practice this isn't very feasible if you don't want to invent new conventions, as you probably don't since colon also means different things in different contexts (records vs. type and type aliases) and that difference is IMHO semantically much bigger than with equal sign in records vs. definitions and using the same sign for records and definitions have that advantage, that you can easily refactor records to definitons and vice versa which I do from time to time...

Another advantage would be that it would be possible to use quite consistent syntax for explicit inline type AND value in records and definitions and ideally also in function signatures which I like more than those "out-of-band" signatures:
```
{ key : type = value }
```
and
```
val : type = value
```
and with functions
```
fullName : Str, Str -> Str = \firstName, lastName ->
    "\(firstName) \(lastName)"
```
or
```
fullName : \firstName: Str, lastName: Str -> Str =
    "\(firstName) \(lastName)"
```
Since record fields AFAIK don't currently support explicit typing, if we define definitons as `def : [type] = val` where type is optional, we could even end up with different sign for type inffered definitons that is quite common and that is `:=`

Anyway, thank you for your efforts, it looks like roc would be and interesting language 👍🙏🏻❤️

**Comment by bhansconnect** [comment]
This is likely better suited for a discussion on the [#ideas stream on zulip](https://roc.zulipchat.com/#narrow/stream/304641-ideas). It works better for community discussions than github issue. Could you cross post this?

**Comment by skyqrose** [comment]
I'm cleaning up old issues. I couldn't find the discussion on Zulip to link to, though I did find this earlier discussion on the same topic: https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/Record.20Syntax/near/290685159

If there's anything left to discuss on this it should go in Zulip. Closing this issue cuz there's nothing left to do in GitHub right now.
