### ISSUE TITLE
type checking not failing early enough

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4845]
A relatively simple but not fully minimized repro can be found here: https://gist.github.com/ni-ko-o-kin/3486d50bc5eac6d3e19f7d7da3fc8181#file-02-solution-part2-roc

It starts with the error:
```
This 2nd argument to map has an unexpected type:

93│          |> List.map calcScore
                         ^^^^^^^^^

This calcScore value is a:

    Instruction -> Points

But map needs its 2nd argument to be:

    Instruction -> Points
```

This error makes no sense, but if you remove the type definiion of `calcScore`, you get a more accurate error:
```
This 2nd argument to map has an unexpected type:

93│          |> List.map calcScore
                         ^^^^^^^^^

This calcScore value is a:

    [Instruction [Paper, Rock, Scissors] [Draw, Lose, Win]] ->
    Int Signed16

But map needs its 2nd argument to be:

    [Instruction [Paper, Rock, Scissors] [Draw, Lose, Paper, Rock,
    Scissors, Win]*] -> Int Signed16
```

Here is the definition of `Instruction` for reference:
```
Sign : [Rock, Paper, Scissors]
Outcome : [Lose, Draw, Win]
Instruction : [Instruction Sign Outcome]
```

It seems that the definition of `Outcome` has been expanded to include the definition of `Sign` as well.
Upon further investigate, the root cause is this definition:
```
    toOutcome : Str -> Sign
    toOutcome = \char ->
        when char is
            "X" -> Lose
            "Y" -> Draw
            "Z" -> Win
            _ -> Lose
```

It has a small typo: `Str -> Sign` should be `Str -> Outcome`. I am pretty sure this function shouldn't type check at all. I think the fact that we now always return open tag unions may have introduced a bug here that allowed this to type check. As such, the error propagated and caused the confusing error listed at the start of this issue.

**Comment by ni-ko-o-kin** [comment]
I could try to create a fully minimized example if that helps?

**Comment by ayazhafiz** [comment]
@ni-ko-o-kin if you have the chance that would be hugely helpful, thank you!

**Comment by ni-ko-o-kin** [comment]
I tried to remove as much unimportant code as possible: https://github.com/ni-ko-o-kin/advent-of-code-2022-roc/blob/main/roc-bug_01.roc

**Comment by ayazhafiz** [comment]
I think the root cause of this is the same as #4852
