### ISSUE TITLE
Unicode input wrong in docs

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4901]
In the docs on the website at https://www.roc-lang.org/builtins/Str,
unicode is said to be input as `\u{0x0A}`.

This is not the case in current Roc. Instead we would input `\u(0A)`.
We use parenthesis instead of squiggly brackets and don't add `0x` despite writing in hex.

Not sure if this is a case of docs being ahead of implementation or of docs not matching the final chosen implementation.

**Comment by lukewilliamboswell** [comment]
@bhansconnect I think this has been fixed, just not sure when. Can you confirm if you still see the original issue?

**Comment by bhansconnect** [comment]
Yeah, it's fixed
