### ISSUE TITLE
Tutorial has spaces before colons in records where they shouldn't be.

### ISSUE THREAD

**Issue by human154** [roc-lang/roc#4967]
The tutorial (as it appears at https://www.roc-lang.org/tutorial ) shows spaces before colons in multiple places, including in the following:

`returnFoo { foo : "hi!", bar : "blah" }`

also:

`{ x, y } = { x : 5, y : 10 }`

also:

```
original = { birds: 5, zebras : 2, iguanas : 7, goats : 1 }
fromScratch = { birds : 4, zebras : 2, iguanas : 3, goats : 1 }
fromOriginal = { original & birds : 4, iguanas : 3 }

```

... and multiple code snippets after that. (Perhaps this is an auto-formatting glitch?).

**Comment by human154** [comment]
@rtfeldman  is this related to https://github.com/roc-lang/roc/pull/4947  ?

**Comment by lukewilliamboswell** [comment]
This may have been me when I converted to markdown. I liked the spaces to be honest. But I can see that it isn't consistent and note that the formatter currently removes the spaces. So I have updated the tutorial (I hope I got all of them) at #5008.

**Comment by human154** [comment]
My understanding of the syntax here is based on what Richard Feldman wrote on Zulip:

"in Roc today:

always, what comes before = is a pattern
always, an identifier followed by a : is a record field declaration
always, an identifier followed by a blank space and then a : is a type declaration
"

**Comment by rtfeldman** [comment]
Oh, I see Luke's PR already did it - nice! 😄

**Comment by human154** [comment]
Yes and now I also have a pull request for more: #5042
