### ISSUE TITLE
roc format breaks with 'unstable formatting'

### ISSUE THREAD

**Issue by tankorsmash** [roc-lang/roc#4968]
```
$ roc --version
roc nightly pre-release, built from commit 2b429d3 on Di 17 Jan 2023 09:08:27 UTC
```

I was exploring the basic-cli argparsing, and reformatting the code. It seems like a minimal example that causes it to break would be something like 

```
app "AOC2022"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.2.0/8tCohJeXMBUnjo_zdMq0jSaqdYoCWJkWazBd4wa8cQU.tar.br" }
    imports [
        pf.Stdout,
        pf.Process,
        pf.Task.{ Task },
        pf.Arg,
    ]
    provides [main] to pf


age =
    (
        1
        )


main =
            Process.exit 1

```
, with the whitespace all messed up being a key element.

```
roc format main.roc
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Formatting bug; formatting is not stable. Reformatting the formatted file changed it again.

I wrote the result of formatting to this file for debugging purposes:
main.roc-format-unstable-1

I wrote the result of double-formatting here:
main.roc-format-unstable-2
```

Attached are the files:

[main.roc-format-unstable-1.txt](https://github.com/roc-lang/roc/files/10511068/main.roc-format-unstable-1.txt)
[main.roc-format-unstable-2.txt](https://github.com/roc-lang/roc/files/10511069/main.roc-format-unstable-2.txt)
[main.roc.txt](https://github.com/roc-lang/roc/files/10511070/main.roc.txt)

---

Changing the `age` bit to
 ```

age =
    ( 1)

``` 
no longer causes the crash

**Comment by JRI98** [comment]
No longer reproduces
