### ISSUE TITLE
use kebab-case for roc filenames and app names

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4986]
For example: `app "helloWorld"` should become `app "hello-world"`. The file name should be the same as the app name with '.roc' added of course

**Comment by lukewilliamboswell** [comment]
What is the scope of this task? Is this an automated fix or more like advise added to the tutorial?

**Comment by Anton-4** [comment]
Good question, I think we should handle this in roc format. So `roc format` should change `app "helloWorld"` to `app "hello-world"`. I don't know if it is acceptable for the formatter to change the file name as well, perhaps we should give a warning for that.

**Comment by lukewilliamboswell** [comment]
@Anton-4 I think this task has been overtaken by other changes. 

The name of the executable is now determined by the file name or using `--output`, and this will be removed in module params changes.

Propose we close this.
