### ISSUE TITLE
Error message is incorrect and unhelpful

### ISSUE THREAD

**Issue by Billzabob** [roc-lang/roc#5032]
I forgot to put a `Task.await` around my Task during backpassing and got the following error message:
```
── TOO FEW ARGS ─────────────────────────────────────── examples/calibrate.roc ─

The test function expects 1 argument, but it got only 1:

36│      _ <- test
              ^^^^

Roc does not allow functions to be partially applied. Use a closure to
make partial application explicit.
```
The type of `test` here is simply `Task {} []`.

**Comment by JRI98** [comment]
No longer relevant as backpassing is being deprecated https://github.com/roc-lang/roc/issues/6829
