### ISSUE TITLE
Roc crashes with `specialization var not derivable!: Underivable`

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5089]
The following crashes Roc. Adding a type annotation provides the compiler enough information to compile and run without any issues. 

Can we stop the compiler crashing and provide an Error message here? @ayazhafiz this may be something you are interested in?

```
luke@192-168-1-104 roc % roc test Json.roc
thread '<unnamed>' panicked at 'specialization var not derivable!: Underivable', crates/compiler/mono/src/ir.rs:5846:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```coffee
# Test json array decoding into integers
expect
    input = Str.toUtf8 "[1,2,3]"
    expected = [1,2,3]

    # actual : List U8 << RUNS WITH THIS ANNOTATION>>
    actual = Decode.fromBytes input fromUtf8 |> Result.withDefault []

    actual == expected
```

**Comment by ayazhafiz** [comment]
Yes this should infer the types correctly and not crash. I will put this on my backlog, but if anyone would like to pick it up please let me know. May take me some time to get to.
