### ISSUE TITLE
Roc repl auto indentation

### ISSUE THREAD

**Issue by swork1** [roc-lang/roc#5101]
I started going through some of the tutorial using "roc repl" and I'm curious if the repl is planning on having automatic indentation when creating functions. Example below

» test = \a -> (press enter after the ->)
… a (press enter - doesn't auto indent) -- compiler sad (error)

» test = \a -> (press enter after the ->)
…  a (press space, press enter) -- compiler happy

**Comment by lukewilliamboswell** [comment]
See [zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/roc.20repl.20auto.20indentation/near/340015774) for more information.

**Comment by swork1** [comment]
> See [zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/roc.20repl.20auto.20indentation/near/340015774) for more information.

I posted in zulip after researching a bit into rustyline
> "It seems RustyLine doesn't support indentation"
https://github.com/kkawakam/rustyline/issues/453
https://github.com/kkawakam/rustyline/pull/466
