### ISSUE TITLE
Copy Doc examples to clipboard 

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5137]
Discussion on [zulip](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/docs.20improvements/near/341707957).

Using JS create copy to clipboard on `<code>` elements. Prepend an empty header so that users can paste into a file and the example will run/test correctly.

**Comment by swork1** [comment]
I have started to work on this

**Comment by swork1** [comment]
@lukewilliamboswell this can be closed
