### ISSUE TITLE
Add `List.takeWhile` builtin function

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5138]
> We should totally promote this to a List.takeWhile builtin!
Add `Json.takeWhile` to the `List` builtins.

@rtfeldman how should we handle the `isEscapeSequence`? I assume we wouldn't want that in a `List` builtin. So I guess we need the predicate to handle variable lengths, so would `takeWhile: List a, (List a -> {taken: a, rest : a}) -> {taken: a, rest: a}` be ok?

```roc
takeWhile = \list, predicate ->
    helper = \{ taken, rest } ->
        when rest is
            [a, b, ..] ->
                if isEscapeSequence a b then
                    helper {
                        taken: taken |> List.append a |> List.append b,
                        rest: List.drop rest 2,
                    }
                else if predicate a then
                    helper {
                        taken: List.append taken a,
                        rest: List.dropFirst rest,
                    }
                else
                    { taken, rest }

            [a, ..] if predicate a ->
                helper {
                    taken: List.append taken a,
                    rest: List.dropFirst rest,
                }

            _ -> { taken, rest }

    helper { taken: [], rest: list }

isEscapeSequence : U8, U8 -> Bool
isEscapeSequence = \a, b ->
    when P a b is
        P '\\' 'b' -> Bool.true # Backspace
        P '\\' 'f' -> Bool.true # Form feed
        P '\\' 'n' -> Bool.true # Newline
        P '\\' 'r' -> Bool.true # Carriage return
        P '\\' 't' -> Bool.true # Tab
        P '\\' '"' -> Bool.true # Double quote
        P '\\' '\\' -> Bool.true # Backslash
        _ -> Bool.false

```

**Comment by ilyakooo0** [comment]
I would like to implement this as my first contribution. Could you please assign it to me?

I would appreciate a pointer to where the code should be placed.

**Comment by ilyakooo0** [comment]
We decided to not implement `takeWhile` as described in the Github issue, and instead decided to add a more traditional boolean-based `takeWhile`.

See this thread on Zulip for more info: https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/List.2EtakeWhile/near/351350051
