### ISSUE TITLE
Add Tuple language feature to the Tutorial

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5141]
@joshuawarner32 implemented Tuples language feature. It was discussed in this discussion on [tulip](https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/Implementing.20tuples/near/322661370).

## Details
- Tuples can hold many values of different types (is there a limit?)
- Tuples can use the `.` to access tuple value (does this have a special name? tuple accessor)
- Zero indexed
- Are there any other relevant details?

## Tests
[`crates/compiler/test_gen/src/gen_tuples.rs`](https://github.com/roc-lang/roc/blob/main/crates/compiler/test_gen/src/gen_tuples.rs)

## Example
```
tuple = ("One", 0xAB01, 15_000_000i64)

thirdItem = tuple.2

expect thirdItem == 15_000_000i64
```

**Comment by kunalznk** [comment]
can i work on this

**Comment by lukewilliamboswell** [comment]
@kunalznk that would be great! 👍 Let me know if you need a hand with anything. 😎

**Comment by kunalznk** [comment]
Okay I'll let yo know ✌️
