### ISSUE TITLE
Roc crashes in decision tree and rendering pointer

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5176]
Two different crashes, similar code. May be related. I have been playing around with this for a while and haven't figured out why it isn't working or what is specifically causing these issues.  

```
% roc test Blah.roc
thread '<unnamed>' panicked at 'explicit panic', crates/compiler/mono/src/decision_tree.rs:273:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
% roc test Blah.roc
thread 'main' panicked at 'not yet implemented: TODO add support for rendering pointer to (Alias(`4.IdentId(88)`, AliasVariables { variables_start: 2436, all_variables_len: 0, lambda_set_variables_len: 0, type_variables_len: 0 }, 3233, Structural), Builtin(Decimal)) in the REPL', /Users/luke/Documents/GitHub/roc/crates/repl_eval/src/eval.rs:884:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I copied two different files in the gist below, should be able to just run with `roc test` etc

[Code Gist](https://gist.github.com/lukewilliamboswell/5a90af3b3102dc1621505e409d4260be)

**Comment by lukewilliamboswell** [comment]
My theories from playing around with this and attempts to minimise;
- Using Tuples seems to break things
- We don't support pattern matching on constants like `0` e.g. `(Start, '0') -> Continue (Zero 1)` doesn't work.
- The expectation below will blow up when the actual result is an `Err` but it is trying to compare it to the `Ok 0.0dec` I think.

```
expect
    actual = "0.0" |> Str.toUtf8 |> decodeDec
    expected = {result : Ok 0.0dec, rest : []}
    
    actual == expected
```

**Comment by ayazhafiz** [comment]
The second issue should be fixed by https://github.com/roc-lang/roc/pull/5171

**Comment by ayazhafiz** [comment]
minimal repro:


```
interface A exposes [] imports []

go : U8 -> Nat
go = \byte ->
    when byte is
        '.' if Bool.true -> 1
        b if Bool.true -> 2
        _ -> 3

expect
  go '.' == 9
```
