### ISSUE TITLE
thread '<unnamed>' panicked at 'cannot find `str.zig`. Check the source code in find_zig_str_path()  .. in nix-darwin nixos nix

### ISSUE THREAD

**Issue by PlumpMath** [roc-lang/roc#5183]
Hello
-------------- MacOS (Intel nix-darwin) : https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_x86_64-2023-03-21-ceacc17.tar.gz
zig installed at nix-darwin

The compiled NixOS is the same as well. macOS has been tested on the M2, and Zig was installed in the same way on all of them. 

Thanks.

> roc run platform-switching/rocLovesZig.roc

🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `str.zig`. Check the source code in find_zig_str_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:90:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:903:46

**Comment by bhansconnect** [comment]
Where are you running the `roc` executable from? Is it still within the same folder structure as came from the archive?

**Comment by Anton-4** [comment]
I think you may need to copy over the crates folder included in the nightly archive to your project folder and run roc from that folder. If you let me know if that works for you, I will improve the error message.

**Comment by PlumpMath** [comment]
Thank you for letting me know. I haven't tried it yet because of my poor health, but I will let you know when I do. I hope that this language will be fully developed and become my next primary language.

**Comment by PlumpMath** [comment]
❯ ./roc examples/platform-switching/rocLovesZig.roc

🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Error:
    Failed to rebuild host.zig:
        The executed command was:
            zig build-obj examples/platform-switching/zig-platform/host.zig -femit-bin=examples/platform-switching/zig-platform/macos-x86_64.o --pkg-begin str crates/compiler/builtins/bitcode/src/str.zig --pkg-end --pkg-begin compiler_rt /nix/store/pghlwfnd501069652sgf9sxrbxxvc8kf-zig-0.10.1/lib/zig/std/special/compiler_rt.zig --pkg-end --library c
        stderr of that command:
            error: Failed to add package at path /nix/store/pghlwfnd501069652sgf9sxrbxxvc8kf-zig-0.10.1/lib/zig/std/special/compiler_rt.zig: FileNotFound
', crates/compiler/build/src/link.rs:1496:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:893:46

**Comment by Anton-4** [comment]
Oh yeah, we're still on zig 0.9.1. We did make progress on upgrading to zig 10, I'll ask around where we are on that.
I'll see if we can improve the error message for zig version mismatches.

**Comment by PlumpMath** [comment]
"The Git main version compiles well on nixos. (It also works well with the same Zig version 0.10.1 there) However, on MacOS Intel/m2 with the same version, it doesn't work. But on Mac, when I try to compile the main source, I can't build due to a segment error, so I use binaries on Mac."

**Comment by Anton-4** [comment]
I have some trouble following what went wrong, can you make issues for the errors you encountered along with the command and the operating system that was used?

If you are using macos 13 you may encounter problems due to a bug in zig 0.9.1, although as long as you're not building zig or wasm platforms you will likely not encounter this problem.

By the way, once [this pull request](https://github.com/roc-lang/roc/pull/5001) is done we will be able to complete the upgrade to zig 10 and officially support it.

If you want to try out interop with other languages, these examples will be helpful:
- [python](https://github.com/roc-lang/roc/tree/main/examples/python-interop)
- [java](https://github.com/roc-lang/roc/tree/main/examples/jvm-interop) (to connect with clojure)

For some questions it can be easier to talk with us on [zulip chat](https://roc.zulipchat.com/), you're always welcome there :)

**Comment by Anton-4** [comment]
I have not set up the flake to install roc yet, but using the default.nix with the command `nix-build` should work on NixOS and linux in general although it is not thoroughly tested. default.nix has dependencies for macos as well, but `nix-build` is not tested on macos CI. I'll make a note to add macos tests for default.nix.

**Comment by PlumpMath** [comment]
I manage computers with an entire mono setup. Since it's all the same configuration, I'm hesitant to share the whole setup, but it's nothing extraordinary, and I am a beginner with nix-shell and coding in general. I haven't finished reading all the roc documentation yet. I tend to work slowly, adjusting everything bit by bit... I was inspired by your flake.nix the day before yesterday and worked on the roc, and today I incorporated tauri and other rust GUIs into nix. (I'm a nix-shell beginner). When I initially tried to incorporate roc into the whole setup, I encountered a file conflict with the previously added poetry2nix. I had to force the loading of the default.nix for all but macOS, and then proceeded with a source build installation, but failed cause collison. I wish there were no conflicts with poetry2nix when force accessing the default.nix from the inputs and building from source on macOS. 

Either I should give up on Roc or poetry2nix, or take them out of the mono setup and manage their profiles separately... Since I've been working on the setup for a long time, I'm leaning towards just waiting. Don't worry too much about my issue and focus on what you were doing. I'm a beginner, and I don't participate in English chats because I can't speak English. If I were to elaborate more on this topic... Personally, I think some people like me adjust their entire configuration.nix or mono flake.nix, but it's not right for all individual project developers to match their nix to people like me who set up the entire setup. It seems like a good idea to match the Nix build CI, but I believe it's best done together with the nixpkgs maintainers. (Anyway, my personal goal is a complete nix setup, but it's a headache to change all kinds of buttons because of constant changes. Also, I rely on the mono setup because I can't trust my memory). If you think about Nix setup in an extremely negative way, you can see examples like the popular ChatGPT these days. The model seems to be a rigid file in the Nix style, but it can't be as flexible and fast as other distributions like a program in the opposite style of Nix... It's possible to avoid mono, but I'm thinking of it as nix-shell (development mode) to keep the simple setup and prevent the hard disk from increasing. Anyway, if AI (like ChatGPT and other generative algorithm tools) constantly emits changing data, Nix is the opposite, constantly fixing Nix coding... Haha. In fact, the reason I started working on Roc since last week is that Clojure was a company-approved language, and I often wished Nix was a general-purpose program rather than a DSL while using Nix. I thought it would be great if there was such a language. About a week ago? I was surprised when I saw the Roc code import side, thinking it's a Nix-like language, so I'm still holding onto it (I have to jump from the basics;;; I'm a slow learner because I'm ambitious). Anyway, I'm not sure if it's just my misconception that the first impression of the language is similar to Nix, but I hope Roc language is an architect blueprint-style language similar to Nix (especially since you can develop a GUI). Anyway, it's amazing that you can mix this language and that language, even Rust and Clojure. Coding will be really fun. Fly high~ fly Roc.

**Comment by tompflynn** [comment]
I am having a very similar issue, so I might as well mention it here. Whenever I try and run one of the examples using a zig-based platform I get this error on NixOS
```bash
roc run tui.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `glue.zig`. Check the source code in find_zig_glue_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:116:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:943:46
```

using nix-shell I tried both zig version 0.9.1 and the latest 0.10.1 with the same result.

**Comment by bhansconnect** [comment]
Yeah, same issue in a different form due to code updates. Is your roc built from source or from the nightly binary? Also, did you more the roc binary to a different folder, if so, did you move the zig libraries with it?

**Comment by lukewilliamboswell** [comment]
@bhansconnect could we have a workaround using `roc glue` where the spec provides a copy of the builtins in the glue directory that zig platform authors can keep and refer to locally? I assume the issue is that these zig platforms are referring to the roc builtins, and in future these will be provided by glue right? So maybe as a workaround we can do that. Downside I guess is that if major changes are made to roc builtins then the ZicSpec.roc glue file will also need to be updated. What do you think?

**Comment by lukewilliamboswell** [comment]
Or is this something that the roc cli needs to know so that it can build a zig platform from source? I guess the design is that platform authors would build these for different architectures and provides prebuilt libraries. Sorry if this just confuses this issue thread.

**Comment by bhansconnect** [comment]
We could make a temporary zig glue that essentially copies these files into a zig platform. That would solve the problem. That said, I would much prefer to make a minimal, but proper zig glue to avoid the dependency. It also would make the structures better for platforms. The builtin versions are fine for builtins but honestly not always that good for platforms.

But yeah, simplest solution is zig glue that directly imports the builtin files and then just dumps them all to files. That glue would need to be run from the roc directory, but once glue was generated for a platform, it would be free to be built anywhere.

**Comment by bhansconnect** [comment]
As a note, another totally reasonable solution is just to stop allowing zig platforms to depend on builtins. Then in each platform just copy the minimal amount of code to get the platform working. In most cases, I bet this is essentially the definition of RocStr with a little bit of extra changes. So manual glue, but extremely minimal. I might push a PR to do that.

**Comment by PlumpMath** [comment]
Leaving aside the Zig error, I cannot install Roc using 'nix profile install github:roc-lang/roc' on my Mac with an Intel processor. It has only worked on NixOS and Mac M2 since I first wrote this post. (Currently, even my Zig-related tests are not running)

nixos
```
 ~/roc (main) [1]> roc examples/platform-switching/rocLovesZig.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `glue.zig`. Check the source code in find_zig_glue_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:116:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:943:46

```

Mac m2
```
 ~/roc   main  roc examples/platform-switching/rocLovesZig.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Error:
    Failed to rebuild host.zig:
        The executed command was:
            zig build-obj examples/platform-switching/zig-platform/host.zig -femit-bin=examples/platform-switching/zig-platform/macos-arm64.o --pkg-begin str crates/compiler/builtins/bitcode/src/str.zig --pkg-end --pkg-begin compiler_rt /nix/store/bchnd795hxv6myjw5ambpnp116n6bi5i-zig-0.9.1/lib/zig/std/special/compiler_rt.zig --pkg-end --library c
        stderr of that command:
            ./examples/platform-switching/zig-platform/host.zig:3:13: error: unable to find 'glue'
const str = @import("glue").str;
            ^
', crates/compiler/build/src/link.rs:1496:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:893:46
```


I am also testing it on Synology NAS with both Intel and ARM processors, but since Nix flake is not supported on those two NAS, I cannot install Roc using nix profile on them. I have given up on that option. 

What I hope for in the future is for Roc to be integrated into nixpkgs, making it easy to install using configuration.nix (whether using flake.nix or config.nix) without the need for nix profile or nix-shell.

**Comment by PlumpMath** [comment]
I hope this project succeeds in eliminating the language barrier between corporate developers and open-source developers, bringing about a more unified world.

**Comment by Anton-4** [comment]
This issue is becoming a bit chaotic, I'm going to split this up.

**Comment by Anton-4** [comment]
For the "cannot find `glue.zig`" issue: #5357

**Comment by Anton-4** [comment]
For the "I cannot install Roc using 'nix profile install github:roc-lang/roc' on my Mac with an Intel processor" issue: #5358

**Comment by Anton-4** [comment]
For "Running Roc on original NixOS (not WSL) results in a segment fault error.": issue #5359

**Comment by Anton-4** [comment]
To "release roc as a nix package": issue #5360

**Comment by Anton-4** [comment]
To "support building with flake so that a nix shell is no longer necessary": issue #5361

**Comment by Anton-4** [comment]
Please continue the conversation in these new issues.
