### ISSUE TITLE
Fix support for a `rest` variable in list pattern matching 

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5187]
**Feature request:** Add support for a `rest` variable to capture the remaining elements of a list in `where` pattern matching expression.

For example, currently in Roc an `eatWhitespace` function could look like the following; 

```elixir
eatWhitespace = \bytes ->
    when bytes is
        [' ', ..] -> eatWhitespace (List.dropFirst bytes)
        ['\n', ..] -> eatWhitespace (List.dropFirst bytes)
        ['\r', ..] -> eatWhitespace (List.dropFirst bytes)
        ['\t', ..] -> eatWhitespace (List.dropFirst bytes)
        _ -> bytes
```

However if we support a `rest` variable this could be written as follows;

```elixir
eatWhitespace = \bytes ->
    when bytes is
        [' ', ..rest] -> eatWhitespace rest
        ['\n', ..rest] -> eatWhitespace rest
        ['\r', ..rest] -> eatWhitespace rest
        ['\t', ..rest] -> eatWhitespace rest
        _ -> bytes
```

This should be an efficient operation now that seamless slices language feature has been added to Roc. 🎉

**Comment by bhansconnect** [comment]
Just a note on this issue, I believe @folkertdev, at one point, said this should be supported with the following syntax:
```coffee
eatWhitespace = \bytes ->
    when bytes is
        [' ', .. as rest] -> eatWhitespace rest
        ['\n', .. as rest] -> eatWhitespace rest
        ['\r', .. as rest] -> eatWhitespace rest
        ['\t', .. as rest] -> eatWhitespace rest
        _ -> bytes
```

I don't think that works currently, but I think that was the syntax that was expected to work.
It passes `roc check`, but still fails to run.

**Comment by rtfeldman** [comment]
I like the proposed `as` syntax, because it should work anyway (you can always use `as` to name a pattern) and I like there being only one way to do this. 😄

**Comment by rtfeldman** [comment]
To reproduce the bug:

```haskell
app "helloWorld"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line (listThing [0, 1, 2, 3] |> Num.toStr)

listThing = \list ->
    when list is
        [head, .. as rest] -> head + List.len rest
        [] -> 0
```

`roc check` succeeds, but `roc build` fails with:

> thread 'main' panicked at 'Expected symbol to be in the map', crates/compiler/mono/src/inc_dec.rs:392:26

**Comment by JRMurr** [comment]
I'll give this a shot!

**Comment by bhansconnect** [comment]
I have a branch that fixes this though is currently hitting some other issues (that to be fair exist on main as well). If I can't find a fix for the other issue, I may narrow the scope to only fix this issue, but hopefully it can fix both

PR at #6030

@JRMurr sorry if I made a PR that overlaps with work you already did or wanted to do. Didn't realize someone was working on this and got annoyed enough this morning to finally dive in and try and fix it directly.

**Comment by JRMurr** [comment]
No worries @bhansconnect, I mostly used it an excuse to explore the compiler so not wasted effort!
