### ISSUE TITLE
Fix for `<<` shift operator syntax sugar

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5192]
The [tutorial](https://www.roc-lang.org/tutorial#operator-desugaring-table) describes using the `<<` operator to byte shift a number.

Using the `<<` operator in the REPL gives the following output.

```sh
% roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 7 << 4

── UNKNOWN OPERATOR ────────────────────────────────────────────────────────────

This looks like an operator, but it's not one I recognize!

1│  app "app" provides [replOutput] to "./platform"
2│
3│  replOutput =
4│      7 << 4
          ^^

I have no specific suggestion for this operator, see TODO for the full
list of operators in Roc.
```

**Comment by skyqrose** [comment]
This operator is no longer listed in the tutorial, which is correct. The operator isn't in the language. Instead, there's the function [Num.shiftLeftBy](https://www.roc-lang.org/builtins/Num#shiftLeftBy). Some discussion on adding it to the language is in [zulip](https://roc.zulipchat.com/#narrow/channel/231634-beginners/topic/Bit.20shifting.20operators.3F).
