### ISSUE TITLE
String literals can create invalid UTF-8

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5235]
This is invalid UTF-8, but the compiler accepts it:

```
"\u(C3)\u(28)"
```

Instead, this should be a canonicalization error!

**Comment by itmuckel** [comment]
I'd like to do this, if no one else started this already. 🙂

**Comment by rtfeldman** [comment]
Awesome, thank you! 😃 

Feel free to ask on Zulip in the `#contributing` channel if you have any questions or get stuck!

**Comment by ayazhafiz** [comment]
Closed because this is not invalid UTF8: https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/canonicalization/near/345950929
