### ISSUE TITLE
Division using dec sometimes make a wrong answer

### ISSUE THREAD

**Issue by yukiomoto** [roc-lang/roc#5259]
It looks like this happens with numbers greater than 340.

right answer 1

```
» 339dec / 340

0.997058823529411764 : Dec
```

right answer 2

```
» 340dec / 340

1. : Dec
```

wrong answer 1
```
» 341dec / 341

1.152921504606846975 : Dec
```

wrong answer 2
```
» 341dec / 342

1.152921504606846975 : Dec
```

**Comment by bhansconnect** [comment]
very intriguing. Not surprised something is broken here given it is so untested. Thanks for the bug.

My guess is we are doing something wrong with scale of intermediate computations. That is then leading us to losing information. Which finally leads to the bugs.

**Comment by yukiomoto** [comment]
@bhansconnect 
Thank you for the information ! 

I'm trying to fix this because this might block what I'm working on (#5218).

I'm not sure if this is even a problem but in the function you mentioned, I see, [mul_u128](https://github.com/roc-lang/roc/blob/main/crates/compiler/builtins/bitcode/src/num.zig#L23) is used to get U256 version of numerator. And if you give it `341000000000000000000` and `1000000000000000000` as its argument, it returns `U256{ .hi = 1, .lo = 717633079061536536625392568231788544 }` which I think means `340,999,999,999,999,999,999,999,999,999,999,999,999` but is it expected ?

**Comment by bhansconnect** [comment]
I think that number is correct

low: `717633079061536536625392568231788544` -> `0x008A360AE2C66FE7D3BAE05000000000`
hi: `1` -> `0x1`

full: `0x1008A360AE2C66FE7D3BAE05000000000` -> `341000000000000000000000000000000000000`

**Comment by yukiomoto** [comment]
Oh I got it. Thank you so much.
