### ISSUE TITLE
Implement `Num.absDiff` 

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5270]
Implement the `Num.absDiff` function for Roc

[zulip discussion](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Num.20function.20for.20getting.20the.20difference.20between.20two.20numbers/near/347277847)

[Rust docs for abs_diff](https://doc.rust-lang.org/std/primitive.usize.html#method.abs_diff)

**Comment by wontem** [comment]
I would like to take it as a first contribution. Probably my implementation will be very naive (no LLVM optimizations like [it's done for rust ](https://doc.rust-lang.org/src/core/num/uint_macros.rs.html#1641-1644), will try to add it iteratively).
If I have some questions or need some help - I'll post them on Zulip
