### ISSUE TITLE
implement proper error handling for `getInt` in `benchmarks/platform/Task.roc`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5283]
See [this line of code](https://github.com/roc-lang/roc/blob/191d8a74086267b102bb2a388dbd37f5b814b6e8/crates/cli_testing_examples/benchmarks/platform/Task.roc#L72).

**Comment by skyqrose** [comment]
No longer relevant since Task was moved to be a builtin and is no longer part of the cli platform. This code was removed in https://github.com/roc-lang/roc/commit/700c7ae9aa3f9642857b9281da726ec93ae2cf71 (note that the file was previously renamed to `crates/cli/tests/benchmarks/platform/Task.roc`)
