### ISSUE TITLE
Online REPL gives "Missing Final Expression" error for an assignment.

### ISSUE THREAD

**Issue by human154** [roc-lang/roc#5301]
Here's a repl session from just now...

» x = 5
── MISSING FINAL EXPRESSION ────────────────────────────────────────────────────

I am partway through parsing a definition, but I got stuck here:

1│  app "app" provides [replOutput] to "./platform"
2│
3│  replOutput =
4│      x = 5
             ^

This definition is missing a final expression. A nested definition
must be followed by either another definition, or an expression

    x = 4
    y = 2

    x + y

**Comment by Anton-4** [comment]
Linking to discussion in [this zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/repl.20surprises).

**Comment by Anton-4** [comment]
Reply from Brian:
"
It's not a regression or a bug, it was just never implemented

The web repl and cli REPL have separate front ends, handle newlines differently, etc. The web repl currently only takes expressions, not definitions. The logic could be connected up but it hasn't been. Would be a great contribution if someone wants to do it!
"

**Comment by Anton-4** [comment]
This works now :)
