### ISSUE TITLE
limited access to web based standard library documentation.

### ISSUE THREAD

**Issue by human154** [roc-lang/roc#5314]
It's possible to reach specific parts of the standard library documentation, for example:
https://www.roc-lang.org/builtins/Str

However the link to the main documentation section is dead:
https://www.roc-lang.org/builtins/Documentation

Currently there are no links from the main web page to the web based documentation.

**Comment by lukewilliamboswell** [comment]
The main issue that is blocking this is describe in [roc-lang/basic-cli#22](https://github.com/roc-lang/basic-cli/pull/22). 

In the interim I have a PR [#28](https://github.com/roc-lang/basic-cli/pull/28) which you can checkout and then follow the instructions in README to generate docs locally. 

Basically, 

```bash
roc docs src/main.roc
cd generated-docs
simple-http-server --nocache # You can install it with `cargo install simple-http-server`.
```

Intent is for the docs to be available on the website, but I think this bug breaks CI. So I assume this means that any docs need to be manually generated and uploaded for now which is difficult to support.

**Comment by skyqrose** [comment]
Docs are currently available on the website: https://www.roc-lang.org/builtins , and there's a link to https://www.roc-lang.org/docs from the home page. So I guess this got fixed some time in the last year and a half. Closing.
