### ISSUE TITLE
Running `roc test` crashes on Ubuntu 23.04

### ISSUE THREAD

**Issue by Hasnep** [roc-lang/roc#5340]
[Discussion on Zulip](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Roc.20test.3A.20.22Linking.20command.20failed.22)

## MWE to recreate

Using Ubuntu 23.04 (lunar)

Create these files:
```roc
# src/main.roc
package "Example"
    exposes [HelloWorld]
    packages {}
```
```roc
# src/HelloWorld.roc
interface HelloWorld exposes [greet] imports []

greet = \person -> "Hello, \(person)."

expect greet "World" == "Hello, World."
```
Then run this command to test:
```shell
roc test src/main.roc
```
The output is:
```
ld: cannot find -lc
ld: cannot find -lm
ld: cannot find -lpthread
ld: cannot find -ldl
ld: cannot find -lrt
ld: cannot find -lutil
ld: cannot find -lc_nonshared
thread 'main' panicked at '
___________
Linking command failed with status ExitStatus(unix_wait_status(256)):

  Child { stdin: None, stdout: None, stderr: None, .. }
___________
', crates/compiler/build/src/link.rs:1392:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've confirmed that this doesn't happen on Ubuntu 22.04 LTS (jammy), but does on 23.04 (lunar), I'm not sure about the release in between (22.10 kinetic).

**Comment by Anton-4** [comment]
Next to interfaces, this failure also happens [with apps](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Roc.20test.3A.20.22Linking.20command.20failed.22/near/353876468).

**Comment by Hasnep** [comment]
Closing as user error :facepalm: I had another GNU binutils installed that was higher in my `PATH`, so the wrong `ld` command was being called.
