### ISSUE TITLE
cannot find `glue.zig`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5357]
Originally posted [here](https://github.com/roc-lang/roc/issues/5183#issuecomment-1530842281) by @tompflynn:
"
I am having a very similar issue, so I might as well mention it here. Whenever I try and run one of the examples using a zig-based platform I get this error on NixOS
```
roc run tui.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `glue.zig`. Check the source code in find_zig_glue_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:116:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:943:46
```
using nix-shell I tried both zig version 0.9.1 and the latest 0.10.1 with the same result.
"

**Comment by Anton-4** [comment]
Other reports:
"
nixos (wsl)
```
 ~/roc (main) [1]> roc examples/platform-switching/rocLovesZig.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'cannot find `glue.zig`. Check the source code in find_zig_glue_path() to show all the paths I tried.', crates/compiler/build/src/link.rs:116:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:943:46
```
Mac m2
```
 ~/roc   main  roc examples/platform-switching/rocLovesZig.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Error:
    Failed to rebuild host.zig:
        The executed command was:
            zig build-obj examples/platform-switching/zig-platform/host.zig -femit-bin=examples/platform-switching/zig-platform/macos-arm64.o --pkg-begin str crates/compiler/builtins/bitcode/src/str.zig --pkg-end --pkg-begin compiler_rt /nix/store/bchnd795hxv6myjw5ambpnp116n6bi5i-zig-0.9.1/lib/zig/std/special/compiler_rt.zig --pkg-end --library c
        stderr of that command:
            ./examples/platform-switching/zig-platform/host.zig:3:13: error: unable to find 'glue'
const str = @import("glue").str;
            ^
', crates/compiler/build/src/link.rs:1496:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to (re)build platform.: Any { .. }', crates/compiler/build/src/program.rs:893:46
```
"

**Comment by PlumpMath** [comment]
Mac intel (can't build, nix profile & cargo build) 

/Users/username/.nix-profile/bin:/etc/profiles/per-user/username/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin

nixos (not wsl) 
nix profile install github:roc-lang/roc 
/home/username/.nix-profile/bin/roc
execute
[1]   575419 segmentation fault (core dumped) roc

/run/wrappers/bin:/home/username/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/username/.nix-profile/bin:/etc/profiles/per-user/username/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin

**Comment by PlumpMath** [comment]
synology ds620slim(Intel Celeron J3355) :
cargo build

error: failed to run custom build command for `roc_bitcode_bc v0.0.1 (/volume1/homes/username/roc/crates/compiler/builtins/bitcode/bc)`

Caused by:
  process didn't exit successfully: `/volume1/homes/username/roc/target/release/build/roc_bitcode_bc-e755c6701b1852b0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  Compiling host ir to: /volume1/homes/username/roc/crates/compiler/builtins/bitcode/bc/../builtins-host.ll
  Compiling 64-bit bitcode to: /volume1/homes/username/roc/crates/compiler/builtins/bitcode/bc/../builtins-host.bc

  --- stderr
  thread 'main' panicked at 'zig build ir -Drelease=true failed with:


  ', crates/compiler/builtins/bitcode/bc/build.rs:124:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by PlumpMath** [comment]
macOS intel

cargo build ..
```

error 
   Compiling distance v0.4.0
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> crates/compiler/mono/src/ir.rs:77:1
   |
77 | roc_error_macros::assert_sizeof_non_wasm!(Expr, 9 * 8);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `ir::Expr<'_>` (640 bits)
   = note: target type: `[u8; 72]` (576 bits)
   = note: this error originates in the macro `static_assertions::assert_eq_size` which comes from the expansion of the macro `roc_error_macros::assert_sizeof_non_wasm` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> crates/compiler/mono/src/ir.rs:78:1
   |
78 | roc_error_macros::assert_sizeof_non_wasm!(Stmt, 12 * 8);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `Stmt<'_>` (832 bits)
   = note: target type: `[u8; 96]` (768 bits)
   = note: this error originates in the macro `static_assertions::assert_eq_size` which comes from the expansion of the macro `roc_error_macros::assert_sizeof_non_wasm` (in Nightly builds, run with -Z macro-backtrace for more info)

   Compiling crossbeam v0.8.2
   Compiling roc_constrain v0.0.1 (/Users/username/roc/crates/compiler/constrain)
   Compiling ucd-trie v0.1.5
   Compiling pest v2.5.6
   Compiling roc_reporting v0.0.1 (/Users/username/roc/crates/reporting)
For more information about this error, try `rustc --explain E0512`.
error: could not compile `roc_mono` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by bhansconnect** [comment]
@PlumpMath, you should be able to safely comment out `roc_error_macros::assert_sizeof_non_wasm!(Expr, 9 * 8);` and related lines. That probably will fix the build. Not related to this `glue.zig` issue, but still definitely a bug (should be track in a different issue than this one if it isn't already). I am definitely a bit confused why it is an issue (maybe from using a different rust version than we do). Based on looking at `rust-toolchain.yaml` in the repo, we are on version `1.66.1` currently.

**Comment by PlumpMath** [comment]
The reason why I had all those Zig-related compilation issues when running nix-shell followed by cargo build is because I had set some environment variables globally, which caused problems on my system. I had referenced the flake.nix file, 

```
# reference flake.nix

LLVM_SYS_130_PREFIX = "${llvmPackages_13.llvm.dev}";
LD_LIBRARY_PATH = lib.makeLibraryPath( buildInputs-full ); 
```

which contained those environment variables that I had previously needed for studying GUI-related Rust development, such as with Tauri or GUI Rust programs. So currently, I'm wrapping some personal packages that are unrelated to Roc and handling those local variables separately.

**Comment by Anton-4** [comment]
This problem with `roc_error_macros::assert_sizeof_non_wasm!(Expr, 9 * 8);` occurs when using a different version of rust.

@PlumpMath do I understand correctly that the error `cannot find glue.zig` has been fixed in your case?

**Comment by PlumpMath** [comment]
I didn't understand the glue.zig issue because I'm not familiar with Zig. I couldn't grasp what the problem with the glue Zig was. However, I understood that the Rust version needs to be aligned with that specific version.

**Comment by Anton-4** [comment]
No problem :)

**Comment by Anton-4** [comment]
Because this issue appears to be resolved by following the steps [here](https://github.com/roc-lang/roc/issues/5357#issuecomment-1531889392) I will close it. @tompflynn please let us know if you still have any unresolved issues.
