### ISSUE TITLE
NixOS segmentation fault

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5359]
Originally posted [here](https://github.com/roc-lang/roc/issues/5183#issuecomment-1531106214) by @PlumpMath:
"
Running Roc on original NixOS (not WSL) results in a segment fault error. It seems that a glibc environment variable is required in nix-shell. I hope that this issue can be resolved without the need for nix-shell, only with buildInputs, without requiring the glibc environment variable. Is it possible to solve this issue with only LLVM-related dependencies, without the need for glibc, in Linux? When I added glibc to buildInputs to resolve the error, a segment fault error occurred. Of course, if glibc is not added, a libstdc++ error occurs
"

**Comment by Anton-4** [comment]
@PlumpMath can you share the commands you ran?

**Comment by PlumpMath** [comment]
https://github.com/roc-lang/roc/issues/5358#issuecomment-1532039127

I was able to resolve the issue in NixOS in the same way. However, the GUI example error.

<img width="896" alt="스크린샷 2023-05-03 오전 4 52 41" src="https://user-images.githubusercontent.com/1218365/235771258-ab57f5df-eb8f-49e1-b6e9-c5eaec1a4fb2.png">


https://github.com/roc-lang/roc/blob/main/BUILDING_FROM_SOURCE.md

I am referring to this resource to try and resolve the issue, so thank you for the recommendation.

**Comment by Anton-4** [comment]
:+1: I've made a [new issue](https://github.com/roc-lang/roc/issues/5368) for the GUI example error.
