### ISSUE TITLE
support building with flake so that a nix shell is no longer necessary

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5361]
I hope to get this done this month.

**Comment by nat-418** [comment]
> Currently blocked on [ipetkov/crane#318](https://github.com/ipetkov/crane/issues/318)

Since that is closed, what needs to happen here?

**Comment by Anton-4** [comment]
This is done :)
`nix build` works now, [for reference](https://github.com/roc-lang/roc/blob/cf8967da61c0afb9a2e701c199516e863144966a/flake.nix#L144).
