### ISSUE TITLE
gui example `thread 'main' panicked at 'Request adapter`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5368]
Originally reported [here](https://github.com/roc-lang/roc/issues/5359#issuecomment-1532061621) by @PlumpMath:

![image](https://user-images.githubusercontent.com/17049058/235890726-f1c6878f-a001-46aa-9cfb-da9f80b01940.png)

**Comment by Anton-4** [comment]
Is this on NixOS @PlumpMath?

**Comment by PlumpMath** [comment]
> Is this on NixOS @PlumpMath?

Yes. wayland + amdgpu

**Comment by Anton-4** [comment]
Awesome, a good day to you as well :)
