### ISSUE TITLE
New Abilities Syntax

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5377]
The syntax in [this Zulip link](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Abilities.20syntax/near/350077930) is officially the plan.

If anyone would like to take a shot at implementing it (or part of it), please leave a comment here!

**Comment by sandprickle** [comment]
I'm game to try to complete at least part of this. I will be spending many hours on planes this week. 

I hope I'm not signing up for something that's way over my head. Rust is still a bit scary to me 😅

**Comment by rtfeldman** [comment]
Awesome! Feel free to pick off one bit at a time, and ask for help on absolutely anything on Zulip! 😃

**Comment by sekerez** [comment]
Should we close this issue?

**Comment by rtfeldman** [comment]
Yep! 🎉
