### ISSUE TITLE
Replace `Nat` with `U64`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5384]
The plan is to remove `Nat` as a first-class type in Roc. Everywhere it currently appears in builtins should be replaced with `U64`, and `Nat` number literals (e.g. `123nat`) should be removed from the parser.

Note that this should not affect data structures. For example, on 32-bit targets, `List` still uses 32-bit integers to store its length and capacity in memory. The difference is that now, when compiling for 32-bit targets, `List.len` casts that 32-bit integer to `U64` before returning it. Similarly for `List.get`, `List.set`, etc.

See https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/replace.20.60Nat.60 for discussion.

**Comment by skyqrose** [comment]
This was done in https://github.com/roc-lang/roc/pull/6422
