### ISSUE TITLE
[Question / Discussion] Standard library argument ordering and |> is different to other ML langauges - any reason?

### ISSUE THREAD

**Issue by njlr** [roc-lang/roc#5409]
Hello :wave: 

This is a question more than a bug; I hope it's in the right place. 

In OCaml and F#, the standard library functions tend to put the "main input" being operated on in the last position. 

For example, OCaml [List.map](https://v2.ocaml.org/api/List.html):

```ocaml
val map : ('a -> 'b) -> 'a list -> 'b list
```

And F# [List.map](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#map):

```fsharp
val map : (('a -> 'b) -> 'a list -> 'b list)
```

This is so that operations can be chained with the pipe operator:

```fsharp
[ 1; 2; 3 ]
|> List.map (fun x -> x + 1)
```

Which in F# can be defined as:

```fsharp
let (|>) x f = f x
```

I noticed that Roc swaps the argument order around, and the [pipe operator](https://www.roc-lang.org/tutorial#the-pipe-operator) is a little different too:

> The |> operator takes the value that comes before the |> and passes it as the first argument to whatever comes after the |>. So in the example above, the |> takes List.get ["a", "b", "c"] 1 and passes that value as the first argument to Result.withDefault, making "" the second argument to Result.withDefault.

Now, I don't think that everything needs to be the same - changing things is a prerequisitie for making things better! However, I was wondering what the gain is from breaking from ML convention in this particular case? 

For myself, it would certainly make it easier to adopt Roc if it uses more familiar conventions. Perhaps there is an advantage to swapping the argument order that I haven't spotted?

Anyway, looking forward to future development on Roc!

**Comment by Anton-4** [comment]
Hi @njlr,
The reasoning for this decision is explained in [this section on currying](https://github.com/roc-lang/roc/blob/main/roc-for-elm-programmers.md#currying-and-).

**Comment by njlr** [comment]
Thanks @Anton-4 that makes sense!
