### ISSUE TITLE
Wrong boolean operator precedence

### ISSUE THREAD

**Issue by KilianVounckx** [roc-lang/roc#5410]
Both boolean operators `&&` and `||` are at the same precedence (0) at the moment. (implemented in this [file](https://github.com/roc-lang/roc/blob/cfcd2a52892cc5ef0cf3ba9a33007820aa57d596/crates/compiler/module/src/called_via.rs#L21-L22)).
In almost all other languages, as well as boolean algebra in mathematics, the `&&` operator has higher precedence however. Either the precedence should be changed, or the compiler should enforce parenthesis around chaining these operators to avoid confusion.

**Comment by bhansconnect** [comment]
So there are 2 things here to do after discussion on zulip:
1. Simply update the precedence. Extremely simple change to the file linked above. Yeah, increment a few things by 1 and reorder and above or.
2. Add a warning to the compiler that says parens should be added (probably not that hard, but definitely more in depth)

**Comment by aybeedee** [comment]
Made the first change, eager to take up the second one if I can get some initial direction on how to attempt it.
