### ISSUE TITLE
breakout examples segfault

### ISSUE THREAD

**Issue by tzemanovic** [roc-lang/roc#5416]
hi, 

I'm trying to update to more a recent Roc version and it seems that there's some issue potentially introduced by #5093:

When I run `roc run examples/gui/breakout/hello-gui.roc` or `roc run examples/gui/breakout/breakout.roc` I get "Segmentation fault: child process 'roc' core dumped".

The commit before the merge of #5093 ceacc1792 doesn't seem to have this problem.

**Comment by Anton-4** [comment]
Once we fix this error, we should add tests for these examples that actually launch the GUI, similar to [this editor test](https://github.com/roc-lang/roc/blob/main/crates/cli/tests/editor.rs).

**Comment by Anton-4** [comment]
Sidenote: `examples/gui/hello.roc` also segfaults but only after closing the window.
