### ISSUE TITLE
Add file importing as Str to Tutorial

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5427]
Add a new feature which enables importing files directly as a Str or a List U8 to the Roc tutorial. 

[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/PSA.3A.20import.20files.20as.20Str.2FList.20U8/near/348507136)

**Comment by Anton-4** [comment]
I'm a little confused by the wording, are you saying the concept of "importing files directly as a Str" should be explained in the tutorial?
