### ISSUE TITLE
dbg tag: 'region @5-16 not in list of dbgs'

### ISSUE THREAD

**Issue by AjaiKN** [roc-lang/roc#5465]
I don't know how related this is to #5458.

```roc
app "main"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    dbg (MyTag 3)

    Stdout.line "Hello, World!"
```

```
$ cargo run dev
    Finished dev [unoptimized + debuginfo] target(s) in 0.77s
     Running `/Users/ajainelson/prog/roc/roc/target/debug/roc dev`
thread 'main' panicked at 'region @5-16 not in list of dbgs', /Users/ajainelson/prog/roc/roc/crates/repl_expect/src/run.rs:521:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$
```

Also, I'm not sure if this is normal, but after the panic, the process continues to run. Until I kill it, `roc_app_binary` takes up 100% of the CPU according to Mac's Activity Monitor. My laptop has been warm all day and running out of battery quickly, so I'm just glad to realize it's not a problem with the laptop. 😅

**Comment by doubledup** [comment]
Just ran into this too (also on Mac), but didn't notice the 10 `roc_app_binary` processes until reading this 😅

**Comment by JRI98** [comment]
No longer reproduces.

Output for reference:
```
[main.roc:9] MyTag 3 = (MyTag 3)
Hello, World!
```
