### ISSUE TITLE
thread 'main' panicked at 'There can only be floats here!'

### ISSUE THREAD

**Issue by fdbeirao** [roc-lang/roc#5467]
### Output of `roc test`

```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'There can only be floats here!', crates/compiler/gen_llvm/src/llvm/lowlevel.rs:2030:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Output of `roc --version`

`roc nightly pre-release, built from commit 62cdcea on Sa 27 Mai 2023 09:06:38 UTC`

### Output of `roc check`

`0 errors and 0 warnings found in 25 ms.`

### Output of `roc run`

> The surgical linker currently has issue #3609 and would fail linking your app.
> Please use `--linker=legacy` to avoid the issue for now.

### Output of `roc run --linker=legacy`

`22448.166666666668`

### Code that reproduces the crash

```roc
app "variance"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf

variance : List (Num a) -> Result (Frac b) [NotEnoughItems, Overflow]
variance = \dataSet ->
    totalItems = List.len dataSet

    if totalItems < 2 then
        Err NotEnoughItems
    else
        dataSet
        |> List.walkTry 0 (\state, elem -> elem |> Num.addChecked state) # Add up all numbers in the data set
        |> Result.try (\addedNumbers -> Num.mulChecked addedNumbers addedNumbers) # Square the sum of all numbers
        |> Result.map (\squared -> (Num.toFrac squared) / (Num.toFrac totalItems)) # Divide the total by the ammount of items on the dataset (no need to worry about DivByZero here)

main =
    [4, 22, 99, 204, 18, 20]
    |> variance
    |> Result.map Num.toStr
    |> Result.mapErr
        (\reason ->
            when reason is
                NotEnoughItems -> "Not enough items"
                Overflow -> "An overflow occurred"
        )
    |> Result.withDefault ""
    |> Stdout.line

expect (variance []) == Err NotEnoughItems
# expect (variance [0]) == Err NotEnoughItems
# expect (variance [4, 22, 99, 204, 18, 20]) == Ok 6_014.56

```

### Additional information

The error started happening when I added the line
`|> Result.map (\squared -> (Num.toFrac squared) / (Num.toFrac **totalItems))`

I find it interesting that `roc test` crashes while `roc run --linker=legacy`  actually works.
The code isn't yet fully implemented, I was progressing through the implementation when I got to this crash.

**Comment by bhansconnect** [comment]
Small guess. This may be related to types. Roc may be getting confused due to lack of concrete types.

`[]` has no concrete type. It is passed in as a `List (Num a)` The `Num a` is being converted to a `Frac b`. Maybe the lack of types is causing roc to fail to correctly pick default types.

**Comment by JRI98** [comment]
No longer reproduces
