### ISSUE TITLE
Improve `Undefined Symbol in relocation` error for floor, sin, round...

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5492]
A good amount of functions currently cause the `Undefined Symbol in relocation` error (caused by #3609):
```
thread 'main' panicked at 'Undefined Symbol in relocation, (+3382, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+26)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "floor", address: +0, size: +0, kind: Label, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1482:33
```
Instead of throwing this error we should give a brief explanation, mention issue #3609 and mention the workaround with `--linker=legacy`.

**Comment by bhansconnect** [comment]
Can/should we just also implement these as part of the builtins.o file like we just did for some compiler-rt functions?

Fundamentally, these are implicit roc dependencies that are pulling in libc. We don't want roc to depend on libc fundamentally. The platform should provide everything we need to depend on that isn't a builtin.

**Comment by bhansconnect** [comment]
All of these should now either work or hit:
```
The surgical linker currently has issue #3609 and would fail linking your app.
Please use `--linker=legacy` to avoid the issue for now.
```
