### ISSUE TITLE
thread main panicked when app name is empty

### ISSUE THREAD

**Issue by fdbeirao** [roc-lang/roc#5497]
This is a silly one, but should be handled gracefully. The following roc code:

```roc
app ""
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main = Stdout.line "Hello, I have an empty name!"
```

Causes this crash when we do `roc run`:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/compiler/build/src/program.rs:820:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Output of `roc --version`

`roc nightly pre-release, built from commit 0c50ee0 on Mi 31 Mai 2023 10:03:48 UTC`

## Output of `roc check`

`0 errors and 0 warnings found in 21 ms.`

**Comment by fdbeirao** [comment]
Naming the app `.` causes the following slightly different output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: IsADirectory, message: "Is a directory" }', crates/compiler/build/src/program.rs:820:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fdbeirao** [comment]
⚠ Naming the app `../parent` causes a file named `parent` to be created on a parent folder, which could in theory lead to attacks on REPL servers

**Comment by fdbeirao** [comment]
⚠ Naming the app `/absolute/path` will create the file on the absolute path. Depending on which permissions the roc script is being run with, we could potentially overwrite critical components on a server

**Comment by JRI98** [comment]
No longer reproduces
