### ISSUE TITLE
Web REPL inserts extra newlines

### ISSUE THREAD

**Issue by doubledup** [roc-lang/roc#5507]
The [web REPL](https://www.roc-lang.org/repl) inserts a newline before executing code when enter is pressed. This produces an error message when the code before the cursor isn't a valid line for the REPL, eg.
`Str.joinWith ["greeting", "audience"] ", "<cursor>` runs fine.
`Str.joinWith ["greeting", "<cursor>audience"] ", "` produces the `UNFINISHED LIST` error message.
`Str.joinWith ["greeting", "audience"] "<cursor>, "` produces the `ENDLESS STRING` error message.

**Comment by skyqrose** [comment]
I just tried again, and couldn't reproduce it, so I guess it got fixed some time in the last year and a half.
