### ISSUE TITLE
panic 'assertion failed: !self.not_reference_counted.contains(symbol)'

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5508]
@Ivo-Balbaert encountered this panic (https://github.com/roc-lang/basic-cli/issues/42) when running this example on Ubuntu 20.04 (WSL) with roc_nightly-linux_x86_64-2023-06-02-58067f9:
```
app "http-get"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Http, pf.Task.{ Task }, pf.Stdin, pf.Stdout]
    provides [main] to pf

main : Task {} []
main =
    _ <- Task.await (Stdout.line "Enter a URL to fetch. It must contain a scheme like \"http://\" or \"https://\".")

    url <- Task.await Stdin.line

    request = {
        method: Get,
        headers: [],
        url,
        body: Http.emptyBody,
        timeout: NoTimeout,
    }

    output <- Http.send request
        |> Task.onFail (\err -> err |> Http.errorToString |> Task.succeed)
        |> Task.await

    Stdout.line output
```

panic:
```
$ roc http-get.roc
thread 'main' panicked at 'assertion failed: !self.not_reference_counted.contains(symbol)', crates/compiler/mono/src/inc_dec.rs:98:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I was not able to reproduce this on WSL.

**Comment by Anton-4** [comment]
@Ivo-Balbaert can you share the output of `RUST_BACKTRACE=1 roc http-get.roc`?

**Comment by Anton-4** [comment]
@JTeeuwissen do you have any ideas as to why [this assert](https://github.com/roc-lang/roc/blob/93cc2e579ff89ff83786134440ec5c3bdf031624/crates/compiler/mono/src/inc_dec.rs#L98) may fail that could be caused by differences in hardware?

**Comment by Ivo-Balbaert** [comment]
Here is the output of :
***RUST_BACKTRACE=1 roc http-get.roc**
thread 'main' panicked at 'assertion failed: !self.not_reference_counted.contains(symbol)', crates/compiler/mono/src/inc_dec.rs:98:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:115:5
   3: roc_mono::inc_dec::SymbolRcTypes::get
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:98:13
   4: roc_mono::inc_dec::RefcountEnvironment::get_symbol_rc_type
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:266:9
   5: roc_mono::inc_dec::RefcountEnvironment::add_symbol
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:308:15
   6: roc_mono::inc_dec::insert_refcount_operations_stmt
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:478:17
   7: roc_mono::inc_dec::insert_inc_dec_operations_proc
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:425:20
   8: roc_mono::inc_dec::insert_inc_dec_operations
             at /home/ivo/roc_repo/roc/crates/compiler/mono/src/inc_dec.rs:53:13
   9: roc_load_internal::file::update
             at /home/ivo/roc_repo/roc/crates/compiler/load_internal/src/file.rs:3105:21
  10: roc_load_internal::file::state_thread_step
             at /home/ivo/roc_repo/roc/crates/compiler/load_internal/src/file.rs:1835:37
  11: roc_load_internal::file::load_multi_threaded::{{closure}}
             at /home/ivo/roc_repo/roc/crates/compiler/load_internal/src/file.rs:2098:23
  12: crossbeam_utils::thread::scope::{{closure}}
             at /home/ivo/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.15/src/thread.rs:163:65
  13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271:9
  14: std::panicking::try::do_call
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
  15: __rust_try
  16: std::panicking::try
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
  17: std::panic::catch_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  18: crossbeam_utils::thread::scope
             at /home/ivo/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.15/src/thread.rs:163:18
  19: roc_load_internal::file::load_multi_threaded
             at /home/ivo/roc_repo/roc/crates/compiler/load_internal/src/file.rs:2036:9
  20: roc_load_internal::file::load
             at /home/ivo/roc_repo/roc/crates/compiler/load_internal/src/file.rs:1621:35
  21: roc_load::load
             at /home/ivo/roc_repo/roc/crates/compiler/load/src/lib.rs:35:5
  22: roc_load::load_and_monomorphize
             at /home/ivo/roc_repo/roc/crates/compiler/load/src/lib.rs:133:11
  23: roc_build::program::build_file
             at /home/ivo/roc_repo/roc/crates/compiler/build/src/program.rs:744:9
  24: roc_cli::build
             at /home/ivo/roc_repo/roc/crates/cli/src/lib.rs:728:27
  25: roc::main
             at /home/ivo/roc_repo/roc/crates/cli/src/main.rs:45:17
  26: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Anton-4** [comment]
Thanks @Ivo-Balbaert :)

**Comment by Ivo-Balbaert** [comment]
It seems I have Ubuntu 22.04.2 LTS release installed in my WSL.

**Comment by Anton-4** [comment]
Thanks for letting me know, I'll check with that version as well

**Comment by Ivo-Balbaert** [comment]
No don't please. I just installed the nightly roc nightly pre-release, built from commit 58067f9 on Fr 02 Jun 2023 09:07:46 UTC
and it worked!

**Comment by Anton-4** [comment]
Oh, well that's good news, do you know what version you were using before?

**Comment by Ivo-Balbaert** [comment]
I was using a roc built from source: "roc built-from-source", it is the much larger version of 500 MB. I obtained it from a git pull this morning (Jun 3) and a cargo build. I used a version built like this since a month without any problem.

**Comment by Ivo-Balbaert** [comment]
I'll download a fresh copy of the roc-lang repo, and see if it still occurs. Sorry for all the time you put into this.

**Comment by Anton-4** [comment]
No problem at all, I enjoy helping people with Roc :)

It does make sense to me now that a debug_assert got triggered if you used the command `cargo build` because the `cargo build --release` command removes occurrences of `debug_assert`. That also means that something is actually going wrong, it just won't be reported with nightlies. I will probably be able to reproduce this locally.

**Comment by Ivo-Balbaert** [comment]
I can confirm that building a fresh source with cargo build --release doesn't have the problem I reported. 
roc http-get.roc works fine.
From now on, I'll keep using the 'cargo build --release' command to build source :-)
I'll close issue 42 on roc-lang/basic-cli.
If you think it is important to keep this issue here #5508 open, you may of course do so. For me the problem is solved. Thanks for all your help, it's people like you that will make Roc a big success!

**Comment by JTeeuwissen** [comment]
@Anton-4 let me know if you need me to look into it further, the assert fails when previous functions fail to add all symbols to the environment. But it's quite the simple analysis so I would not have expected it to fail here.

**Comment by JTeeuwissen** [comment]
But to answer your question: I don't think this assert directly depends on different hardware. But I cannot rule out its effect on IR generation before reference counting. Resulting in wrong assumptions from my part.

**Comment by Anton-4** [comment]
> I don't think this assert directly depends on different hardware.

Correct, I can reproduce it now when building roc with `cargo build`.

**Comment by Anton-4** [comment]
I checked with the other cli examples and http-get is the only one that is failing:
```
❯ ./target/debug/roc build examples/cli/http-get.roc 
thread 'main' panicked at 'assertion failed: !self.not_reference_counted.contains(symbol)', crates/compiler/mono/src/inc_dec.rs:98:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

> @Anton-4 let me know if you need me to look into it further

@JTeeuwissen yes, please :)

**Comment by JTeeuwissen** [comment]
Allright, the problem is as follows:
The IR of one of the statements looks like this
```coffee
procedure : `16.IdentId(2)` [C {{Boxed({[C Str List U8, C ], List {Str, Str}, [C , C U64], Str, U8}), {}}, {}} {}, C {}]
procedure = `16.IdentId(2)` (`16.IdentId(3)`: Str):
    let `17.IdentId(9)` : [C Str List U8, C ] = CallByName `17.IdentId(9)`;
    let `16.IdentId(26)` : List {Str, Str} = Array [];
    let `16.IdentId(27)` : [C , C U64] = TagId(0) ;
    let `16.IdentId(28)` : U8 = 2u8;
    let `16.IdentId(4)` : {[C Str List U8, C ], List {Str, Str}, [C , C U64], Str, U8} = Struct {`17.IdentId(9)`, `16.IdentId(26)`, `16.IdentId(27)`, `16.IdentId(3)`, `16.IdentId(28)`};
    let `16.IdentId(22)` : {Boxed({[C Str List U8, C ], List {Str, Str}, [C , C U64], Str, U8}), {}} = CallByName `17.IdentId(15)` `16.IdentId(4)`;
    let `16.IdentId(23)` : {} = Struct {};
    let `16.IdentId(19)` : {{Boxed({[C Str List U8, C ], List {Str, Str}, [C , C U64], Str, U8}), {}}, {}} = CallByName `18.IdentId(6)` `16.IdentId(22)` `16.IdentId(23)`;
    let `16.IdentId(20)` : {} = Struct {};
    let `16.IdentId(18)` : [C {{Boxed({[C Str List U8, C ], List {Str, Str}, [C , C U64], Str, U8}), {}}, {}} {}, C {}] = CallByName `18.IdentId(3)` `16.IdentId(19)` `16.IdentId(20)`;
    ret `16.IdentId(18)`;
```

note the first line `let `17.IdentId(9)` : [C Str List U8, C ] = CallByName `17.IdentId(9)`;` using the same symbol for different things. I mark the symbols for procedures as non reference counted and the symbols for variables as RC/non-RC depending on their type. So this assert fails as the same symbol is used by the proc. Looking into removing the proc symbol in it's entirety from the map.
