### ISSUE TITLE
provide good error message when `provides...` is forgotten in the header

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5516]
Currently this code snippet:
```
app "broken"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br",
    }
    imports [
        pf.Stdout,
    ]

main =
    Stdout.line "answer"
```
results in:
```
% roc check aoc-2022/03/broken.roc
thread 'main' panicked at 'not yet implemented: unhandled parse error IndentProvides(@201)', crates/reporting/src/error/parse.rs:3499:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`provides [main] to pf` was forgotten in the header, the panic should be prevented, and a nice error message should be provided instead.

**Comment by KilianVounckx** [comment]
The error message that was already there however will not have a newline at the end. Because of this, the shell prompt will be on the same line as the last line from the error. This is not ideal
