### ISSUE TITLE
Roc crashes with `explicit panic` 

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5526]
```
% roc run examples/Tuples/main.roc
thread '<unnamed>' panicked at 'explicit panic', crates/compiler/mono/src/ir/decision_tree.rs:279:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
app "tuples-example"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.2/tE4xS_zLdmmxmHwHih9kHWQ7fsXtJr7W7h3425-eZFk.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main = 

    fruitSelection : [Apple, Pear, Banana, Orange, Grape]
    fruitSelection = Pear

    qty : I32
    qty = 12

    when (fruitSelection, qty) is 
        (Apple, a) if a > 0 -> Stdout.line "You have some apples"
        (Pear, a) if a > 0 -> Stdout.line "You have some pears"
        (_, 0) -> Stdout.line "You have no fruit"

```

**Comment by Ivo-Balbaert** [comment]
This now doesn't crash anymore, and gives a seemingly correct error:

── UNSAFE PATTERN ───────────────────────────────────────────────── test24.roc ─

This when does not cover all the possibilities:

16│>      when (fruitSelection, qty) is
17│>          (Apple, a) if a > 0 -> Stdout.line "You have some apples"
18│>          (Pear, a) if a > 0 -> Stdout.line "You have some pears"
19│>          (_, 0) -> Stdout.line "You have no fruit"

Other possibilities include:

    ( Banana, _ )    (note the lack of an if clause)
    ( Grape, _ )    (note the lack of an if clause)
    ( Orange, _ )    (note the lack of an if clause)
    ( _, _ )    (note the lack of an if clause)

I would have to crash if I saw one of those! Add branches for them!

──────────────────────────────────────────────────────

1 error and 0 warnings found in 30 ms.

Perhaps this issue can be closed now?

**Comment by Anton-4** [comment]
Thanks for looking at all these issues @Ivo-Balbaert :heart:

**Comment by Ivo-Balbaert** [comment]
Thanks, no problem, "one does what one can". 
It is a pity that often the issue list on open-source projects seems to grow without end at a big rate, while issues stay open that could easily be closed. There should be a GitHub mechanism that reminds authors of issues every 6 months or so to check if their issue is still valid, or something like that.

**Comment by Ivo-Balbaert** [comment]
I'd hoped to squash more, but these were the easiest ones. Only 1135 and 5621 (duplicate) are still open.
