### ISSUE TITLE
Fix formatting on parsing error messages

### ISSUE THREAD

**Issue by isaacvando** [roc-lang/roc#5542]
Many parsing error messages that I have encountered do not print a newline at the end of the message.

For example, the program `main = Stdout.line "foo` with a missing double quote results in this output:

```
── ENDLESS STRING ─────────────────────────────────────────────────── main.roc ─

I cannot find the end of this string:

15│  main = Stdout.line "foo
                         ^

You could change it to something like "to be or not to be" or even
just "".isaac@isaacbox:~/Desktop/projects/oss/roc$ 
```

I'm not sure if this applies to other kinds of errors or only parsing errors.

**Comment by skyqrose** [comment]
Duplicate of https://github.com/roc-lang/roc/issues/4911
