### ISSUE TITLE
Roc crashes with `Segmentation fault: 11`

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5545]
EDIT [minimised reproduction](https://gist.github.com/lukewilliamboswell/ba9d4a03db1c0b89e9b38bef38f1c812)

Running this app [aoc-2022/12/main.roc](https://github.com/lukewilliamboswell/roc-things/blob/main/aoc-2022/12/main.roc) causes a `Segmentation fault: 11` on macOS. I'm using roc built from source. 

```
$ roc build --optimize  aoc-2022/12/main.roc 
0 errors and 0 warnings found in 2970 ms while successfully building:

    aoc-2022/12/aoc
$ ./aoc-2022/12/aoc 
Segmentation fault: 11
```

**Comment by Ivo-Balbaert** [comment]
Same on WSL-Ubuntu 22.

**Comment by JRI98** [comment]
No longer reproduces
