### ISSUE TITLE
Missing entry in Pipe chapter of tutorial

### ISSUE THREAD

**Issue by herwinw** [roc-lang/roc#5556]
https://www.roc-lang.org/tutorial#the-pipe-operator

The last section in the chapter says "All three of the following do the same thing", but only lists two items. Given the context of the chapter, I would assume it was supposed to be either `first |> Num.div second` or `first |> / second` (with newlines before the pipe operator).

**Comment by herwinw** [comment]
I stand (slightly) corrected: the syntax of `|> / second`  currently raises a `TrailingOperator` panic, so that shouldn't be added to the tutorial.

**Comment by Anton-4** [comment]
Thanks for raising this issue @herwinw, I've fixed it in #5563
