### ISSUE TITLE
Roc format command fails with list pattern matching "[.. as foo]" syntax

### ISSUE THREAD

**Issue by Hasnep** [roc-lang/roc#5570]
The auto-formatter seems to have a bug with the `[.. as foo]` syntax

## Example

In this example, the following code:

```
interface Example exposes [parseNumber] imports []

parseNumber = \numberStr ->
    (sign, digitsGraphemes) = when Str.graphemes numberStr is
        ["-", .. as justTheDigits] -> (Negative, justTheDigits)
        justTheDigits -> (Positive, justTheDigits )
    # Just return what we have so far as an example
    {sign, digits}

expect
    parseNumber "123" == {sign: Positive, digits: ["1","2","3"]}


expect
    parseNumber "-123" == {sign: Negative, digits: ["1","2","3"]}
```

Has this problem with the first branch of the `when`:

<details>
<summary>AST before</summary>
<pre>
List(
    [
        StrLiteral(
            PlainLine(
                "-",
            ),
        ),
        ListRest(
            Some(
                (
                    [],
                    PatternAs {
                        spaces_before: [],
                        identifier: @174-187 "justTheDigits",
                    },
                ),
            ),
        ),
    ],
), 
</pre>
</details>

<details>
<summary>AST after</summary>
<pre>
List(
    [
        StrLiteral(
            PlainLine(
                "-",
            ),
        ),
        ListRest(
            Some(
                (
                    [],
                    PatternAs {
                        spaces_before: [],
                        identifier: @162-175 "justTheDigits",
                    },
                ),
            ),
        ),
    ],
),
</pre>
</details>

The difference is with the identifier used for the alias.

I'm using the latest nightly build: `roc nightly pre-release, built from commit 0f327d9 on Sa 17 Jun 2023 09:25:17 UTC`

**Comment by JRI98** [comment]
No longer reproduces
