### ISSUE TITLE
nightly error: cannot find `wasi-libc.a`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5573]
```
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'cannot find `wasi-libc.a`', crates/compiler/build/src/link.rs:126:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Explanation from Brian Carroll:
>When we build the compiler from source, wasi-libc.a is created somewhere inside Cargo's target directory, and we set an environment variable equal to that path. The path is then compiled into some of the other crates in the compiler. (There's also a second file called compiler-rt.o.)
Later when we run the compiler with --target=wasm32, it will try to find those files to link them with the user's Roc code.
My guess is that our nightly build does not copy wasi-libc.a and compiler-rt.o into the bundle.
So basically right now Wasm targets won't work with nightly builds... unless you happen to have these files at the exact same directory paths as the machine where the nightly build was run!
However this is solvable and we have solved it in other places. For example we have object files for builtin functions that we also link with user code. So maybe there's a similar approach we can take in this case.

**Temporary workaround:**

Building from source should prevent this issue. Make sure you have [nix installed](https://nixos.org/download.html).
```
git clone https://github.com/roc-lang/roc.git
cd roc
nix develop
cargo build --release --bin roc
./target/release/roc build your_roc_file.roc
```

**Comment by brian-carroll** [comment]
What do we actually do for the builtins object files? Do we copy them into the nightly? Where is the script that does that?

**Comment by Anton-4** [comment]
We copy the zig files for the builtins in [this script](https://github.com/roc-lang/roc/blob/main/ci/package_release.sh). I think we used to copy the object files but @bhansconnect said that was a bad idea.

**Comment by brian-carroll** [comment]
OK so I guess that means that when you install Roc via nightly build, we require you to also install Zig.
We also use Zig to get wasi-libc.a, so maybe we can use that.
Do we require you to install Rust too, or just Zig?

**Comment by Anton-4** [comment]
Hmm, we actually don't require zig to be installed, [here](https://github.com/roc-lang/roc/blob/main/.github/workflows/test_nightly_many_os.yml) the rust example works before I install zig. I'm not sure how it all fits together, can you help us out @bhansconnect?

**Comment by matekdk** [comment]
FYI: I get the same error as of 30th october 2023:

```
roc build  --target=wasm32 rocLovesWebAssembly.roc
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'cannot find `wasi-libc.a`', crates/compiler/build/src/link.rs:127:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
zig version
0.11.0
```

```
roc version
roc nightly pre-release, built from commit cb00cfb on Mon Oct 30 09:19:21 UTC 2023
```

```
rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)
```

```
uname -v
Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
```

**Comment by Anton-4** [comment]
Thanks for your report @matekdk :)
In case it may help, I just now edited the original issue comment to include a clearly visible workaround.

**Comment by skyqrose** [comment]
Completed by #6834
