### ISSUE TITLE
Zero-Sized values in code gen

### ISSUE THREAD

**Issue by folkertdev** [roc-lang/roc#559]
We ran into some issues with lists of elements with size zero, for instance `[ {}, {} ]`. What should the runtime representation of the list be here? How is `List.get` supposed to work

**Comment by rtfeldman** [comment]
@folkertdev is this still an issue?

**Comment by folkertdev** [comment]
not this case. Zero-sized types and our builtins probably have additional bugs but the fuzzing will take care of them eventually
