### ISSUE TITLE
Unexpected panic in REPL

### ISSUE THREAD

**Issue by Ivo-Balbaert** [roc-lang/roc#5599]
(tested on WSL: Ubuntu 22 and Windows)

» Str.fromInt 42
correctly gives the error:

── NOT EXPOSED ─────────────────────────────────────────────────────────────────

The Str module does not expose `fromInt`:

» Str.concat "abc" Str.fromInt 42
also correctly gives a NOT EXPOSED and TOO MANY ARGS errors

Adding parentheses around (Str.fromInt 42) causes a panic:
» Str.concat "abc" (Str.fromInt 42)

"\xa0B\xd4U;\x7f"
thread 'main' panicked at 'Roc hit an error', crates/repl_cli/src/cli_gen.rs:133:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

On Windows, this also panics, but with a different message so probably different cause:
»        Str.concat "abc" (Str.fromInt 42)
warning: ignoring debug info with an invalid version (0) in
thread 'main' panicked at 'extern function roc_mmap is not defined by the builtins', crates\compiler\gen_llvm\src\llvm\externs.rs:176:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Anton-4** [comment]
Thanks for reporting this @Ivo-Balbaert, I've confirmed that this also happens on NixOS.

**Comment by folkertdev** [comment]
Does this still reproduce?

**Comment by Anton-4** [comment]
It does not :tada:
