### ISSUE TITLE
inform users about feature differences with local repl

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5603]
Underneath [this line](https://github.com/roc-lang/roc/blob/addd513528b64326d26658549a045647ae7a0f44/www/public/repl/index.html#L12) we should add a paragraph stating: "This web repl misses some features that are available in the CLI (`roc repl`) like defining variables without a final expression, that will result in the "Missing Final Expression" error."

**Comment by KekmaTime** [comment]
i would like to work on this issue

**Comment by Anton-4** [comment]
Thanks @KekmaTime :) I've assigned you to the issue, feel free to request me as reviewer for your PR.

**Comment by KekmaTime** [comment]
@Anton-4 Ive opened a PR can you check it?
