### ISSUE TITLE
Duplicate printing of ability constraints

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5621]
I don't have a repro for this, but writing it down so it doesn't get lost.

The symptom I saw was in an error message, and it printed out something like:

```
Expected:

    Dict k a -> Dict k b | k has Hash & Eq, k has Hash & Eq
```

So there were two different types (`Dict k a` and `Dict k b`) but the ability constraints on their shared type variable `k` should only have been printed once.

**Comment by Ivo-Balbaert** [comment]
Hi Richard. I suspect this is a duplicate of:
Ability constraints printed multiple ties for same type variable #4914, can they be merged and one of them closed?

**Comment by rtfeldman** [comment]
I think so, thanks!
