### ISSUE TITLE
What is the concurrency model, or how it will look in the final product?

### ISSUE THREAD

**Issue by D4no0** [roc-lang/roc#5640]
I am a beginner here so bear with me, I am not sure this is the best place to ask, however there doesn't seem to be other communication channels mentions in readme.

I will start by the fact that I am not a big fan of JS and never used the async/await constructs in a complex real-world application, but I can tell from the fact when I have to read JS from time to time, that the approach is a mess. I saw in a few demos usage of async/await model and it was interesting to me if you want to pursue that path also. Elm uses it because it is ultimately constrained by the JS it is transpiled into, however in the case of roc you have full freedom of choice.

So my question is: is there a big advantage for using a async/await approach instead of a actor-based or a similar model?

Languages like go, that employ in their way the idea of passing messages around concurrent constructs seems to be very successful and from my personal experience of writing elixir in production (the processes from elixir work on same basis as actors) it seems a much better approach for designing systems and debug them.

**Comment by Anton-4** [comment]
Hi @D4no0,

> however there doesn't seem to be other communication channels mentions in readme.

There is a link to our [group chat](https://roc.zulipchat.com/) in our README, I've tried to make it stand out more in PR #5641 , preview [here](https://github.com/roc-lang/roc/blob/626ca609b8ea6d32f4be04f8d1788248d0fd765b/README.md). Let me know if that could be further improved.

The ideas stream on our group chat is the best place to ask your question.
I have not worked on it personally but I believe we are indeed going for async/await.
I too am a big fan actors and message passing so I'm curious about the answer to your question as well :)

**Comment by D4no0** [comment]
Aaah I see it now, thanks!
