### ISSUE TITLE
Problem compiling Tutorial example: Optional Record Fields

### ISSUE THREAD

**Issue by Ivo-Balbaert** [roc-lang/roc#5653]
I love how the Tutorial has expanded the last year!

I came across a problem in the section mentioned above. I first showed it on Zulip, and it was suggested to make it into an issue.
All variations on the following code:
```coffee
main =
   # dbg table { height: 100, width: 150, title: "a", description: "b" }
   # dbg table {100, 150, "a", "b"}
   # Stdout.line "\(table {100, 150})"
   Stdout.line "the end"

table : { height : Num, width : Num, title ? Str, description ? Str } -> Str
table = \{
        height,
        width,
        title? "oak",
        description? "a wooden table"
    }
    -> "abc"
```

give the following compiler error (compiling hangs):
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Any other pattern should have given a parse error', crates/compiler/can/src/pattern.rs:737:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Here is the stack backtrace:
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: roc_can::pattern::canonicalize_pattern
   3: roc_can::scope::Scope::inner_scope
   4: roc_can::def::canonicalize_pending_body
   5: roc_can::def::canonicalize_value_defs
   6: roc_can::module::canonicalize_module_defs
   7: roc_load_internal::file::run_task
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}

**Comment by Ivo-Balbaert** [comment]
A workaround for this issue suggested by Kilian Vounckx in Zulip is writing all arguments on one line, like:

table = \{ height, width, title? "oak", description? "a wooden table" }
    -> "abc" 

Clearly the problem is a parsing bug on the arguments not on one line. I will leave it open, unless it is decided that the tutorial format is not valid. In that case, this issue can be closed and the tutorial adapted.

**Comment by rtfeldman** [comment]
Definitely a bug - thanks for the compact reproduction!
