### ISSUE TITLE
Add `clippy` and `fmt` aliases to flake.nix for use in development

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5659]
`clippy` should execute: `cargo clippy --workspace --tests --release -- --deny warnings`

`fmt` should execute: `cargo fmt --all`

**Comment by kadinsayani** [comment]
Hi, I've opened a [PR](https://github.com/roc-lang/roc/pull/5677) for this issue.

**Comment by Anton-4** [comment]
Thanks @kadinsayani :)
