### ISSUE TITLE
docs css: add border to module functions/types in nav

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5750]
We have these borders on the left of types/functions:
![Screenshot_20230811_112943](https://github.com/roc-lang/roc/assets/17049058/ec915744-0372-43a5-b6d2-15fb9b7cfdc6)

I'd like to add a very similar border on the left of the indented types/functions in the navbar as well:
![Screenshot_20230811_115842](https://github.com/roc-lang/roc/assets/17049058/e4f78c6d-1a5b-45b6-b232-f222da47181e)

The indentation alone does not make it stand out enough.

**Comment by jakub-c** [comment]
@Anton-4 are you thinking about something looking like the proposal attached to this post?
![left border proposal](https://github.com/roc-lang/roc/assets/29469/705d7c07-b5d5-42c2-8bd5-b7831c708e3b)

**Comment by Anton-4** [comment]
Yes, looks good @jakub-c!

**Comment by jakub-c** [comment]
@Anton-4 PR opened: #6091
