### ISSUE TITLE
Putting `.1` into the repl crashes it

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5759]
```
  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» .1
thread 'main' panicked at 'Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("mainForHost"), definition of value binding ValueId(4): could not find func in module ModName("UserApp") with name FuncName("\x00\x00\x00\x00\x10\x00\x00\x00LM\x9e\xcf\x072\x00\xf9")', crates/compiler/gen_llvm/src/llvm/build.rs:5096:19
```

**Comment by kukimik** [comment]
This is currently parsed as a tuple field accessor (in the online REPL):

```
» .1

 : ( a )* -> a
```

Looks like this issue is no longer relevant and can be closed? (Note however that this syntax may be somewhat confusing to newcomers, who may expect `.1` to be parsed as the number `0.1`.)

**Comment by Anton-4** [comment]
> Looks like this issue is no longer relevant and can be closed? 

Thanks @kukimik! I am still hitting an issue with this on the local REPL, but it produces a different error message, so I'll make a new issue for that.

> Note however that this syntax may be somewhat confusing to newcomers, who may expect .1 to be parsed as the number 0.1.

True, I can't think of a good solution to that right now though... :thinking:

**Comment by Anton-4** [comment]
I created #6721 for my issue.
