### ISSUE TITLE
Repl prints <function> when there's a crash

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5807]
To reproduce:

```
  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» (Num.toU32 -1) + 1
This Roc code crashed with: "integer addition overflowed!"

<function> : U32          # val1

»
```

Instead, it should report the crash and then take you back to the prompt.

**Comment by folkertdev** [comment]
basically the same as https://github.com/roc-lang/roc/issues/6066

**Comment by skyqrose** [comment]
#6066 has more details, so I'm closing this issue in favor of that one.
