### ISSUE TITLE
repl prints negative dec values incorrectly

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#5813]
Run in repl:
```
» -123.45dec

-1234.5 : Dec             # val1
```

Note how the decimal point is in the wrong location. This is a printing bug. The decimal has the correct value. This can be seen by:
```
» -1 * -123.45dec

123.45 : Dec              # val1
```

**Comment by bhansconnect** [comment]
Note, this is not an issue with the Num.toStr builtin when applied to dec. This is specifically an issue in the repl printing code (which should be in rust)

**Comment by sekerez** [comment]
I just posted a PR addressing this!
