### ISSUE TITLE
Add `pow` support for `Dec`

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#5828]
This implementation will basically be the same as power for integers, but using dec multiplication. It is important to use dec multiplication and constants or we will have issues with the wrong power. We can not simply call `math.powi` on the underlying `i128`. Overall, will just be reimplementing [math.powi](https://ziglang.org/documentation/master/std/src/std/math/powi.zig.html) with dec constants and math operators.

**Comment by JRI98** [comment]
Fixed by https://github.com/roc-lang/roc/pull/6463?
