### ISSUE TITLE
Support dbg as expression

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5894]
Right now you can do:
```
main =
    dbg "hey"
    Stdout.line "Hello, World!"
```

But we also want to support the following:
```
main =
    Stdout.line (dbg "Hello, World!")
```
So `dbg` will print "Hello, World!" and pass on the value it was provided.

This is particularly useful for quickly debugging pipeline steps:
```
myList
|> List.map Num.toNat
|> List.sum
|> dbg
|> Num.toStr
```

`dbg` should not be a function, for example `List.map list dbg` should not work.

**Comment by Anton-4** [comment]
Code that appropriately detects when dbg is used as a statement or expression may be a bit tedious, perhaps we should temporarily use dbge for the expression variant and "merge" them later to dbg.

**Comment by mulias** [comment]
@Anton-4 this should be fully implemented now!
