### ISSUE TITLE
Remove all `val<number>` references in Tutorial

### ISSUE THREAD

**Issue by ryanb** [roc-lang/roc#6001]
I'm going through the [Roc Tutorial](https://www.roc-lang.org/tutorial) and it has me enter `val1` in the [Naming Things]() section, but I get the "Nothing is named `val1` in this scope." error.

```
% roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» "Hello World"

"Hello World" : Str
» val1

── UNRECOGNIZED NAME ───────────────────────────────────────────────────────────

Nothing is named `val1` in this scope.

4│      val1
        ^^^^
```

I'm on the latest nightly build.

```
% roc --version
roc nightly pre-release, built from commit afba365 on Fri Nov 17 09:08:42 UTC 2023
```

**Comment by Anton-4** [comment]
The auto declaring/naming with valX is a repl feature that has been removed. All references to it should be removed from the tutorial.

**Comment by lukewilliamboswell** [comment]
This issue has been resolved, there are no longer any references to `val` in the tutorial.
