### ISSUE TITLE
WIP website repl is not responsive after a parser error

### ISSUE THREAD

**Issue by JRMurr** [roc-lang/roc#6009]
I entered this expression and had an accidental typo of 

```
» 0.1 + 0,2
panicked at 'not yet implemented: unhandled parse error: Pattern(IndentEnd(@82), @81)', crates/reporting/src/error/parse.rs:673:14

Stack:
<trace ommited>
```

after that typing new expressions in the repl would not be printed/evaluated until I did a page reload

**Comment by Anton-4** [comment]
Thanks @kukimik!

> Is it feasible to solve this in general, or only case-by-case?

It's possible but it will take significant effort to set up better error handling all over the place. I made #6722 for this.
