### ISSUE TITLE
Tutorial/docs: explain functional purity  and how to do the equivalent of void/unit functions

### ISSUE THREAD

**Issue by faldor20** [roc-lang/roc#6017]
Explain functional purity and it's implications better:
Searching for the word "unit" and "void" in the tutorial returns no results. I think this is a significant issue given roc doesn't allow this super fundamental feature of most languages. 
My first experience running roc code went as follows:
1. Use Stdout.line to print hello world.
2. 
Write this
```elm
main=
  Stdout.line "hi"
  Stdout.line "hello"
```
3. Spend half an hour reading through examples, docs and stuffing around complying broken stuff to try to figure out the accepted method of running two print statements. 

The tutorial should contain a section on purity and one that very specifically explains how you would do the kinds of things you would use void returning functionss for normally.

**Comment by Anton-4** [comment]
Hi @faldor20,
I'm sorry to hear you had a frustrating experience.
We've been discussing various ways to prevent this and I was wondering what exactly you meant with "compiling broken stuff". Were examples not working or were you trying stuff and hitting type errors or ...?

**Comment by faldor20** [comment]
oh no, the examples were fine, just me trying things that seemed logical and it not working, like trying to set the return type to some kind of void/unit type, and changing bits to try to figure out why the type signature was the way it was, that sort of thing.

**Comment by lukewilliamboswell** [comment]
@faldor20 could you please read through the [Task & Error Handling Example](https://www.roc-lang.org/examples/Tasks/README.html) and let me know if that resolves this issue?

Is there anything further we could/should do to improve this experience for other users?

**Comment by faldor20** [comment]
I think it mostly covers it but I would really love to see a little section that highlights an example with the format:
```elm
Writeline "This is a roc program. what's your name?"
Readline
Writeline "hi, \name "
Writeline "I'm done, bye"
```
(Written on my phone, so you only get sudocode, sorry)

This is the kind of program most beginners in a programming language learn to write, just some input, and output, it demonstrates multiple tasks, and clearly shows the how to do the roc version of void/null calls. I know you mention void/null but an example that focuses on that would really help.

**Comment by skyqrose** [comment]
Since this issue was opened, Roc got the `!` operator to chain together effects, and there's the in-progress Purity Inference plan which will make writing functions that run effects way easier. As part of that, all the tutorials and docs will need to be updated anyway. The purity inference plan isn't done yet, but this issue isn't needed for tracking this idea anymore. Marking the issue as complete.
