### ISSUE TITLE
Nightly does not bundle `wasi-libc.a`

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#6029]
When building wasm platforms, we link in `wasi-libc.a`. This currently only works if you built the compiler from source. We should make this also just work when compiling with nightlies.

Should be a matter of include `wasi-libc.a` in the nightlies and then setting `WASI_LIBC_PATH` correctly. I believe it currently comes from an environment variable or default path.

**Comment by rgripper** [comment]
https://github.com/roc-lang/roc/issues/6029

**Comment by skyqrose** [comment]
Completed by #6834
