### ISSUE TITLE
Feature Request - Jump to Top button on Website pages

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#6073]
When scrolling through the website sometimes I want to jump to the top of the page. I would like a button to appear after scrolling that returns my window to the top of the page when I click it.

*edit* relevant [zulip discussion](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Website.20Back.20to.20Top/near/403863509)

**Comment by lsculv** [comment]
When I've been going through the website tutorial/std lib docs most of the time I want to jump back to the top is to get the table of contents to jump to another section/function. It might be useful to make the table of contents always visible as you scroll (or tucked in a menu that is always visible as you scroll) to make this easier. This would be in addition the the top of page button, which I think is also a good idea.

**Comment by dotslashbit** [comment]
Is this issue still exist??

**Comment by Anton-4** [comment]
It might be hard to place this button well when the site is in a narrower window or on mobile. I'm closing for now but we can reconsider if more people want it.
