### ISSUE TITLE
`--stdin` flag in `roc format` not behaving correctly

### ISSUE THREAD

**Issue by CrepeGoat** [roc-lang/roc#6088]
# setup to reproduce
- system - aarch64-darwin (M1 macbook air); macOS 13.4.1
- install the Roc compiler via
    ```sh
    nix shell github:roc-lang/roc/3d8884a96d44e2101ce8932336b74e2b9416e029
    ```
- create a basic roc file with proper Roc syntax but improper formatting, like `test.roc`:
    ```coffeescript
    app "hello"
        packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
        imports [pf.Stdout]
        provides [main] to pf
    



    main = Stdout.line "I'm a Roc application!"
    ```

# working action
```sh
roc format --stdout test.roc
```
produces this in stdout (note the several sequential line returns are reduced to 2):
```coffeescript
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main = Stdout.line "I'm a Roc application!"
```

# buggy action
IIUC this command *should* produce the same results as described above, but instead passes to stdout the *unformatted* content:
```sh
cat test.roc | roc format --stdin --stdout
```

**Comment by Anton-4** [comment]
I think in [this line](https://github.com/roc-lang/roc/blob/668a9d363d0350002b487f2501444f5aa684f99e/crates/cli/src/main.rs#L336C68-L336C71) we need to use `formatted_src` instead of `src`. I'll make this a "good first issue" for someone willing to test my suggestion and do a PR.
