### ISSUE TITLE
Improve error message when platform url is wrong

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6109]
I introduced a typo in the url on purpose, 0.6.0/OQW... should be 0.6.0/QOQW..., the error should be a lot more specific here than "failed to iterate over archive".
```
 ── IO ERROR ────────────────────────────────────────────────────── UNKNOWN.roc ─

I was trying to download this URL:

    https://github.com/roc-lang/basic-cli/releases/download/0.6.0/OQW08n38nHHrVVkJNiPIjzjvbR3iMjXeFY5w1aT46w.tar.br

But I encountered an IO (input/output) error:

    failed to iterate over archive 
```

**Comment by zapsh** [comment]
I'd be willing give this a go if nobody is already working on it

**Comment by Anton-4** [comment]
Awesome, thanks @zapsh :)
I've assigned you to the issue

**Comment by mainrs** [comment]
I am looking for some `good-first-issue` labeled issues and found this one, which has already been solved. Can be closed! @Anton-4
