### ISSUE TITLE
Export multiple symbols to the platform

### ISSUE THREAD

**Issue by ostcar** [roc-lang/roc#6115]
Currently, an roc app can only provide one symbol (for example main) to the platform.

It would be nice, if multiple symbols could be provides.

See [this zulip post](https://roc.zulipchat.com/#narrow/stream/302903-Writing-a-platform/topic/Can.20a.20platform.20require.20and.20provide.20more.20then.20one.20synbol.3F).

**Comment by folkertdev** [comment]
sure, we have this enum already

```rust
#[derive(Debug, Clone, Copy)]
pub enum EntryPoint<'a> {
    Single(SingleEntryPoint<'a>),
    Expects { symbols: &'a [Symbol] },
}
```

where `Single` triggers a bunch of functions to be generated and exposed to the host, and `Expects` already deals with multiple symbols. I think it's as easy as adding a third variant to this enum that sort of combines the two, and then see where the errors lead you.

**Comment by skyqrose** [comment]
Done in https://github.com/roc-lang/roc/pull/7147
