### ISSUE TITLE
`when ... is` should be a parse error if the body isn't tabbed.

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#6155]
This is valid currently:
```coffee
    when color is
    Red -> (value, g, b)
    Green -> (r, value, b)
    Blue -> (r, g, value)
```

It probably shouldn't be. We probably want to require that the body of the `when ... is` is tabbed in compared tot the rest of the function.

**Comment by bhansconnect** [comment]
this is probably a good first issue, but I don't know the parser enough to know for sure.

**Comment by Anton-4** [comment]
This may be a deliberate decision by @joshuawarner32, I know he likes the parser to be lenient.

**Comment by joshuawarner32** [comment]
I've been chatting with @rtfeldman recently about how we can make the parser mostly or completely indentation-agnostic  (so long as it's not ambiguous or likely to cause user confusion) - and rely on the auto-formatter to confirm communicate to the user how the compiler is interpreting the syntax. So - yes, that's loosely the direction I've been thinking in.

That said, glancing at the code, I'm a little fuzzy on why this is happening. The code seems to be wanting at least one space there.

**Comment by lukewilliamboswell** [comment]
Closing for now as this is behaving in the intended way -- it is parsing and formatting as Josh described.

@bhansconnect let me know if you think this is incorrect, and we can re-open.

```
main = 
    color = Red
    msg = 
        when color is
        Red -> "(value, g, b)"
        Green -> "(r, value, b)"
        Blue -> "(r, g, value)"

    Stdout.line msg
```
Formats to...
```
main =
    color = Red
    msg =
        when color is
            Red -> "(value, g, b)"
            Green -> "(r, value, b)"
            Blue -> "(r, g, value)"

    Stdout.line msg
```
