### ISSUE TITLE
x64 and ARM backends don't do overflow checking for arithmetic

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#6169]
This can be reproduced in `roc repl`, which now uses the x64 and ARM backends:

```
» 1u8 - 2

255 : U8
```

The web repl correctly reports a crash, as does normal `roc build` / `roc run`.

**Comment by rtfeldman** [comment]
Awesome, thank you @horriblename! 😃 

If you have any questions about anything, feel free to ask in https://roc.zulipchat.com/#narrow/stream/316715-contributing/ !

**Comment by shua** [comment]
Tried this today on my x86 machine and it seems to work ok:
```
» 1u8 - 2
This Roc code crashed with: "Integer subtraction overflowed!"
```

there's also a test `gen_num::int_sub_overflow` that checks something like this for the all the backends.

I'm not certain the gen-dev aarch64 backend does this correctly, as `cargo build --target aarch64-unknown-linux-gnu` fails locally for me so I can't test.

**Comment by lukewilliamboswell** [comment]
The original issue linked here doesn't repro for me either. I think it's ok to close.
