### ISSUE TITLE
Ignore changes to AUTHORS file for ci-manager

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6179]
See [this line](https://github.com/roc-lang/roc/blob/a187d141bd881e3515133ee484fb8ffa1ba790e8/.github/workflows/ci_manager.yml#L24)

**Comment by dotslashbit** [comment]
Is this still open?

**Comment by Anton-4** [comment]
This has been handled, thanks for alerting us @dotslashbit!
