### ISSUE TITLE
bug: constructor can never align with a literal

### ISSUE THREAD

**Issue by kwando** [roc-lang/roc#6187]
I'm just trying to wrap my head around how to use Task so the following code might not even make sense, but the compiler told me to log an issues so here we are :)
```
app "helloWorld"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br" }
    imports [
      pf.Stdout,
      pf.Env,
      pf.Task.{ Task },
      pf.Path.{ Path },
    ]
    provides [main] to pf



main =
  Task.await Env.cwd \result ->
    when result is
      InternalPath.InternalPath ->
        Stdout.line "current directory: \(result |> Path.display)"
      CwdUnavailable ->
        Stdout.line "could not lookup current directory"
```
 running that with `roc dev` or `roc run` explodes like this:
 ```
 An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'After type checking, a constructor can never align with a literal: that should be a type error!', crates/compiler/exhaustive/src/lib.rs:637:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Roc version
```
❯ roc --version
roc nightly pre-release, built from commit a187d141bd8 on Mon Dec  4 09:19:54 UTC 2023
```

Bonus points if someone can write the correct version of that main function. I'm just guessing wild at this point.

**Comment by AsbjornOlling** [comment]
I can't fix the compiler bug, but I *can* fix your roc code ;)

I'd do something like this:

```roc
main : Task {} I32
main =
    Task.await Env.cwd \path ->
        Stdout.line "current directory: \(Path.display path)"
    |> Task.mapErr \_ -> -1
```

...or a bit more verbosely, to specifically handle the cwd error:

```roc
main : Task {} I32
main =
  # wrap Env.cwd so it fails with I32
  errWrappedCwd = Task.onErr Env.cwd \_ ->
    _ <- Task.await (Stdout.line "something went wrong...")
    _ <- Task.await (Stdout.line "failed getting current working directory")
    Task.err -1

  # await and print
  path <- Task.await errWrappedCwd
  Stdout.line "current directory: \(Path.display path)"
```

**Comment by kwando** [comment]
Thank you  @AsbjornOlling!  I see where my thinking failed me now. The callback to `Task.await` is called with the path (`Path`) and not _something_ I should pattern match on to get the path out.

This was very helpful! :)

**Comment by Anton-4** [comment]
For record keeping: this is possibly related to #6180

**Comment by skyqrose** [comment]
There are plans to change a ton of stuff about how Tasks are handled. In particular, effectful functions will return a result (like you tried to do in the original incorrect code) instead of having separate success and error types. So even if this bug isn't fixed when all that code is rewritten, this reproduction won't be useful anymore. And also this might be covered by that other issue. So I'm closing this issue.
