### ISSUE TITLE
`roc check interface.roc` hangs on certain interface imports

### ISSUE THREAD

**Issue by CrepeGoat** [roc-lang/roc#6200]
# repro example

- Roc version `github:roc-lang/roc/dc37b7a31d4fa2014ec159eda1d51c27832ddca6`
- run on macOS 13.4.1 arm64 (M1 macbook air)

## main.roc
```coffee
app "day4"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
        parse: "https://github.com/lukewilliamboswell/roc-parser/releases/download/0.3.0/-e3ebWWmlFPfe9fYrr2z1urfslzygbtQQsl69iH1qzQ.tar.br",
    }
    imports [
        pf.Stdout,
        pf.Task,
        ParseInput.{
            parse,
        },
    ]
    provides [main] to pf

main : Task.Task {} I32
main =
    Stdout.line "parse: \(parse)"
```

## ParseInput.roc
```coffee
interface ParseInput
    exposes [parse]
    imports [
        # if I keep some import here, `roc check ParseInput.roc` hangs
        # but if I *remove* this import, everything works
        # (the actual thing imported from parse doesn't seem to matter)
        parse.Core.{ Parser },
    ]

parse = "hello"
```

# problem behavior
when running `roc check ParseInput.roc` the command hangs until forcibly quit.

# expected behavior
`roc check ParseInput.roc` should either error with a descriptive error message, or pass and generate the intended results. Either way, the program should not hang.

# debugging
this code will NOT hang when:
- running `roc check` or `roc check main.roc`
- removing the imports from `ParseInput.roc` and running `roc check `

**Comment by CrepeGoat** [comment]
duplicate of https://github.com/roc-lang/roc/issues/6185?

**Comment by AsbjornOlling** [comment]
> related to #6185?

I think this is unllikely, since #6185 also hangs on `roc check`
