### ISSUE TITLE
`Num.floor` not implemented for `Dec`

### ISSUE THREAD

**Issue by ryanb** [roc-lang/roc#6212]
I'm unable to do `Num.div` and `Num.floor` in the repl.

```
» Num.div 10.0 2.0
thread 'main' panicked at 'not yet implemented: NumDiv: layout, Builtin(Decimal)', crates/compiler/gen_dev/src/generic64/mod.rs:1612:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

» Num.floor 3.14
thread 'main' panicked at 'not yet implemented: low level, NumFloor', crates/compiler/gen_dev/src/lib.rs:1924:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Division seems to work in `roc dev` but I'm seeing a panic on `Num.floor` in `roc dev`.

```
thread 'main' panicked at 'internal error: entered unreachable code: Unrecognized dec unary operation: NumFloor', crates/compiler/gen_llvm/src/llvm/lowlevel.rs:2318:13
```

This is on the latest nightly build on Apple Silicone.

```
roc nightly pre-release, built from commit 9889984dd48 on Wed Dec  6 09:18:32 UTC 2023
```

Am I doing something wrong?

**Comment by lukewilliamboswell** [comment]
I don't think you are doing anything wrong, those functions just arent implemented yet in the dev backend for arm64. It shouldn't be difficult to add if you are interested in diving into that part of the compiler.

For context the arm64 dev backend is quite new, previously the REPL was using LLVM but the plan is to move everything across to the dev backends for improved speed while developing.

**Comment by bhansconnect** [comment]
There are a few things that we may have changed too early:
1. We change the repl to the dev backend, but it is still missing features
2. We changed the default Fractional type to `Dec`, but it doesn't support everything `F32` does.


`Frac` is a wrapper type that can be a `Dec`, a `F32`, or a `F64`. It defaults to `Dec` now.

**Comment by ryanb** [comment]
@bhansconnect thanks for clarifying. It makes more sense now.

Is there a way to configure which backend the `repl` uses? Ideally the repl would match `roc dev` so I can use it to debug issues.

**Comment by bhansconnect** [comment]
I don't think that is supported currently. @folkertdev is there any way to still use the llvm backend with the repl?

**Comment by folkertdev** [comment]
https://github.com/roc-lang/roc/pull/6339 fixes the `Num.div`. `Num.floor` is still unimplemented for decimals though
