### ISSUE TITLE
`An internal compiler expectation was broken` with surgical linker,` Integer subtraction overflowed!` with legacy linker

### ISSUE THREAD

**Issue by JRMurr** [roc-lang/roc#6245]
When working on AoC day 10 i got this error (minor spoilers for it...)

```
> roc dev -- 10 1 1
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+96e5, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+7b9)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "__udivti3", address: +0, size: +0, kind: Label, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1486:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If i try to use the legacy linker i get 

```
Running Part 1...[D10/Day.roc:79] [Vertical, SouthEast, SouthWest]
[D10/Day.roc:79] [Vertical, NorthEast, NorthWest]
[D10/Day.roc:79] [Horizontal, NorthEast, SouthEast]
Roc crashed with:

	Integer subtraction overflowed!

Here is the call stack that led to the crash:

	.libc
	.libc
```

The area causing pain seems to be [here](https://github.com/JRMurr/AdventOfCode2023/blob/76351687d04eef9e7eca19328ee1b4f166e0c913/roc/D10/Day.roc#L77) (permalinked to the commit with the issue)

I assume the issue is related to me passing around function references but not positive. Trying to work around this issue atm. Will update if i find one

**Comment by JRMurr** [comment]
Looks like the `Integer subtraction overflowed!` is an actual bug in my logic since i was doing `0-1` so most likely just a surgical linker error

**Comment by JRMurr** [comment]
Looks like the issue was fixed by me rolling back my roc version to an older commit. I was on `f795d0856a8a68747aa7bc975827bd02ff8d4610` and saw this issue. I rolled back to `bccfdde63af8e37918b259023af4e159b12ad52e` and that seemed to fix it

**Comment by Anton-4** [comment]
I expect the `Undefined symbol in relocation` will be fixed by https://github.com/roc-lang/roc/pull/6270.

**Comment by JRMurr** [comment]
Updated to the latest roc in my AOC repo and the issue is fixed!
