### ISSUE TITLE
Add the FAQ to the website

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6260]
This is currently in FAQ.md in the repo.
The faq page should be linked where we currently have "Frequently Asked Questions" on the docs page.
Changes should be made in the www folder on the repo.

**Comment by oranjan** [comment]
hi, can I work on this ?

**Comment by lukewilliamboswell** [comment]
Sure, let us know if you need a hand with anything.

**Comment by dotslashbit** [comment]
@oranjan are you still working on it?? If not I would like to work on it

**Comment by dotslashbit** [comment]
Needed some clarifications, there's already a link to the FAQ.md page from the www/content/docs file [file link](https://github.com/roc-lang/roc/blob/main/www/content/docs.md). So, what do you mean by this "The faq page should be linked where we currently have "Frequently Asked Questions" on the docs page."

**Comment by Anton-4** [comment]
The link there should link to a new faq page on the roc-lang website, instead of to github.

**Comment by dotslashbit** [comment]
I have added the faq.md file and now this also creates a faq.html file after build, but I'm unable to add this html file to the website, can you help me with this?

**Comment by lukewilliamboswell** [comment]
You jeed to create a folder over here https://github.com/roc-lang/roc/tree/main/www/content

You can generate the website locally to test it using the build scripts in the www/ folder.

**Comment by dotslashbit** [comment]
What I did is, I created a file called faq.md on the content directory and after running the build script, the website is opening but faq isn't showing up

**Comment by dotslashbit** [comment]
Here's the local build website screenshot
<img width="1393" alt="Screenshot 2023-12-16 at 3 17 32 AM" src="https://github.com/roc-lang/roc/assets/46224156/ce2a7298-5126-4a4f-9c11-6cd25cf63e51">
