### ISSUE TITLE
Prevent CI from running when only comments have changed

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6276]
Currently we do not run CI if [only css, md, html,... files have changed](https://github.com/roc-lang/roc/blob/97727ab422bda9b0c91854bc6bf47666663773a8/.github/workflows/ci_manager.yml#L24).
We should further modify this so that it does not run when only:
- [ ] (doc) comments have changed in rs files
- [ ] (doc) comments have changed in .roc files

**Comment by dotslashbit** [comment]
I'm interested to work on this, but after making changes, how to test it. I don't even know how to check the situation:
where if I modify a comment in a .roc file, the CI is running or not?

**Comment by lukewilliamboswell** [comment]
Are you able to make a PR against your fork of the repository maybe? That might allow you to see if the change trigger the action?

**Comment by Anton-4** [comment]
Yeah, I think with a PR against your fork you can test it.
