### ISSUE TITLE
`roc test --optimize` segfaults when creating a large `List.range`

### ISSUE THREAD

**Issue by CrepeGoat** [roc-lang/roc#6282]
# system
- Roc version `github:roc-lang/roc/dc37b7a31d4fa2014ec159eda1d51c27832ddca6`
- run on macOS 13.4.1 arm64 (M1 macbook air)

# setup
main.roc
```coffee
# references
# - https://github.com/roc-lang/examples/tree/main/examples/CommandLineArgs
app "day"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
    }
    imports [
        pf.Stdout,
        pf.Task,
    ]
    provides [main] to pf

main : Task.Task {} I32
main =
    Stdout.line "result: big shrug my guy"

expect
    # v Problem here!
    _range = List.range { start: At 1, end: Length 1000000000 }
    # ^
    0 == 0
```

# problem
Running `roc test --optimize` terminates with the message `zsh: segmentation fault  roc test --optimize`.

# expected behavior
The program should not segfault. A better behavior would be to build the program and execute the test code, or emit a compiler error if this is not supported.

# debugging

- this doesn't happen without the `--optimize` flag; `roc test` runs the test as expected
- the critical value at which the segfault occurs on my machine seems to be `536870911` = `2 ** 29 - 1`. I.e., for `N = 536870911`:

    ```coffee
    expect
        _range = List.range { start: At 1, end: Length N }
    ```

    segfaults, but

    ```coffee
    expect
        _range = List.range { start: At 1, end: Length N - 1 }
    ```

    executes without error.

- in narrowing the critical value described above, one execution of `roc test --optimize` produced the error `zsh: bus error  roc test --optimize`. (This only occurred once -> I imagine it isn't easy to reproduce. This is also maybe not related.)

**Comment by bhansconnect** [comment]
Probably a variant of #6213

**Comment by bhansconnect** [comment]
Hmm, though if this is test specific it may be something else. I wonder if test even respects the `--optimize` flag.
