### ISSUE TITLE
Rust `roc_std::Dict` does not match Roc `Dict`

### ISSUE THREAD

**Issue by brian-carroll** [roc-lang/roc#6292]
As @bhansconnect pointed out in #6230 

> Our dictionaries haven't been an associative list in quite a long time.

This means that [crates/roc_std/src/roc_dict.rs](https://github.com/roc-lang/roc/blob/main/crates/roc_std/src/roc_dict.rs) is incorrect and should not be used.

**Comment by skyqrose** [comment]
That file was removed in https://github.com/roc-lang/roc/pull/6894
