### ISSUE TITLE
Bad formatting in FAQ page

### ISSUE THREAD

**Issue by JRI98** [roc-lang/roc#6306]
The heading of the FAQ page https://www.roc-lang.org/faq.html looks like this:

![Screenshot 2023-12-23 at 12 09 14](https://github.com/roc-lang/roc/assets/38755101/01f070e0-f3d5-480b-9ef6-b0ef5e30aaed)

**Comment by Anton-4** [comment]
Haha, that's not supposed to happen, thanks for reporting @JRI98, I'll fix it right now.

**Comment by JRI98** [comment]
Fixed by https://github.com/roc-lang/roc/pull/6307
