### ISSUE TITLE
Language server crashes when typing debug command in vscode

### ISSUE THREAD

**Issue by fwgreen** [roc-lang/roc#6321]
I'm running `roc nightly pre-release, built from commit 4569770c82c on Fri Dec 29 09:12:45 UTC 2023` with the unofficial vscode extension on an M1 Mac.

To reproduce, start a basic project and start typing `dbg`.  The crash comes when you get to the `g`.

```elm
app "bug"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
    }
    imports [
        pf.Stdout, 
    ]
    provides [main] to pf

main =
    dbg #<--- crahses here
    Stdout.line 
        """
        done
        """
```
LS executable path: Some(/Users/francois/Libraries/Roc/roc/roc_lang_server)
LS debug executable path: Some(/Users/francois/Libraries/Roc/roc/roc_lang_server)
You are ready to Roc!Roc language server started
[Info  - 8:23:42 AM] Roc language server initialized.
thread 'main' panicked at 'not yet implemented', crates/reporting/src/error/parse.rs:1421:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 8:23:53 AM] Connection to server got closed. Server will restart.
true
[Error - 8:23:53 AM] Server process exited with code 101.
[Info  - 8:23:53 AM] Roc language server initialized.
thread 'main' panicked at 'not yet implemented', crates/reporting/src/error/parse.rs:1421:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 8:23:54 AM] Connection to server got closed. Server will restart.
true
[Error - 8:23:54 AM] Server process exited with code 101.
[Info  - 8:23:54 AM] Roc language server initialized.
thread 'main' panicked at 'not yet implemented', crates/reporting/src/error/parse.rs:1421:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 8:23:54 AM] Connection to server got closed. Server will restart.
true
[Error - 8:23:54 AM] Server process exited with code 101.
[Info  - 8:23:54 AM] Roc language server initialized.
thread 'main' panicked at 'not yet implemented', crates/reporting/src/error/parse.rs:1421:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 8:23:55 AM] Connection to server got closed. Server will restart.
true
[Error - 8:23:55 AM] Server process exited with code 101.
[Info  - 8:23:55 AM] Roc language server initialized.
thread 'main' panicked at 'not yet implemented', crates/reporting/src/error/parse.rs:1421:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 8:23:55 AM] The roc-lang server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:23:55 AM] Server process exited with code 101.
[Error - 8:23:56 AM] Delivering pending changes failed
TypeError: this.task is not a function
	at /Users/francois/.vscode/extensions/ivandemchenko.roc-lang-unofficial-1.1.2/dist/extension.js:1:249086
```

**Comment by faldor20** [comment]
Interestingly this isn't happening to me on my fork of the server #6134. We should re-check this once that is merged.
I do remember this happening to me at some point in the past though

**Comment by fwgreen** [comment]
This issue was resolved with `roc nightly pre-release, built from commit 448c29353ed on Fri Feb  9 09:13:03 UTC 2024`
