### ISSUE TITLE
Remove heap allocations where possible to increase compiler performance

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#633]
Whenever possible, we should use the bumpalo::Bump for all allocations. This means we should remove functions that generate memory on the heap. For example, [joining an array](https://github.com/rtfeldman/roc/blob/be77d887db2cdf2081c60b325062d7fa39f7e7a3/compiler/parse/src/expr.rs#L1082) or using [format!](https://github.com/rtfeldman/roc/blob/be77d887db2cdf2081c60b325062d7fa39f7e7a3/compiler/parse/src/expr.rs#L1084) will allocate memory on the heap.

An example fix in these cases could be to count how many charters we need, create a buffer with the bumpalo::Bump, and then  push the the characters and formatting into the buffer.

**Comment by rtfeldman** [comment]
I think we're already actively pursuing this enough that we don't need an issue to track it, so I'm just gonna close this! 😄
