### ISSUE TITLE
Rename all instances of `roc_ls` and `roc_lang_server` to `roc_language_server`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6330]
Descriptive names are better :)

**Comment by ayazhafiz** [comment]
Let's go either fully to `roc_language_server` or stick with `roc_ls`. I chose `roc_ls` because it's short and the LS suffix is well known; for example Haskell has hls, Go has gopls, OCaml has ocamllsp. Also, long term people shouldn't be really using this on the frontend; you should favor an editor extension.

**Comment by Anton-4** [comment]
`roc_language_server` is good for me :+1:
I'd guess the LS suffix is well known among experienced programmers but I'd bet it's not very familiar to people with a few years of programming experience or less.

> Also, long term people shouldn't be really using this on the frontend

I agree, but even if `roc_ls` was only used in our code base I would prefer a more descriptive name. I like to remove friction to understanding the code base wherever possible. Only if a name is e.g. used frequently in a small section of code  does the decrease in clutter (because of the shorter name) start to be worth it.

**Comment by B-Teague** [comment]
I wanted to pick this up as my first contribution to roc-lang, but I wanted to ask this first?

For consistency, should I do ```roc_lang_server``` instead of ```roc_language_server```?
website is roc-lang.org
github is repo is roc-lang

Just wanted to confirm before I start making all the changes.

**Comment by ayazhafiz** [comment]
Let's do roc_language_server.

**Comment by Anton-4** [comment]
Thanks for helping out @B-Teague :)
