### ISSUE TITLE
REPL on Website fails to map over a list

### ISSUE THREAD

**Issue by kreibaum** [roc-lang/roc#6334]
Hi! I was happy to see that you have a REPL integrated into the website and gave it a shot:

```plain
Enter an expression to evaluate, or a definition (like x = 1) to use later.
» List.map [1,2,3] (\x -> x*x)

[1, 4, 9] : List (Num *)
» List.map [0.1,0.2,0.3] (\x -> x*x)

JsValue(CompileError: wasm validation error: at offset 12564: type mismatch: expression has type i32 but expected i64
) : 
```

I asked about it in Zulip earlier before reporting it here: https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Question.20on.20the.20Repl.20embedded.20in.20the.20Website/near/410766990

I got quick feedback on the question on Zulip, so thank you for that :-)

**Comment by folkertdev** [comment]
this is not really a web repl problem, but a problem with multiplication for Decimal not being implemented

```
  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

»  List.map [0.1,0.2,0.3] (\x -> x*x)
… 
thread 'main' panicked at 'not yet implemented: NumMulWrap: layout, Builtin(Decimal)', crates/compiler/gen_dev/src/generic64/mod.rs:1500:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

it is of course also interesting that it picks mulwrap here instead of mul
