### ISSUE TITLE
Language server will occasionally hog CPU

### ISSUE THREAD

**Issue by fwgreen** [roc-lang/roc#6336]
On a few occasions, the language server starts to consume a lot of CPU.  I usually only find out whats happening when my cooling fan spins up.  I don't know how to trigger it demand, but it might be related to restarting VSCode after the language server crashes with multiple editors open.

![Screenshot 2024-01-02 at 00 28 30](https://github.com/roc-lang/roc/assets/7098161/461b2cf1-b8d6-4383-8b67-835e56493dd8)

```
roc nightly pre-release, built from commit 4569770c82c on Fri Dec 29 09:12:45 UTC 2023
Apple M1
```

**Comment by faldor20** [comment]
One possibility is lots of analysis tasks queued 

The upcoming version of the language server in #6134 trys to "debounce" as you type so that it doesn't perform a document analysis on every change, that change may help.
My guess would be that if you do a lot of typing you can get backlogged on analysis and then it just sits there churning for a bit.

Do you find it stops using lots of CPU time if you just leave it for a bit?
Can you get hover docs when it is in this "high cpu" state?

**Comment by fwgreen** [comment]
Thanks for taking the time and I wish I had the technical acumen to help you diagnose what is actually happening.  Each process just sits at 99% CPU even after I exit VSCode.  But I never suspected the language server because it seemed to run fine throughout and was still responsive (I assumed it was Safari as I usually have the browser open when I code).

**Comment by faldor20** [comment]
Hmm, It's also interesting that you have multiple processes... I don't think there should be more than one.
I'm wondering if we are getting stuck in some kind of weird loop and then vscode is abandoning the process when it stops responding and then just starting another one. 

A few things I'd like to see:
1. When you have these stuck processes, do they eventually just disappear?
2. When you close vscode, does one of the processes close with it?
3. When you freshly start vscode how many roc_ls processes start? is it just one and the extra ones get added on later?

**Comment by fwgreen** [comment]
I'll keep these questions in mind and report back if it happens again (I'll also take a screenshot of the memory tab).  Note that it's only happened twice in the past week and a half though I've spent a few hours per day trying to muddle through my Advent of Code backlog.  

Under normal operation, I see one process start with each editor window; one closes immediately with each window closing or all close immediately if I just exit VSCode.  Though I am just realizing that normally each process uses 10 threads but use 9 threads when they run amok (maybe another clue or just nothing?).

![Screenshot 2024-01-02 at 13 18 19](https://github.com/roc-lang/roc/assets/7098161/a52cbc6d-53cb-48c6-9718-c3bd0c221628)

**Comment by CrepeGoat** [comment]
related to #6185?

**Comment by CrepeGoat** [comment]
I've had a similar experience with the roc-ls, and because of this behavior I've stopped using it altogether, which makes writing Roc much more challenging. It'll be an exciting day to see a fix for this 🙏

**Comment by fwgreen** [comment]
The popup is new, but the last time around I didn't have Docker running...
![Screenshot 2024-01-06 at 23 04 05](https://github.com/roc-lang/roc/assets/7098161/c008ff0c-0126-4d8c-81e4-09bbf9cee2a9)
I was able to quit VSCode normally but had to kill the language server process.  Note the 40 GB memory consumption.

**Comment by faldor20** [comment]
Okay I believe I have figured out what is wrong, It seems like anytime you open an interface file that has a shorthand import of a package, the language server will hang.
eg 
```
interface A
  imports [pf.Stdout]
```
The other case is if you typecheck an app file with a shorthand that is incorrect:
eg 
```
app "a"
  imports [notapackage.Stdout]
```
If you can find instances where it hangs outside of that, I'd be very interested to see an example.

I am working on a fix for the above 2 issues, but it's an annoying thing to solve

**Comment by faldor20** [comment]
@fwgreen The PR to fix this was merged, would you like to check if this is working now?

**Comment by fwgreen** [comment]
I'm now getting a more tolerable version of the problem (the CPU hogging might have stopped):  The runaway processes seem to halt and possibly start new processes?  Note I have three editors open and five language servers running...

![Screenshot 2024-01-25 at 16 52 32](https://github.com/roc-lang/roc/assets/7098161/e7482a2c-ce66-4634-8b8e-6f0d0f2a871d)

After quitting VSCode, I still have two language servers still running...

![Screenshot 2024-01-25 at 16 55 31](https://github.com/roc-lang/roc/assets/7098161/19bad286-2a55-429a-866a-d5c6e9a78948)

**Comment by faldor20** [comment]
Okay, now I think this is a different issue. The language server isn't shutting down correctly sometimes, I think I've had this issue too. If you could make a new issue with those screenshots I'll take a look at it as well sometime :)

**Comment by faldor20** [comment]
@fwgreen Could you please mark this as closed ::
