### ISSUE TITLE
Underscores in variable names crash compiler

### ISSUE THREAD

**Issue by alexpyattaev** [roc-lang/roc#6338]
If underscore is present in variable name the compiler crashes in an unfriendly manner:
```roc
x_a=1
```

thread '<unnamed>' panicked at 'not yet implemented: top-level destrucuture patterns are not implemented', crates/compiler/load_internal/src/file.rs:5926:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The funny bit is that roc check actually knows that _ is not allowed, but roc compiler just crashes.

roc repl crashes in a similarly unfriendly manner:
```
❯ roc repl

  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» x_1=3
thread 'main' panicked at 'not yet implemented: handle pattern other than identifier (which repl doesn't support)', crates/repl_ui/src/repl_state.rs:123:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by skyqrose** [comment]
This problem still exists, but won't for long: Underscores will now be allowed after https://redirect.github.com/roc-lang/roc/issues/7214 . So I'm closing this issue.
