### ISSUE TITLE
Should we add something like `approxEqual` for floats?

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6349]
It seems like a lot of languages have something like it. The docs for the function would be a good place to explain the float comparison issue in detail. We should do some research on how this is done in other language and then propose something in the zulip ideas stream.

**Comment by B-Teague** [comment]
I'd like to take this too please

**Comment by B-Teague** [comment]
This approach would require a new Option type.

```roc
isApproxEq = a,b, Option rtol, Option atol ->
    _rtol = when rtol is
        Some x -> x
        None -> 1e-05
    _atol = when atol is
        Some y -> y
        None -> 1e-08
    (Num.abs (a - b)) <= (_atol + _rtol * (Num.abs b))
```

**Comment by johannesvollmer** [comment]
Shouldn't this be the default for all float comparisons? Because otherwise, the automatically generated eq implementation would be useless, and I'd always have to write my own equality algorithms for the types that contain floats?
