### ISSUE TITLE
Add new Option.roc builtin type?

### ISSUE THREAD

**Issue by B-Teague** [roc-lang/roc#6353]
I see Option already in use in some of the code base.

Do we want to make an official Option.roc type interface?

**Comment by Anton-4** [comment]
Hi @B-Teague,
Not encouraging the use of `Option` was a deliberate choice, we talk about it [here](https://github.com/roc-lang/roc/blob/main/www/content/faq.md#why-doesnt-roc-have-a-maybe-or-option-or-optional-type-or-null-or-nil-or-undefined).
