### ISSUE TITLE
roc compiler hangs indefinitely when encountering unexpected lower case import

### ISSUE THREAD

**Issue by imclerran** [roc-lang/roc#6388]
I was converting a roc app to an interface, and still had a leftover import of `pf.Stdout` in my import statements. When running `roc test MyInterfaceFile.roc`, the terminal hangs indefinitely, with no output, until `Ctrl+C` is pressed to break execution. 

I have tried this in a few different interface files, and adding any `lowerCamel.*` import will hang the execution. If I import a non existant `UpperCamel.*`, the compiler correctly fails with a file not found error. But any import beginning with a lowercase letter causes the compiler to hang.

Both `roc check` and `roc test` hang this way.

**EDIT**: On further testing, adding an unexpected lower case import to a roc app will also cause the same indefinite hang - so this bug does not only apply to interfaces, but also to apps, and thus `roc run`, `roc dev`, etc will also encounter this issue.

**Comment by RMailaender** [comment]
I think it might be related to: #6373

**Comment by imclerran** [comment]
Yes, and like the same issue as #5961 - good find on your report.
