### ISSUE TITLE
Scalar literal `'$'` errors with `ENDLESS STRING`

### ISSUE THREAD

**Issue by doubledup** [roc-lang/roc#6390]
The literal `$` causes an endless string error as below. The same error happens when building a file containing `'$'` with `roc dev`. It requires a backslash now, but going by the Zulip thread it shouldn't.

[Zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/how.20.20to.20.20do.20U8.20.20now.3F)

```
» x = '$'

── ENDLESS STRING ──────────────────────────────────────────────────────────────

I cannot find the end of this string:

6│      x = '$'
             ^

You could change it to something like "to be or not to be" or even
just "".

» x = '\$'

36 : Int *
» 
```

**Comment by rtfeldman** [comment]
This is now fixed in https://github.com/roc-lang/roc/pull/6379!
