### ISSUE TITLE
Add markdown style links for generated roc docs

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#6420]
Update `crates/docs/src/lib.rs` so that we generate markdown style links. 

This is already implemented in the `examples/static-site-gen` platform which may be useful. Note that we do not want to support rendering arbitrary html in doc comments, so the method used in static-site-gen may not be suitable.

## Desired behaviour 

A doc comment like follows

```roc
## ## [Syntax](#syntax) {#syntax} 
```

Should generate the following html

```html
<h2 id="syntax"><a href="#syntax">Syntax</a></h2>
```

**Comment by stuarth** [comment]
i'll grab this one
