### ISSUE TITLE
`cargo test --test cli_run` runs for ever when the example programs don't compile

### ISSUE THREAD

**Issue by sebsheep** [roc-lang/roc#644]
The `cargo test --test cli_run` has an issue when the example programs don't compile: it makes the test waiting without emitting any error.

E.G., add an invalid line in `examples/hello-world/Hello.roc`:
```
app Hello provides [ main ] imports []

greeting =
    hi = "Hello"
    name = "World"

    "\(hi), \(name)!!!!!!!!!!!!!"

f # <---- this is meaningless!

main = greeting
```

and run:
```
cargo test --test cli_run hello
```
This would display:
```
running 2 tests
```

And nothing happens.

**Comment by isaacvando** [comment]
Closing as this is no longer and issue.
