### ISSUE TITLE
Stylesheet issue on /different-names

### ISSUE THREAD

**Issue by jelder** [roc-lang/roc#6470]
[The different names page](https://www.roc-lang.org/different-names) (which I love, btw) renders strangely with no left margin since the late 2023 redesign. 

<img width="1177" alt="image" src="https://github.com/roc-lang/roc/assets/38099/aa54c547-1489-4bc2-a2c5-4d56cfc84ef8">

**Comment by gunnarahlberg** [comment]
@jelder - I think this is fixed now?

**Comment by jelder** [comment]
Better, but should this page have links to the rest of the Roc documentation? It seems like as part of the docs, it should have the same navbar as e.g. https://www.roc-lang.org/builtins.

**Comment by gunnarahlberg** [comment]
Yes, I agree that would make sense

I am not really sure about the reason or background for this page, maybe the names page is included somewhere else and that is why?

**Comment by Anton-4** [comment]
I think that's because the builtin docs are generated by roc and the different-names page is just a static page.
I approve of adding the header to the different-names page.
