### ISSUE TITLE
add sort button to docs so that function names can be displayed in alphabetical order

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6494]
This is currently in the order that the functions are exposed in at the top of Str.roc:

![Screenshot_20240203_112316](https://github.com/roc-lang/roc/assets/17049058/4b51eb23-9e21-40d7-8cf6-8160d5d0cedb)

A button should be added near the top of this list to change this to alphabetical order.
I think changes need to be made [here](https://github.com/roc-lang/roc/blob/main/crates/docs/src/lib.rs).

- [ ] implement sorting functionality
- [ ]  make a good looking button that fits with the docs theme 
- [ ] check button looks good with dark and light theme
- [ ] check button looks good for variety of screen sizes on desktop, tablet, smartphone
- [ ] this button should not be visible if javascript is disabled

**Comment by gamebox** [comment]
Just taking a look at issues, and this would be simple enough.  But is there any value in the current order at all?  Shouldn't we just sort alphabetically always?  I'm assuming the current order is based on source order, but I don't think docs should care about source order.

**Comment by Anton-4** [comment]
We've discussed this before on zulip, using the source order makes it easy to group related functions that may otherwise be very far apart using an alphabetical order.

Thinking about it more, there has been very little demand for this. Let's shelve this for now, it's good to prevent rapid accumulation of features and complexity.
