### ISSUE TITLE
Improve repl contrast on (very) dark terminal background

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6512]
![PXL_20240207_110908757.MP.jpg](https://github.com/roc-lang/roc/assets/17049058/91545af3-b1bd-44e8-b777-f738e6d52443)

In real life the contrast is worse than in the photo. The blue text is unreadable and the pink colon's visibility is not good enough.

**Comment by hirotake111** [comment]
I would like to take a look at this. It looks like we can use brighter colors out of 256 colors if terminal supports them (otherwise fallbacks to ansi colors).

**Comment by hirotake111** [comment]
Oh so we can't simply check environment variables as `STYLE_CODES` is a global variable. Let's change these color variables into something brighter from 256 color palette assuming most of terminals today are 256-color compatible.

**Comment by Anton-4** [comment]
Sounds good @hirotake111 :)
I'll assign you to the issue
