### ISSUE TITLE
Debug output with a Tag has duplicate information

### ISSUE THREAD

**Issue by fwgreen** [roc-lang/roc#6518]
The following statement,
```elm
dbg T "the row number is: " row
```
outputs...
```
[main.roc:31] T "the row number is: " row = (T "the row number is: " 1)
```

`roc nightly pre-release, built from commit 448c29353ed on Fri Feb  9 09:13:03 UTC 2024`

**Comment by lukewilliamboswell** [comment]
I think this is the correct behaviour, it prints the source code at line 31, and then also the value the expression given to `dbg` resolves to.

**Comment by fwgreen** [comment]
Once explained it does make sense, but it wasn't the behavior prior to the `Feb 9` release and doesn't align with the current documentation.  Maybe some formatting options can be provided?  Now the output gives the impression that `row` is equal to  `(T "the row number is: " 1)` and not just `1`.  Thanks for taking the time to explain.

**Comment by skyqrose** [comment]
https://www.roc-lang.org/tutorial#dbg still says:

(begin quote)

```roc
pluralize = \singular, plural, count ->
    dbg count
    if count == 1 then
        singular
    else
        plural
```

Whenever this `dbg` line of code is reached, the value of `count` will be printed to [stderr](<https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)>), along with the source code file and line number where the `dbg` itself was written:

`[pluralize.roc 6:8]`

Here, `[pluralize.roc 6:8]` tells us that this `dbg` was written in the file `pluralize.roc` on line 6, column 8.

(end quote)

So I guess that's out of date.

**Comment by lukewilliamboswell** [comment]
I'm going to close this as the specific formatting is provided by the platform and not provided by roc. 

The tutorial and documentation could be improved slightly, but I don't think that this is an issue that needs to be resolved or tracked.
