### ISSUE TITLE
Docs: support search by signature

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6540]
I think this functionality should be added in [this file](https://github.com/roc-lang/roc/blob/main/crates/docs/src/lib.rs).

- [ ] Implement basic signature search functionality.
- [ ] Integrate this functionality with existing search text input field. Not sure what the best UI/UX would be here, I recommend experimenting. 

Inspiration:
- https://klaftertief.github.io/elm-search/
- https://hoogle.haskell.org/

**Comment by jfkonecn** [comment]
@Anton-4 

I do have a [simple working implementation](https://github.com/jfkonecn/roc/commit/d96b11952a96fea558d67cc55296c663f369a2d1), but I made no changes to the UI so user will not know the function signatures are acceptable search parameters.

I was thinking about using the [vue.js](https://vuejs.org/api/options-lifecycle.html) search modal for inspiration.

I could use the [dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element to implement the modal. 

If you think a modal is a bad idea, then the way [stripes docs search](https://docs.stripe.com/no-code/subscriptions) works also seems pretty user friendly.

**Comment by Anton-4** [comment]
Thanks for looking into this @jfkonecn :heart:
I like the stripe one the most, with the search bar centered :)
