### ISSUE TITLE
feat: suppress REPL startup message

### ISSUE THREAD

**Issue by gvwilson** [roc-lang/roc#6570]
It would be useful for teaching purposes to have a `-q` flag for `roc repl` that suppressed the startup message so that it didn't appear in captured output:

```
  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.
```

If this is added, could `-q` (or some other flag) disable colorized output? The escape sequences used to change colors have to be filtered out if I'm saving output for inclusion in Markdown and other docs.

**Comment by Anton-4** [comment]
Yeah, those sound like helpful features :+1:

I would go with two flags like `--no-header` and `--no-colors`.
