### ISSUE TITLE
space after backslash in function definition causes panic

### ISSUE THREAD

**Issue by gvwilson** [roc-lang/roc#6578]
Without space, works as expected:

```
max3 = \a, b, c ->
    Num.max a (Num.max b c)

<function> : Num a, Num a, Num a -> Num a
```

With space after backslash (which I expected to work in the same way as a space after `+` in `3 + 2`):

```
max_3 = \ a, b, c ->
    Num.max a (Num.max b c)

thread 'main' panicked at 'not yet implemented: handle pattern other than identifier (which repl doesn't support)', crates/repl_ui/src/repl_state.rs:123:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think space should be allowed after `\`, particularly with long parameter names (the `\` can get lost), but if it is not, there should be a comprehensible error message rather than a panic.

Using:
- MacOS 14.3.1
- roc nightly pre-release, built from commit 3ea97398f5 on Tue Feb 27 09:12:57 UTC 2024

**Comment by lukewilliamboswell** [comment]
For reference, I think a good place to start investigating this issue would be [`closure_help` in `crates/compiler/parse/src/expr.rs`](https://github.com/roc-lang/roc/blob/4a7d1a892be60012e910a489a475e0c6b6a31cae/crates/compiler/parse/src/expr.rs#L2081).

**Comment by wontem** [comment]
It looks more like a problem with the underscore in `max_3`:

```
» max3 = \ a, b, c -> Num.max a (Num.max b c)

<function> : Num a, Num a, Num a -> Num a
» max3a = \ a ,    b ,  c    -> Num.max a (Num.max b c)

<function> : Num a, Num a, Num a -> Num a
```

but

```
» a_1 = 42
thread 'main' panicked at crates/repl_ui/src/repl_state.rs:133:25:
not yet implemented: handle pattern other than identifier (which repl doesn't support).
Tip: this error can be triggered when trying to define a variable with a character that is not allowed,like starting with an uppercase character.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
