### ISSUE TITLE
improve error message: "field not in its own type"

### ISSUE THREAD

**Issue by float3** [roc-lang/roc#6636]
https://github.com/roc-lang/roc/blob/main/crates/compiler/mono/src/ir.rs#L8049

I run into this a lot, a more helpful error message would be good

am willing to contribute this but would probably need some guidance

**Comment by Anton-4** [comment]
Hi @float3,
Can you post a small but realistic code example that causes this panic?

**Comment by float3** [comment]
sorry for not providing a minimized example. I forgot. thanks for fixing it
