### ISSUE TITLE
Builtins to implement

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#664]
# Builtins to implement

These are some builtins we haven't yet implemented. When implementing a builtin, please:

1. Make an issue for it and and assign it to yourself so no one accidentally starts implementing your builtin after you've started!
2. Put all the necessary changes for adding your builtin in the same PR, with no extraneous changes unrelated to adding the builtin. Then, include the name of the module and builtin (for example, `List.dropAt`) in the title of the PR. This allows other contributors to find your PR later and use it as an example when they are trying to implement _their_ first builtins.

## `Num`

- [x] `maxU128 : U128`
- [x] `toI8 : Int * -> I8`
- [x] `toI16 : Int * -> I16`
- [x] `toI32 : Int * -> I32`
- [x] `toI64 : Int * -> I64`
- [x] `toI128 : Int * -> I128`
- [x] `toU8 : Int * -> U8`
- [x] `toU16 : Int * -> U16`
- [x] `toU32 : Int * -> U32`
- [x] `toU64 : Int * -> U64`
- [x] `toU128 : Int * -> U128`
- [x] `toF32 : Num * -> F32`
- [x] `toF64 : Num * -> F64`
- [ ] `parseI16 : List U8, Endi, Nat -> Result I16 [ NotEnoughBytes ]*`
- [ ] `parseU16 : List U8, Endi, Nat -> Result U16 [ NotEnoughBytes ]*`
- [ ] `parseI32 : List U8, Endi, Nat -> Result I32 [ NotEnoughBytes ]*`
- [ ] `parseU32 : List U8, Endi, Nat -> Result U32 [ NotEnoughBytes ]*`
- [ ] `parseI64 : List U8, Endi, Nat -> Result I64 [ NotEnoughBytes ]*`
- [ ] `parseU64 : List U8, Endi, Nat -> Result U64 [ NotEnoughBytes ]*`
- [ ] `parseI128 : List U8, Endi, Nat -> Result I128 [ NotEnoughBytes ]*`
- [ ] `parseU128 : List U8, Endi, Nat -> Result U128 [ NotEnoughBytes ]*`
- [ ] `parseF32 : List U8, Endi, Nat -> Result F32 [ NotEnoughBytes ]*`
- [ ] `parseF64 : List U8, Endi, Nat -> Result F64 [ NotEnoughBytes ]*`
- [ ] `parseNat : List U8, Endi, Nat -> Result Nat [ NotEnoughBytes ]*`
- [ ] `parseDec : List U8, Endi, Nat -> Result Dec [ NotEnoughBytes ]*`

## `List`

- [x] #2001
- [x] #1896
- [x] #2504
- [x] `walkBackwardsUntil : List elem, state, (state, elem -> [ Continue state, Stop state ]) -> state`
- [x] `walkFrom : List elem, Nat, state, (state, elem -> state) -> state` (starts walking at the given `Nat` index) (#4346)
- [x] `walkFromUntil : List elem, Nat, state, (state, elem -> [ Continue state, Stop state ]) -> state` (#4346)
- [x] #6988
- [x] #6989

## `Result`

- [x] #6991
- [ ] `map3 : Result a err, Result b err, Result c err, (a, b, c -> d) -> Result d err`
- [ ] `map4 : Result a err, Result b err, Result c err, Result d err, (a, b, c, d -> e) -> Result e err`
- [ ] `map5 : Result a err, Result b err, Result c err, Result d err, Result e err, (a, b, c, d, e -> f) -> Result f err`
- [ ] `map6 : Result a err, Result b err, Result c err, Result d err, Result e err, Result f err, (a, b, c, d, e, f -> g) -> Result g err`
- [ ] `map7 : Result a err, Result b err, Result c err, Result d err, Result e err, Result f err, Result g err, (a, b, c, d, e, f, g -> h) -> Result h err`
- [ ] `map8 : Result a err, Result b err, Result c err, Result d err, Result e err, Result f err, Result g err, Result h err, (a, b, c, d, e, f, g, h -> i) -> Result i err`
- [x] #6992
- [x] `try : Result before err, (before -> Result after err) -> Result after err`
- [x] `onErr : Result ok before, (before -> Result ok after) -> Result ok after`
- [x] #1954
- [x] #1965

## `Str`

- [x] `withCapacity : Nat -> Str`
- [ ] `dropPrefix : Str, Str -> Result Str {}`
- [ ] `dropSuffix : Str, Str -> Result Str {}`
- [x] #3251
- [x] #1972

**Comment by snprajwal** [comment]
@rtfeldman It would be great if this list could be updated, since a lot of them have been implemented since June

**Comment by Lunarmagpie** [comment]
`walkFrom` and `walkFromUntil` are already implemented. They should be checked off the list.

**Comment by JanCVanB** [comment]
@Lunarmagpie updated!

**Comment by lukewilliamboswell** [comment]
@rtfeldman I propose we close this issue. 

We can track the `List.sort` upgrade in https://github.com/roc-lang/roc/issues/7006, and if we add an issue for [string parsers we are discussing on Zulip](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/builtins.20for.20parsing/near/462945412), and if https://github.com/roc-lang/roc/pull/7007 lands, , then I think we have everything covered and this tracking issue is no longer required.

**Comment by rtfeldman** [comment]
Awesome, sounds good! 🎉
