### ISSUE TITLE
`roc build` should emit an executable, not a .o file

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#665]
Right now, `roc run` builds an executable and then runs it.

`roc build` should build that same executable, and print its location to stdout, but should stop short of running it.

(At the moment, `roc build` just compiles a `.o` file and stops there!)

**Comment by lukewilliamboswell** [comment]
Recommend this be closed as completed.

```sh
% roc build test.roc
0 errors and 0 warnings found in 1321 ms while successfully building:

    aoc-2022
```
