### ISSUE TITLE
Are `Roc's tags` suitable for low-level languages?

### ISSUE THREAD

**Issue by hardskulls** [roc-lang/roc#6707]
I'm wondering if it's possible do do the same thing in low-level languages like `C++`, `Rust`, `Zig`, etc.
If no - then why, and if yes - why no one does it. 
On surface this feature looks like just anonimous `Rust enums`, where `enum` is not defined upfront by user, and is instead defined automatically by the compiler.
I'm also curious about `closed/open` feature which is related to `tags` as well as `records`.

**Comment by lukewilliamboswell** [comment]
@hardskulls, these are some good discussion points. I think you might find better engagement with this over on the [roc zulip](https://roc.zulipchat.com) which is where most people hang out and chat about these kinds of things.

**Comment by hardskulls** [comment]
> @hardskulls, these are some good discussion points. I think you might find better engagement with this over on the [roc zulip](https://roc.zulipchat.com) which is where most people hang out and chat about these kinds of things. 
> 

Ok, thanks

**Comment by Anton-4** [comment]
Moved to https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Roc's.20tags
