### ISSUE TITLE
Support file imports without type annotation

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#6710]
If a user doesn't include a type annotation when ingesting files they get a slightly confusing "NOT END OF FILE" error message. Ideally we could detect this issue and provide a nicer error message.

<img width="729" alt="Screenshot 2024-05-03 at 19 09 39" src="https://github.com/roc-lang/roc/assets/2679227/d7c74258-9357-45e9-bc71-d55b1c0921f6">

```roc
import "data.json" as requestBody : List U8
```

**Comment by agu-z** [comment]
We decided to make the annotation optional, so that the following:

```roc
import "data.json" as requestBody
```
Is equivalent to:
```roc
import "data.json" as requestBody : _
```

Currently, `_` defaults to `List U8`, but I made a separate [issue](https://github.com/roc-lang/roc/issues/6716) to infer the type from usage.
