### ISSUE TITLE
Dead link to LogFormatter.roc in abilities.md

### ISSUE THREAD

**Issue by kukimik** [roc-lang/roc#6727]
This is a dead link:

https://github.com/roc-lang/roc/blob/9ed0067248044bf2a950fed104d26796e2531cf2/www/content/abilities.md?plain=1#L181

The file was removed in aeabf96e8008434fad5e7067d15f088bad3d57ea.

I could just remove the link, but I'm not sure if there are other examples of formatters available and whether `Inspect.toDbgStr` (which, as far as I understand, is a standard solution that replaced `LogFormatter`) should be mentioned in `abilities.md`, so I'm not fixing this myself.

**Comment by Anton-4** [comment]
Thanks for alerting us @kukimik, I fixed this in #6731
