### ISSUE TITLE
Add HTML page titles and descriptions for roc-lang.org/examples and everything under it.

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6741]
Perhaps those can be added to the pageData Dict [here](https://github.com/roc-lang/roc/blob/main/www/main.roc) but I'm not sure...

**Comment by kukimik** [comment]
@Anton-4  I don't think it works as intended.

https://www.roc-lang.org/examples/HelloWorld/README.html
```
<title>README.html</title><meta  name="description" content="Example of README.html in the Roc programming language."><
```

https://www.roc-lang.org/examples/
```
<title>index.html</title><meta  name="description" content="Example of index.html in the Roc programming language.">
```

**Comment by Anton-4** [comment]
Haha, good catch, I'll fix that.
