### ISSUE TITLE
Consider switching to tabs for indentation

### ISSUE THREAD

**Issue by bemyak** [roc-lang/roc#6756]
I hate to be _that_ guy, but I haven't found a relevant discussion (only bugs https://github.com/roc-lang/roc/issues/4528, https://github.com/roc-lang/roc/issues/2288). Since Roc is not 1.0 yet, but approaching it somewhat, maybe it's worth settling this down now.

The main argument for tabs is accessibility. There's a lengthy [discussion](https://github.com/rust-lang/rustfmt/issues/4067#issuecomment-685961408) in rustfmt, from which I would like to highlight a link to this [reddit post](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/), and this [comment](https://github.com/rust-lang/rustfmt/issues/4067#issuecomment-685961408), both of which confirm that visually-impaired people do struggle with spaces as they are not customizable for their needs.

Gofmt also uses tabs, but I haven't found the reasoning behind this decision.

My personal issue with spaces is the cursor placement. For every indentation level, there are 3 cursor positions, which do not make sense (e.g. placing the cursor after 3rd space).

I'd like to know if the Roc developers have any opinions on this, and is it feasible to do the switch?

**Comment by ayazhafiz** [comment]
The discussion for this topic in Roc is here: https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/tabs.20for.20indentation.3F

**Comment by bemyak** [comment]
Oh, I haven't checked Zulip, my bad. Good to see it was already raised and discussed. I believe the devs will make the right choice whatever that ends up being.

I watched the Richard's talk on Roc just yesterday and was absolutely blown away by the language design: so many elegant and simple concepts packed together in a form which surpasses even the Elm's ergonomic 🤯
This tab thingie was the only tiny detail, which I would like to have a second thought on. Congrats on the amazing project!
