### ISSUE TITLE
Invalid "File Not Found" Error

### ISSUE THREAD

**Issue by fwgreen** [roc-lang/roc#6766]
The code below runs without issue, but the IDE gives me this error:
```
[1;36m── FILE NOT FOUND in Lib/Lib/A.roc ─────────────────────────────────────────────[0m

I am looking for this file, but it's not there:

    [1;33m/Users/francois/SoftwareProjects/Roc/RocBug/Lib/Lib/A.roc[0m

Is the file supposed to be there? Maybe there is a typo in the file
name?
```

**Directory structure**
```
RocBug/
├── Lib/
│   ├── A.roc
│   └── B.roc
└── main.roc
```
**main.roc**
```roc
# main.roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import pf.Stdout
import Lib.B

main =

    Stdout.line Lib.B.second
```
**A.roc**
```roc
module [first]

first = "Hello"
```
**B.roc**
```roc
module [second]

import Lib.A 

second = Str.joinWith [Lib.A.first, "World"] ", "
```

**Comment by fwgreen** [comment]
Thanks for taking the time and I apologize for the missing details.  I'm on an Apple M1 running macOS 14.5 and VSCode 1.89.1 with unofficial Roc extension .  I just upgraded to
`roc nightly pre-release, built from commit 33075285b72 on Wed May 22 09:12:12 UTC 2024`
and I'm still having the problem.

**Comment by lukewilliamboswell** [comment]
I think this is a known issue, and I think this is something @agu-z mentioned that he would start on after module params. 

We need some way to be able to traverse back up the folder structure until we find a `main.roc` (platform/package) so we can know what the import structure is.

**Comment by fwgreen** [comment]
Resolved as of `roc nightly pre-release, built from commit 4d4776784ad on Tue Jun 11 09:12:11 UTC 2024`.  Thanks again.
