### ISSUE TITLE
Compiler crashed when building with --optimize flag on Zorin OS

### ISSUE THREAD

**Issue by dykstrom** [roc-lang/roc#6783]
The compiler crashed and told me to file an issue, see below!

Operating system: Zorin OS
Compiler version: nightly build from 2024-05-22 (and also 2024-05-27)
Code to build: https://github.com/dykstrom/rocky (tag rocky-0.0.1)

Compiling on Zorin OS without optimization works fine. 
Compiling with optimization using the same version of the compiler on macOS works fine.
Compiling using the latest nightly build on Zorin OS also crashes.

```
RUST_BACKTRACE=full roc build --optimize --output ./ src/rocky.roc
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at crates/linker/src/elf.rs:1471:25:
Undefined Symbol in relocation, (+212b7, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+97)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "memmove", address: +0, size: +0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })
stack backtrace:
   0:     0x564f423165cb - <unknown>
   1:     0x564f4152d650 - <unknown>
   2:     0x564f42312233 - <unknown>
   3:     0x564f42316364 - <unknown>
   4:     0x564f42317ec0 - <unknown>
   5:     0x564f42317bdf - <unknown>
   6:     0x564f423183de - <unknown>
   7:     0x564f423182e2 - <unknown>
   8:     0x564f42316ac6 - <unknown>
   9:     0x564f42318050 - <unknown>
  10:     0x564f4141ce55 - <unknown>
  11:     0x564f41c452a9 - <unknown>
  12:     0x564f41c57efe - <unknown>
  13:     0x564f4176a792 - <unknown>
  14:     0x564f41768683 - <unknown>
  15:     0x564f41886465 - <unknown>
  16:     0x564f4171d3de - <unknown>
  17:     0x564f416fb263 - <unknown>
  18:     0x564f416fb283 - <unknown>
  19:     0x564f4230818a - <unknown>
  20:     0x564f4171fc75 - <unknown>
  21:     0x7fdb69383083 - __libc_start_main
  22:     0x564f414c195e - <unknown>
  23:                0x0 - <unknown>
```

**Comment by Anton-4** [comment]
Thanks for reporting this issue @dykstrom! Can you share the source code?

**Comment by dykstrom** [comment]
It is too much code to paste in the issue, and I haven't been able to reduce it to a small example.

It is available in a public GitHub repo: https://github.com/dykstrom/rocky
Check out tag rocky-0.0.1

**Comment by Anton-4** [comment]
Thanks, yeah that's a lot of code :p
This may work as a workaround `roc build --linker=legacy --optimize --output ./ src/rocky.roc`.
This looks like a case of https://github.com/roc-lang/roc/issues/3609

**Comment by dykstrom** [comment]
I'll try that and let you know if it works.

**Comment by dykstrom** [comment]
Yes, the workaround worked. Thank you!
Shall we close this issue as a duplicate then?
