### ISSUE TITLE
Unrecognized Package error after the most recent update

### ISSUE THREAD

**Issue by fwgreen** [roc-lang/roc#6801]
Note the platform is named `bug` instead of `pf`.
```roc
app [main] {
    pg: "https://github.com/agu-z/roc-pg/releases/download/0.1.0/nb1q6kN1pu1xvv45w2tE7JjbQ60hOyR1NMxxhRMCVFc.tar.br",
    bug: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import bug.Stdout
import pg.Pg.BasicCliClient

main =
    Stdout.line! "Bug!"
```

```
UNRECOGNIZED PACKAGE

This module is trying to import from `pf`:

22│          pf.Tcp,
             ^^^^^^

A lowercase name indicates a package shorthand, but I don't
recognize this one. Did you mean one of these?

    pg
    bug
```
macOS 14.5
`roc nightly pre-release, built from commit 4d4776784ad on Tue Jun 11 09:12:11 UTC 2024`

**Comment by lukewilliamboswell** [comment]
I think this is because roc pg is using effects and assumes the platfrom is named 'pf'. 

This should be resolved with module params and is currently a workaround for not being able to pass the effects into a package.

**Comment by agu-z** [comment]
@fwgreen As Luke said, this is just a workaround that roc-pg uses. I'm closing this because the compiler seems to work as expected here. We can reopen if you find a different issue.
