### ISSUE TITLE
Compiler Panics when --prebuild-platform is omitted.

### ISSUE THREAD

**Issue by ishehadeh** [roc-lang/roc#6815]
Steps to reproduce:
- `git clone https://github.com/lukewilliamboswell/roc-platform-template-c`
- `roc run build.roc`
- `roc build app.roc`
- compiler panics with `Error When Building C Platform: failed to open file "platform/dynhost": No such file or directory (os error 2)`

This could probably be repoduced different ways,  without using the roc-plaftform-c repo.

Steps to fix:

Catch the error, possibly suggest trying the -prebuilt-platform.

see: https://github.com/roc-lang/roc/issues/6814

**Comment by Anton-4** [comment]
Suggested fix sounds good, the error message could be:
```
Error: File "platform/dynhost" does not exist.
    Tip:  Perhaps you intended to use a prebuilt platform? Try again with for example; `roc build your_file.roc --prebuilt-platform`.
```

**Comment by lukewilliamboswell** [comment]
Fixed by https://github.com/roc-lang/roc/pull/6859
