### ISSUE TITLE
Panic when annotation has smaller arity than function definition

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#686]
If I write a function with 2 arguments, and annotate it with an annotation that has fewer than 2 arguments, the type-checker will panic. For example:

```
threeArgs : Int, Int -> Int
threeArgs = \a, b, c -> a + b + c # My annotation should have 3 args but it only has 2
```

This is because there's a call to `zip()` which zips the arguments in the function definition together with the arguments in the annotation, and if one is longer than the other, arguments in the definition will get silently dropped by `zip`. When the function body then goes to refer to those arguments, the lookup will fail even though it worked back in the name resolution stage of canonicalization.

The fix for this should include tests for all 4 of these cases: (note that the `zip` appears in differnent places for recursive vs nonrecursive functions)
- [ ] Annotation has more arguments than definition (recursive function)
- [ ] Annotation has more arguments than definition (nonrecursive function)
- [ ] Annotation has fewer arguments than definition (recursive function)
- [ ] Annotation has fewer arguments than definition (nonrecursive function)

They will both have different symptoms!

**Comment by JanCVanB** [comment]
This doesn't seem to panic anymore - has this issue been satisfactorily resolved?
```
» threeArgs : Nat, Nat -> Nat
… threeArgs = \a, b, c -> a + b + c # My annotation should have 3 args but it only has 2
… threeArgs 7 8 9

── UNRECOGNIZED NAME ───────────────────────────────────────────────────────────

The #UserApp module does not expose anything by the name c.

── TOO MANY ARGS ───────────────────────────────────────────────────────────────

The threeArgs function expects 2 arguments, but it got 3 instead:

6│      threeArgs 7 8 9
        ^^^^^^^^^

Are there any missing commas? Or missing parentheses?


» 
```

**Comment by JanCVanB** [comment]
@rtfeldman This doesn't seem to panic anymore - has this issue been satisfactorily resolved?
```
» threeArgs : Nat, Nat -> Nat
… threeArgs = \a, b, c -> a + b + c # My annotation should have 3 args but it only has 2
… threeArgs 7 8 9

── UNRECOGNIZED NAME ───────────────────────────────────────────────────────────

The #UserApp module does not expose anything by the name c.

── TOO MANY ARGS ───────────────────────────────────────────────────────────────

The threeArgs function expects 2 arguments, but it got 3 instead:

6│      threeArgs 7 8 9
        ^^^^^^^^^

Are there any missing commas? Or missing parentheses?


» 
```

**Comment by rtfeldman** [comment]
Looks like it! 👍
