### ISSUE TITLE
maocs nightly release size has massively increased

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6871]
The nightly archive size went from 30.8 MiB to 87.3 MiB between commits 794c20956de and d47a073634e, on Linux there was no increase at all.
I suspect PR https://github.com/roc-lang/roc/pull/6834 is the cause. We should investigate this and see if we can reduce the size.

**Comment by skyqrose** [comment]
Whatever it was, the sizes are back to normal now.

![List of nightly downloads, macos is 36MB](https://github.com/user-attachments/assets/b280985a-3b7d-44bc-8637-66bf541532f8)
