### ISSUE TITLE
Upgrade Zig Version to 0.13.0

### ISSUE THREAD

**Issue by ricardo-valero** [roc-lang/roc#6875]
Is there anything stopping us from upgrading to the latest Zig version (0.13.0)?

Current Zig version:
https://github.com/roc-lang/roc/blob/1bcf30391baef2cd19ff2158ba78748b67d3ddd1/nix/compile-deps.nix#L3

I am encountering issues building from source using Nix on Darwin aarch64:
https://github.com/NixOS/nixpkgs/issues/299091

**Comment by lukewilliamboswell** [comment]
We discussed it briefly at https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/Zig.200.2E12.2E0/near/444208611

Essentially just needs someone to make it happen I think.

**Comment by jpospychala** [comment]
great to see it happening in #6921 thank you @lukewilliamboswell

**Comment by lishaduck** [comment]
@skyqrose, can this be closed now that #6921 is merged?
