### ISSUE TITLE
Feature request: Julia-style "next command" down key in the REPL

### ISSUE THREAD

**Issue by ageron** [roc-lang/roc#6877]
Julia's REPL has a really nice feature: when you press the down key, if you just picked and executed a command in the history, it will select the following command in the history.

For example:
```julia
julia> 1+1
2
julia> 2+2
4
julia> 3+3
6
julia> 4+4
8
julia> 2+2        #<-- this command was selected in the history by type <up><up><up>
4
julia> 3+3        #<-- this command was selected simply by typing <down>
```

Rationale: it's very common to want to execute several commands in a row from the history (perhaps skipping or editing a few of them). If these commands are far up in the history, then it's cumbersome to have to go back up for each one. Thanks to this "next command" feature, you only need to go back up once.

It's probably not very hard to implement, and it's a real pleasure to use. Why not in Roc's REPL?

**Comment by Anton-4** [comment]
I'd be fine with that addition, we rely on [rustyline](https://github.com/kkawakam/rustyline) for these things. Would you be willing to add an issue to rustyline for this? That way all projects relying on rustyline will be able to use this feature :)

**Comment by ageron** [comment]
Yes, I started looking at that yesterday and I noticed that it's rustyline under the hood. I'll file an issue over there. 👍

**Comment by ageron** [comment]
Here's the rustyline issue I just created: https://github.com/kkawakam/rustyline/issues/781
