### ISSUE TITLE
Variable can be used before it is defined

### ISSUE THREAD

**Issue by dykstrom** [roc-lang/roc#6897]
This example program builds and runs fine, even though variable "bar" is undefined when it is used.

I am using roc nightly pre-release, built from commit 3abc276 on Fri Jul  5 09:11:06 UTC 2024.
Operating system: macOS.

```roc
app [main] {
    cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.11.0/SY4WWMhWQ9NvQgvIthcv15AUeA7rAIJHAHgiaSHGhdY.tar.br",
}

import cli.Stdout

foo = \value -> value

main =
    x = foo bar
    bar = 17
    Stdout.line! "Value: $(Num.toStr x)"
```

**Comment by bhansconnect** [comment]
This is actually expected in current roc. Since there are only immutable values and not actual variables, this is totally. That said, we do have plans to make it a warning in the future.

**Comment by dykstrom** [comment]
Well, if it is by design, then we can close this issue. But it was a bit surprising to me, so I would certainly appreciate a warning.
