### ISSUE TITLE
Values after comments in records are not correctly formatted

### ISSUE THREAD

**Issue by sebsheep** [roc-lang/roc#690]
The following snippet should not change after reformatting (or does it?)

```
{
    y: # comment 1
        41,
 }
```

However, it is transformed to (note the additional indentation before 41):
```
{
    y: # comment 1
            41,
 }
```

(note that the trailing comma is now valid syntax, see #546 )

**Comment by JanCVanB** [comment]
FWIW, the above example now seems to format to
```
{
    y: # comment 1
    41,
}
```
