### ISSUE TITLE
Failed to rebuild zig-platform from "platform-switching"

### ISSUE THREAD

**Issue by gthvn1** [roc-lang/roc#7018]
:wave:
I'm starting to play with platform so I tried to run [platform-switching](https://github.com/roc-lang/roc/tree/main/examples/platform-switching). The default C platform is working well as expected. But when I tried to switch to the zig-platform I got the following error:
```
❯ roc run
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Error:
    Failed to rebuild host.zig:
        The executed command was:
            zig build-exe -fPIE -rdynamic zig-platform/libapp.so /tmp/host_bitcoded8F4B0tY.o zig-platform/host.zig -femit-bin=zig-platform/dynhost --mod glue::/home/gthvn1/git/roc/crates/compiler/builtins/bitcode/src/glue.zig --deps glue -lc -target x86_64-native -fcompiler-rt
        stderr of that command:
            error: unrecognized file extension of parameter 'glue'

Location: crates/compiler/build/src/link.rs:1426:21
```

I just replaced in the *main.roc* this line:
```
diff --git a/examples/platform-switching/main.roc b/examples/platform-switching/main.roc
index d33bf330b..f3492a0a6 100644
--- a/examples/platform-switching/main.roc
+++ b/examples/platform-switching/main.roc
@@ -1,3 +1,3 @@
-app [main] { pf: platform "c-platform/main.roc" }
+app [main] { pf: platform "zig-platform/main.roc" }

 main = "Which platform am I running on now?\n"
```
I have build ROC from source and the HEAD is faeea52878ee94a6705e5fa71d6cfd2bc40418c4

If I can help more don't hesitate,
Thx for Roc :+1:

**Comment by gthvn1** [comment]
Note that it also fails with same error when using wasm-platform and it works fine with rust-platform.
I'm using zig version 0.13.0.

**Comment by lukewilliamboswell** [comment]
For current main we are still using zig 0.11.0. The issue you are seeing here is that in `examples/platform-switching/zig-platform/host.zig` the glue module `const str = @import("glue").str;` is being provided when the cli is "rebuilding" the platform host. This feature using the `--mod` argument to zig cli was changed in 0.13.0 and is no longer available. 

If you would like to use 0.13.0, I have bee working on the https://github.com/roc-lang/roc/tree/upgrade-llvm-zig branch which upgrades to zig 0.13.0 and llvm 18. It should work for you ok there. That upgrade is basically done, I just haven't finished the last upgrade on the wasm-repl crates -- which I'm basically waiting for other PR's to land first to I can merge breaking changes I know are there.

**Comment by lukewilliamboswell** [comment]
Please let me know if this resolves your issue, or if you would like further assistance. 

If you message me on zulip I can also share notes I have been collecting on roc platform development which may be helpful for you to learn more about the different parts that make a platform.

**Comment by gthvn1** [comment]
I tried with zig 0.11 and yes it fixes the issue for the zig platform :+1: 
I also tried to use zig 0.13 using *upgrade-llvm-zig* but it looks like I have another error:
```
cannot find `glue.zig`. Check the source code in find_zig_glue_path() to show all the paths I tried.
Location: crates/compiler/build/src/link.rs:118:5
```
So probably the zig-platform needs a new `glue.zig` file to work...

I will send you a message on zulip I will be happy to get some infos about platform development. I already try to read https://lukewilliamboswell.github.io/roc-ray-experiment/ but it is not that easy :)

Thx for you help,
