### ISSUE TITLE
Alignment in structs & unions

### ISSUE THREAD

**Issue by folkertdev** [roc-lang/roc#703]
Struct fields that are not a full word cause any subsequent fields to be unaligned. For instance this program is fine

    Tree : [ Node Tree Bool, Empty ]

    balance : Tree
    balance = 
        Node Empty True

    rocMain : Effect.Effect {} as Fx
    rocMain =
        when balance is
            Node _ _ -> Effect.putLine "Yay"
            _ -> Effect.putLine "Nay"

But this one is not

    Tree : [ Node Bool Tree, Empty ]

    balance : Tree
    balance = 
        Node True Empty

    rocMain : Effect.Effect {} as Fx
    rocMain =
        when balance is
            Node _ _ -> Effect.putLine "Yay"
            _ -> Effect.putLine "Nay"

The only difference is the position of the Bool (represented as i1). We get the same problem for a union stored in a `i8`, and presumably the problem is the same for `i16` and `i32`. Because the smaller-than-word value is stored before the pointer, a read of the pointer is unaligned.

There may be a llvm-specific solution, where loads/stores of these types are marked as `align 1` (for `i1` and `i8`, "align number-of-bytes" in general). But with the `x86` backend in mind, we probably should generate `Layout`s in such a way that all the smaller-than-word values are at the back of the struct and aligned properly.

**Comment by lukewilliamboswell** [comment]
@folkertdev it looks like this issue has been resolved.

```
% roc dev test.roc
Yay
```

```elixir
app "aoc-2022"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br" }
    imports [
        pf.Stdout,
        pf.Task.{ Task },
    ]
    provides [main] to pf

Tree : [ Node Bool Tree, Empty ]

balance : Tree
balance = 
    Node Bool.true Empty

main : Task {} []
main =
    when balance is
        Node _ _ -> Stdout.line "Yay"
        _ -> Stdout.line "Nay"
```
