### ISSUE TITLE
Num.powInt overflow behavior

### ISSUE THREAD

**Issue by KilianVounckx** [roc-lang/roc#7062]
When `Num.powInt` overflows, it doesn't panic, but silently returns 0.

To replicate, enter `Num.powInt (Num.toU8 2) 8` in the repl.

**Comment by KilianVounckx** [comment]
@lukewilliamboswell I wrote this sample program:

```roc
app [main] {
    cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.15.0/SlwdbJ-3GR7uBWQo6zlmYWNYOxnvo8r6YABXD-45UOw.tar.br",
}

import cli.Stdout

main : Task {} _
main =
    x : U8
    x = 2
    y = Num.powInt x 8
    Stdout.line! (Num.toStr y)
```

I again get an output of `0` when building with `--optimize` and then running the executable.

I am using Pop-OS! on an x86_64 machine

**Comment by shua** [comment]
I can take this ticket
