### ISSUE TITLE
List.dropAt drops the wrong index

### ISSUE THREAD

**Issue by ageron** [roc-lang/roc#7065]
It looks like `List.dropAt` is currently broken:

```
  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» [0,10,20,30,40,50] |> List.dropAt 0

[10, 20, 30, 40, 50] : List (Num *)               <-- OK
» [0,10,20,30,40,50] |> List.dropAt 1

[0, 10, 20, 30, 40] : List (Num *)                <-- WRONG!
» [0,10,20,30,40,50] |> List.dropAt 2

[0, 10, 20, 30, 40] : List (Num *)                <-- WRONG!
» [0,10,20,30,40,50] |> List.dropAt 3

[0, 10, 20, 30, 40] : List (Num *)                <-- WRONG!
» [0,10,20,30,40,50] |> List.dropAt 4

[0, 10, 20, 30, 40] : List (Num *)                <-- WRONG!
» [0,10,20,30,40,50] |> List.dropAt 5

[0, 10, 20, 30, 40] : List (Num *)                <-- OK
» [0,10,20,30,40,50] |> List.dropAt 6

[0, 10, 20, 30, 40, 50] : List (Num *)            <-- OK
```

**Comment by ageron** [comment]
```bash
$ roc version
roc nightly pre-release, built from commit 9a4d556 on Sat Sep  7 09:02:00 UTC 2024
```

**Comment by ageron** [comment]
I'm really surprised this regression didn't break any tests.
It looks like none of the [existing test cases](https://github.com/roc-lang/roc/blob/9a4d55672551fb4ffb54983272bb02d119c19f85/crates/compiler/test_gen/src/gen_list.rs#L544) cover the case where you drop at an index in the middle of the list. As a result, none of the tests go past [this line in the Zig implementation](https://github.com/roc-lang/roc/blob/9a4d55672551fb4ffb54983272bb02d119c19f85/crates/compiler/builtins/bitcode/src/list.zig#L631).

**Comment by Anton-4** [comment]
Thanks for the investigation @ageron!
We should definitely:

- [ ] add your examples to the tests
