### ISSUE TITLE
Use ?? for Providing Defaults for Results

### ISSUE THREAD

**Issue by smores56** [roc-lang/roc#7089]
We want to add a new operator ?? that acts as a `Result.withDefault` equivalent. Some example usages:

```roc
configFile = args.configFile ?? "~/.config/service.json"

dataItems =
    Config.readFile! configFile
   |> Result.try Json.decode
    ?? ["abc", "def", "ghi"]
```

It should be equal precedence to the `|>` pipeline operator, such that it can be used after a pipeline. The two above formattings are the only legal formattings.

If a pure handler is used with the new ?? "Result.withDefault" operator, we should raise a warning that the error mapping is unnecessary, since it will always be discarded by ??.

**Comment by gamebox** [comment]
Do we still want to try to land this before static dispatch?  If so, I can take this on.

**Comment by smores56** [comment]
Richard still wants this, I think it's good, so go for it! Two things:
- I wouldn't desugar to `Result.withDefault`, but instead to a `when res is; Ok val -> val; Err _err -> default`, because then this is short circuiting and won't run unnecessary default logic code
- We can start with a desugaring version, that should be much easier to implement, but long-term we'll want a proper canonicalization node for this so that we can give proper type errors. There's definitely `try`/`?` code that can be reused there. That said, I'd definitely recommend making a separate PR if you want to take up that challenge, because it's significantly more effort to understand type constraining than it is to just desugar to a when expression.

**Comment by gamebox** [comment]
Ok, I got my first program to run with this feature added!

```roc
app [main] {
    pl: platform "https://github.com/roc-lang/basic-cli/releases/download/0.17.0/lZFLstMUCUvd5bjnnpYromZJXkQUrdhbva4xdBInicE.tar.br",
}

import pl.Stdout
import pl.Stdin

echo_input = \{} ->
    input = Stdin.line!
    num = Str.toU8 input ?? 255
    Stdout.line! "Did you write $(Num.toStr num) (Y/n)"

main =
    echo_input! {}
```

Here's some test runs:

```sh
❯ ../../roc/target/debug/roc build
0 errors and 0 warnings found in 561 ms while successfully building:

    main

❯ ./main
423142
Did you write 255 (Y/n)

❯ ./main
33
Did you write 33 (Y/n)

```
