### ISSUE TITLE
Is there a syntax for creating extend record based on the old

### ISSUE THREAD

**Issue by lost22git** [roc-lang/roc#7121]
```roc
user = {name: "foo"}

userExtend = {user | age: 10} # => {name: "foo", age: 10}
```

**Comment by lukewilliamboswell** [comment]
Yes you can use `&` instead of `|`, see also https://www.roc-lang.org/tutorial#making-records-from-other-records

**Comment by lost22git** [comment]
`&` can only update exist fields, not append fields

**Comment by lukewilliamboswell** [comment]
I'm not sure the best way to explain it, but my understanding is that Roc is not a dynamic language like Python or JavaScript, the types are static at compile time.

**Comment by lost22git** [comment]
OK, i see...and thanks ;)
