### ISSUE TITLE
Cargo build fails with error: no field named 'path' in union 'Build.LazyPath'

### ISSUE THREAD

**Issue by socialmediarefugee** [roc-lang/roc#7132]
Issuing cargo clean && cargo build fails with an error that I am unsure of whether to report here or with the zig folks.

~/Documents/Projects/roc$ zig version
0.13.0

:~/Documents/Projects/roc$ rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)

~/Documents/Projects/roc$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

 wsl -v
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4169

...

 Compiling wasm-bindgen-shared v0.2.87
error: failed to run custom build command for `roc_bitcode v0.0.1 (/mnt/c/Users/sunshine/Documents/Projects/roc/crates/compiler/builtins/bitcode)`

Caused by:
  process didn't exit successfully: `/mnt/c/Users/sunshine/Documents/Projects/roc/target/debug/build/roc_bitcode-3c96ef726963ba2b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs
  Compiling zig object `object` to: /mnt/c/Users/sunshine/Documents/Projects/roc/crates/compiler/builtins/bitcode/zig-out/builtins-host.o

  --- stderr
  An internal compiler expectation was broken.
  This is definitely a compiler bug.
  Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
  zig build object -Drelease=true failed with:

    /mnt/c/Users/sunshine/Documents/Projects/roc/crates/compiler/builtins/bitcode/build.zig:19:38: error: no field named 'path' in union 'Build.LazyPath'
  /snap/zig/11625/lib/std/Build.zig:2171:22: note: union declared here

**Comment by Anton-4** [comment]
Hi @socialmediarefugee,
We're still on zig 0.11, an upgrade to 0.13 is [in the works](https://github.com/roc-lang/roc/pull/6921).
