### ISSUE TITLE
Order matters when sets within records are compared

### ISSUE THREAD

**Issue by ageron** [roc-lang/roc#7144]
Comparing records containing sets does not work as expected:

```roc
{foo: Set.fromList [1,2]} == {foo: Set.fromList [1,2]}  # returns Bool.true => OK
{foo: Set.fromList [1,2]} == {foo: Set.fromList [2,1]}  # returns Bool.false => ERROR
```

This is most likely the same underlying issue as #7111, but perhaps not.

**Comment by bhansconnect** [comment]
Yeah, this will be the same root issue as #7111 

duplicate of #7111
