### ISSUE TITLE
Remove deprecated string interpolation syntax

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#7148]
Remove the old string interpolation syntax `"\(var)" which has been deprecated in favour of the new `"$(var)` syntax and is no longer required. 

It is ok to break existing code -- as this syntax has been deprecated for some time and there are numerous other breaking changes that have occurred since then. Any code still using the old syntax would likely require other updates also.

**Comment by hrishisd** [comment]
I'd like to give this a shot. Is there an assignment mechanism or should I just get started?

**Comment by Anton-4** [comment]
Thanks for helping out @hrishisd!
I've assigned you to the issue
