### ISSUE TITLE
Allow multi-line editing in REPL

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#718]
Some languages have multi-line editing using some special symbols to indicate another line is going to follow.
Others detect if what is entered is a parseble expression or statement, this could be a pain to implement.

My personal preference goes to `Shift+Enter`, which is commonly used to go to the next line without submitting when using text-areas.

I'll ask in the chat before implementing.

**Comment by ghigt** [comment]
Is it linked with #2666?

**Comment by Anton-4** [comment]
Yes indeed. Having this implemented would be a significant improvement in repl UX.

**Comment by Anton-4** [comment]
We use rustyline for generic repl features. [This rustyline example](https://github.com/kkawakam/rustyline/blob/ca62587632607524b8e310be6b3677e4299102b7/examples/input_multiline.rs#L17) adapted for `Shift+Enter` might be all that's needed. Are you interested in giving that a try @ghigt?

**Comment by ghigt** [comment]
Yes, I tried it before, but while this works
```rust
rl.bind_sequence(
    KeyEvent(KeyCode::Char('s'), Modifiers::CTRL),
    EventHandler::Simple(Cmd::Newline),
);
```
This is handled by the default `Enter` behavior:
```rust
rl.bind_sequence(
    KeyEvent(KeyCode::Enter, Modifiers::SHIFT),
    EventHandler::Simple(Cmd::Newline),
);
```

**Comment by Anton-4** [comment]
Oh I see, can you file an issue for that on the [rustyline repo](https://github.com/kkawakam/rustyline/issues)?

**Comment by ghigt** [comment]
https://github.com/kkawakam/rustyline/issues/653

**Comment by Anton-4** [comment]
Thanks @ghigt!

**Comment by ghigt** [comment]
His response makes sens, do you think about an alternative?

**Comment by Anton-4** [comment]
Interesting, `Ctrl+s` is probably good.

**Comment by ghigt** [comment]
I don't want to enter into a battle 😇, but I associate `Ctrl+s` with "save", is there a particular reason that I don't know for the `s` key?

I would associate a newline with `Ctrl+n` or `Ctrl+o` (like in vim mode).

**Comment by Anton-4** [comment]
The main thing I like about `Ctrl+s` is that it is easy to reach single-handedly.

**Comment by lukewilliamboswell** [comment]
@Anton-4 recommend this be closed as completed. Just using enter on an expression that isn't complete seems to work fine. 

```sh
% roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» greeting : Str
… greeting = "Hi"

"Hi" : Str            # greeting

» 
```

**Comment by Anton-4** [comment]
Thanks for notifying me @lukewilliamboswell :)
