### ISSUE TITLE
failed to open file "../../basic-ssg/platform/dynhost": No such file or directory (os error 2)

### ISSUE THREAD

**Issue by jfkonecn** [roc-lang/roc#7197]
I'm working on [this issue](https://github.com/roc-lang/roc/issues/7076) to add an LLM friendly text file to the roc website. In order to support this, I made some changes to [basic-ssg](https://github.com/jfkonecn/basic-ssg/commit/7a229cae3801edf45cbf25c80ae9e57bd7726dd5). After adding those changes to `basic-ssg` I made [these changes](https://github.com/jfkonecn/roc/commit/e80e6a937ad25d1780f1765b01c9734cad0fabb1) to the roc website code and now I'm getting a compiler error. 

```sh
$ ./www/build-dev-local.sh
++ dirname ./www/build-dev-local.sh
+ DIR=./www
+ cd ./www
+ rm -rf dist/
+ cp -r build dist/
+ cp -r public/favicon.svg public/license public/site.css public/site.js public/zulip-icon-circle.svg dist/
+ roc run main.roc -- content/ dist/
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
failed to open file "../../basic-ssg/platform/dynhost": No such file or directory (os error 2)
Location: crates/linker/src/lib.rs:552:29
```

I think it might be these lines of code that are causing the issue.

```roc
SSG.readFile markdownPath
|> Task.await (\x -> SSG.writeFile { outputDir, relpath: llmRelPath, content: x })
```

**Comment by lukewilliamboswell** [comment]
If you're on linux you will need `--prebuilt-platfrom` flag as this platform only build the legacy host prebuilt binaries.

**Comment by jfkonecn** [comment]
Thanks for the quick reply!

I wasn't able to get it to work, but it does seems like those two lines of code are the problem.

I figured out a [simpler solution](https://github.com/roc-lang/roc/pull/7200) that doesn't require changes to the platform so I'm going to close this issue.
