### ISSUE TITLE
Update tutorial with recent syntax changes

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#7242]
I've already started editing `tutorial.md` locally, but I'm creating this to track the variety of changes we need/want:

(sorted by first impacted location in tutorial)

- [x] Minimize `!"` use in example strings, to help effectful function names pop and prevent exclamation fatigue
- [x] Bump dependencies to the best ones for December (frozen during AoC)
- [ ] ~Update `main =`s to `main! = \{} ->`s~ [full explanation postponed for purity inference delay]
- [x] Update `Stdfoo.bar`s to `Stdfoo.bar!`s
- [x] Explain early return (`return`)
- [x] Explain early error return (`try`)
- [x] ~Explain~ Preview effectful functions syntax+concepts (`!`) [full explanation postponed for purity inference delay]
- [x] ~Explain~ Preview effectful function type (`=>`) [full explanation postponed for purity inference delay]
- [ ] ~Remove `Tasks` section and all references to task-related vocabulary~ [postponed for purity inference delay]
- [x] Preview `Tasks` section removal
- [x] Polish language around "`!` postfix operator"
- [x] Add section on "Ignoring informationless return values"

[See [discussion of purity inference delay](https://roc.zulipchat.com/#narrow/channel/302903-platform-development/topic/Platform.20.2F.20Language.20version.20compatibility/near/485003658).]

~PR coming soon!~

- [ ] Additional TODO: Add `try` versions to [Result parsing/trying examples file](https://github.com/roc-lang/examples/blob/main/examples/Results/main.roc)

**Comment by JanCVanB** [comment]
I wonder how many days before AoC 1% of participants start learning a new language.

**Comment by ErikFeeley** [comment]
I am not new to the language but I had thought about freshening up on Roc as early as a week or two ago when thinking about using it for AoC this year.

**Comment by JanCVanB** [comment]
@ErikFeeley Thank you! That's helpful to know. If you want, I can ping you again next week for feedback on the updated tutorial. 🙂

**Comment by fpsvogel** [comment]
I **am** new to the language, except for a read-through of the tutorial a couple months ago, after which life got busy and now I'm coming back to give Roc a proper try (pun intended).

Thank you for working on the tutorial! If you want feedback from a newbie, let me know.

**Comment by ErikFeeley** [comment]
@JanCVanB sounds good but no worries! I am honestly not sure how much time I'll get to dedicate to AoC this year. But I'll try to give some feedback if I get around to giving it a go :).

**Comment by JanCVanB** [comment]
PR #7274 now includes all of the latest suggestions, except for the previews of purity inference syntax. Feedback and additional requests welcome! I'm logging off for the day, but I expect to add the previews tomorrow then seek merge approval.

**Comment by JanCVanB** [comment]
@ErikFeeley @fpsvogel The PR is ready for full review! I expect that today these changes will go live on the tutorial webpage, so feel free to read them whenever, in either place.

**Comment by JanCVanB** [comment]
@ErikFeeley @fpsvogel PR merged and tutorial updated! Feedback welcome :)
