### ISSUE TITLE
Str.countGraphemeClusters generates a lot of data

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#727]
This may not be a bug, but it should still be inspected. The `.o` files generated by zig are about 110k in size. Over 100k of that is from `Str.countGraphemeClusters`. Currently we don't actually use the zig `.o` file, but it will be used by the dev backend eventually. Also, I haven't checked, but likely the `.ll` file we use also carries this bloat with it.

To generate a sample `.o` file:
```
cd compiler/builtins
zig build-obj bitcode/src/main.zig --strip -O ReleaseFast -fPIC
```
After that you should have a `main.o` file that contains all of the zig builtins.

If you comment out [this line](https://github.com/rtfeldman/roc/blob/5eee74f209ea8bd1ff5f27e955d39d86010d33e8/compiler/builtins/bitcode/src/main.zig#L17), you should be able to generate the version without all the bloat from `Str.countGraphemeClusters`. We should just double check that this function is being doing what we want and not generating extra data for no good reason.

**Comment by skyqrose** [comment]
`countGraphemeClusters` is no longer in `Str`
