### ISSUE TITLE
Dec multiply is not reporting overflow

### ISSUE THREAD

**Issue by shua** [roc-lang/roc#7276]
From the following repl output:
```
» Num.mulSaturated 170_141_183_460_469_231_731dec 2

-1.374607431768211456 : Dec
» Num.mulChecked 170_141_183_460_469_231_731dec 2

Ok -1.374607431768211456 : Result Dec [Overflow]
» Num.mul 170_141_183_460_469_231_731dec 2

-1.374607431768211456 : Dec
```
I would expect all three to indicate overflow either via panic, `Err` or returning `Dec` maximum value, but instead they all return a sort of wrapped multiplication.

This also shows up outside the repl:
```
app [main] { pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.17.0/lZFLstMUCUvd5bjnnpYromZJXkQUrdhbva4xdBInicE.tar.br" }

import pf.Stdout

main =
    Stdout.line! (Num.toStr (Num.mul 170_141_183_460_469_231_731dec 2))

# output:
# -1.374607431768211456
```

Which indicates this is not specific to the gen-dev backend but rather the zig bitcode implementation. `mulWithOverflow` is the place to look: https://github.com/roc-lang/roc/blob/0e550a7f68f53d8699d484a426cd4963e0110539/crates/compiler/builtins/bitcode/src/dec.zig#L310

Found as part of work on #7264

**Comment by bhansconnect** [comment]
I have a fix on the `dec-mul` branch. Just waiting on https://github.com/roc-lang/roc/pull/7264 to land before I make a PR.

**Comment by lukewilliamboswell** [comment]
@bhansconnect that PR has merged, in case you missed it.
