### ISSUE TITLE
Apparent memory corruption during REPL tests

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#729]
One time when running `cargo test` on f6e42e610f85d183c7e47a5446335b6173dd418c I encountered this:

<img width="881" alt="Screen Shot 2020-11-23 at 12 21 46 AM" src="https://user-images.githubusercontent.com/1094080/99931286-f014d580-2d21-11eb-9bb6-3ad8d0b2d5da.png">

Another time I saw one of the repl tests fail with this:

```
roc(63840,0x1198b5dc0) malloc: *** error for object 0x7fc0d7926200: pointer being freed was not allocated
roc(63840,0x1198b5dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```

I haven't been able to reproduce either of these, though - so it seems like some test was affecting another test.

Still, I'm writing them down in hopes that if they turn up again in the future, we can use these past data points to help investigate.

(If the year is 2022 or later, and we've had no further reports of this since 2020, seems safe to close it!)

**Comment by JanCVanB** [comment]
>(If the year is 2022 or later, and we've had no further reports of this since 2020, seems safe to close it!)

🙂👍🏻
