### ISSUE TITLE
Deadlock in loading

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#731]
When running `cargo test --release` on a989d4823914fe7c77d75a9d664fbadb2027e2d2 I saw a test get stuck and hang - specifically `app_dep_types` in `test_load`.

I re-ran `cargo test --release` and the tests all passed, so it may take multiple runs to reproduce. I wanted to file this so we know it's out there and can happen!

**Comment by JanCVanB** [comment]
It seems safe to close this now, but feel free to reopen!
