### ISSUE TITLE
trailing comma inside `when ... is` → compiler error

### ISSUE THREAD

**Issue by lue-bird** [roc-lang/roc#7327]
```roc
exampleRecord = {
    field:
    when [] is
        [] -> []
        [_, ..] ->
            [],
}
```
the compiler prints the error
```
── RECORD PARSE PROBLEM in src/testing.roc ─────────────────────────────────────

I am partway through parsing a record, but I got stuck here:

18│  exampleRecord = {
                     ^

TODO provide more context.
```

I tested with list commas and record commas.
The problem arises _only_ when the trailing comma is indented _more_ than the last case pattern.

For context, I discovered this only because the formatter always places commas in exactly these indentation levels
but it isn't the root of the problem here.

- roc nightly pre-release, built from commit https://github.com/roc-lang/roc/commit/d7825428df72e3685be7291284c5eeeb1300a7f6

Thanky <3

**Comment by joshuawarner32** [comment]
By coincidence I think this was fixed in 0cc16b0d2c7318b99b8fa271fa56c68c370655c8
