### ISSUE TITLE
repl: input "1e10" results in ICE Invalid decimal for float literal

### ISSUE THREAD

**Issue by mocompute** [roc-lang/roc#7351]
Using revision 27b36a8f1fd02d0c88e18a390fc48414739fd68b:

```
[mo@nixos:~/dev/roc/]$ roc repl

  The rockin' roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» 1e10
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Invalid decimal for float literal = 1e10. This should be a type error!
Location: crates/compiler/mono/src/ir/literal.rs:115:25
```

**Comment by lukewilliamboswell** [comment]
Note giving it an annotation for `F64` works ok, I suspect this is related to `Dec`
```
» 1e10f64

10000000000 : F64
```

@shua are you interested in this issue?

**Comment by lukewilliamboswell** [comment]
Looks like this is in Mono - not dev backend specifically.

> Brendan Hansknecht: inbetween the two in mono
> Brendan Hansknecht: rocdec from str failed
> Brendan Hansknecht: it doesn't understand e I guess

**Comment by shua** [comment]
@lukewilliamboswell  I'm interested, but not really available until after new years, so you can leave it unassigned in case someone else wants to pick it up sooner.

**Comment by lukewilliamboswell** [comment]
No worries @shua -- I'll assign it to you. But no rush. Just chip away whenever suits you or let me know if you want to do other things instead.
