### ISSUE TITLE
Using fewer bytes for the tag discriminant

### ISSUE THREAD

**Issue by folkertdev** [roc-lang/roc#739]
In theory most tag unions need only a byte (or perhaps two) to store the tag discriminant, yet currently we always use a `i64`, and that `i64` is always the first 8 bytes of the tag union in memory.

Making the discriminant smaller means that (because of alignment) it's likely not the first 8 bytes any more. Still, we need to be able to know statically where the tag ID is located, and this location must be the same for all variants.

Say we have this type

    These a b : [ This a, That b, These a b ]

and instantiate it with `a = I64, b = I64`, we store the tag efficiently (3 options, so as a I8) and sort for aligmnent, then the layout is

    Union( [ I64, I8 ], [ I64, I8 ], [ I64, I64, I8 ]

Problem is: how do we find the tag discriminant? we need to know the tag id to know the index, for which we need to know the tag id, etc.

So, the tag must be stored at the same position for every tag in the tag union, but that does not always work with the alignment. A possible solution is to use padding in a smart way, but in any case this will require substantial changes to pattern match compilation.

I made an initial attempt on the `smaller-tag-id-attempt` branch.

**Comment by rtfeldman** [comment]
@folkertdev can this be closed?

**Comment by folkertdev** [comment]
yes, the tag is now smaller, although alignment may still cause more space to be used in practice
