### ISSUE TITLE
Incorrect links in generated docs for packages with submodules

### ISSUE THREAD

**Issue by imclerran** [roc-lang/roc#7417]
## Description

When generating documentation for a Roc package using roc docs, submodules (e.g., Sub.Module) result in incorrect links. While the module name is correctly identified as Sub.Module, the corresponding HTML file is placed in a directory structure like Sub/Module. However, the generated links in the documentation point to Sub.Module, resulting in 404 errors.

## Steps to Reproduce

1. Create the following file structure:
    **main.roc:**
    ```
    package [Sub.Module] {}
    ```
    **Sub/Module.roc:**
    ```
    module []
    ```

2. Run `roc docs` to generate the documentation.
3. Open the generated documentation and inspect the links for Sub.Module.

## Expected Behavior
The generated links in the documentation page should point to the correct location, such as `href="Sub/Module"`.

## Actual Behavior
The links incorrectly point to `Sub.Module`, causing 404 errors.

## Additional Information
The docs pages are generated correctly, it is just the links that are broken.

**Comment by imclerran** [comment]
This issue can also be observed in the wild at: https://www.imclerran.com/roc-openrouter/

**Comment by lukewilliamboswell** [comment]
Closed by #7418
