### ISSUE TITLE
Improve RC based on Perceus

### ISSUE THREAD

**Issue by folkertdev** [roc-lang/roc#825]
We currently implement reference counting based on the "Counting immutable beans" paper. Recently we learned about its successor [Perceus](https://www.microsoft.com/en-us/research/uploads/prod/2020/11/perceus-tr-v1.pdf).

Based on my current understanding, it has these practical advancements over the "Beans" system:

* fusing of increments/decrements of a structure and its fields
* allow setting of individual fields on a constructor (see their RBTree example)

It also looks like they do this without a fixed-point analysis, but I'm not entirely sure yet how.

If we want to implement this, I think we should make recursive tag unions live on the heap (always, even the "first" node). I think this is required for the reuse to work at all. 

But of course we should first see if maybe we can do these things statically, with aliasing and/or uniqueness analysis.

other links

* [one of the authors answering questions on reddit](https://www.reddit.com/r/ProgrammingLanguages/comments/k9ixz2/perceus_garbage_free_reference_counting_with_reuse/)

**Comment by skyqrose** [comment]
This is done now: https://github.com/roc-lang/roc/pull/5258
