### ISSUE TITLE
Run valgrind tests on CI if CPU can execute it correctly

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#827]
For caching we took the CPU model into account, @bhansconnect figured out we can use the same approach to run valgrind without errors.

- [ ] Run valgrind tests if CPU is Xeon E5-2673 **v4**. 
- [ ] The E5-2673 **v3** could work as well, this should be tested.
- [ ] Only compile valgrind if we're using a CPU that can run it.
- [ ] Skip valgrind tests without errors if we're on a unsupported CPU.
- [ ] We used to run `cargo test -- --ignored` for the valgrind tests. It's better to filter ignored tests on "valgrind"  for clarity.

**Comment by skyqrose** [comment]
Valgrind runs in CI now (I think)

**Comment by Anton-4** [comment]
It does :)
