### ISSUE TITLE
Benchmark memory allocation approaches for the variable returned from `TextBuffer::all_lines`.

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#900]
Memory usage and execution speed should be compared for:
- Bump allocation
- [Pool allocation](https://github.com/rtfeldman/roc/pull/892#issuecomment-760646503)
- "rust default allocation" using `std::string::String`

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
