### ISSUE TITLE
Use actor model for plugins?

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#914]
The actor model seems well suited for communication between plugins and the core editor.
- It naturally fits the elm architecture with its message passing.
- It allows for easy safe concurrency.
- It allows us to control resources (e.g. CPU cores) well so that the execution speed of the core editor can be guarded.
- Nice separation between every plugin and the core, good for reliability and controlling access to editor state.

[actix](https://github.com/actix/actix) could be used for the platform.

I have very fond memories of the [akka](https://akka.io/) actor framework. It can be good inspiration on how to use actors well.

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
