### ISSUE TITLE
Undo and redo

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#936]
- [ ] investigate efficient recording of transformations to support undo and redo
- [ ] undo char insert on `Ctrl+Z`
- [ ] redo char insert on `Ctrl+Y` and `Ctrl+Shift+Z`
- [ ] support undoing all actions that would make sense to be undoable
- [ ] support redoing all undoable actions
- [ ] write tests
- [ ] write benchmarks

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
