### ISSUE TITLE
UI mockup in Elm (elm-ui)?

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#959]
I've been talking with @popara and we're considering to do further prototyping in Elm.
Due to the complexity of the editor it's a lot of work to create mockups in figma, especially if we want to add some interactivity.
I think we planned to do the UI framework in roc following The Elm Architecture @rtfeldman, so there would be little duplication of work. It's also difficult to judge if a certain layout would work well in practice without proper interactivity.

 I've also been thinking [elm-ui](https://github.com/mdgriffith/elm-ui) is a great battle-tested design toolkit we could clone in roc.
 If we planned to use an elm-ui like toolkit for the editor it would be beneficial to use it in the mockups as well.
 
 All text editing functionality would likely be omitted as this would duplicate rust code.
 
 CC @rvcas

**Comment by skyqrose** [comment]
Editor is no longer being worked on, and has been removed from the repo. Closing.
